# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/variables.json
Variables:
  idpConnector:
    # The proxy server URL
    apiProxyUrl: https://idp.api.axonivy.com/api
    # API Key for "IDP Document Capturing API"
    #[password]
    apiKeySecret: ${decrypt:}
    # Number of seconds to wait for the completion of document processing.
    # If processing doesn't finish in this time, a URL for retrieving the results will be returned.
    waitFor: "120"
    # The default value for validation processing result's confidence values  
    confidenceMinValue: "0.8"
    # Stand alone URL
    standAloneUrl: ""
