/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.DateExtraction1;
import com.axonivy.connector.idp.connector.model.FloatExtraction1;
import com.axonivy.connector.idp.connector.model.StringExtraction1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AccountMaintenanceCharge1
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class AccountMaintenanceCharge1 {
  @JsonProperty("start_date")
  private DateExtraction1 startDate = null;

  @JsonProperty("start_percentage")
  private FloatExtraction1 startPercentage = null;

  @JsonProperty("start_amount")
  private FloatExtraction1 startAmount = null;

  @JsonProperty("payment_interval")
  private StringExtraction1 paymentInterval = null;

  public AccountMaintenanceCharge1 startDate(DateExtraction1 startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  public DateExtraction1 getStartDate() {
    return startDate;
  }

  public void setStartDate(DateExtraction1 startDate) {
    this.startDate = startDate;
  }

  public AccountMaintenanceCharge1 startPercentage(FloatExtraction1 startPercentage) {
    this.startPercentage = startPercentage;
    return this;
  }

   /**
   * Get startPercentage
   * @return startPercentage
  **/
  public FloatExtraction1 getStartPercentage() {
    return startPercentage;
  }

  public void setStartPercentage(FloatExtraction1 startPercentage) {
    this.startPercentage = startPercentage;
  }

  public AccountMaintenanceCharge1 startAmount(FloatExtraction1 startAmount) {
    this.startAmount = startAmount;
    return this;
  }

   /**
   * Get startAmount
   * @return startAmount
  **/
  public FloatExtraction1 getStartAmount() {
    return startAmount;
  }

  public void setStartAmount(FloatExtraction1 startAmount) {
    this.startAmount = startAmount;
  }

  public AccountMaintenanceCharge1 paymentInterval(StringExtraction1 paymentInterval) {
    this.paymentInterval = paymentInterval;
    return this;
  }

   /**
   * Get paymentInterval
   * @return paymentInterval
  **/
  public StringExtraction1 getPaymentInterval() {
    return paymentInterval;
  }

  public void setPaymentInterval(StringExtraction1 paymentInterval) {
    this.paymentInterval = paymentInterval;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountMaintenanceCharge1 accountMaintenanceCharge1 = (AccountMaintenanceCharge1) o;
    return Objects.equals(this.startDate, accountMaintenanceCharge1.startDate) &&
        Objects.equals(this.startPercentage, accountMaintenanceCharge1.startPercentage) &&
        Objects.equals(this.startAmount, accountMaintenanceCharge1.startAmount) &&
        Objects.equals(this.paymentInterval, accountMaintenanceCharge1.paymentInterval);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startDate, startPercentage, startAmount, paymentInterval);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountMaintenanceCharge1 {\n");
    
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    startPercentage: ").append(toIndentedString(startPercentage)).append("\n");
    sb.append("    startAmount: ").append(toIndentedString(startAmount)).append("\n");
    sb.append("    paymentInterval: ").append(toIndentedString(paymentInterval)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
