/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ApiCoreWorkflowMetaModelsReference
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class ApiCoreWorkflowMetaModelsReference {
  @JsonProperty("page_num")
  private Integer pageNum = null;

  @JsonProperty("bbox_id")
  private Integer bboxId = null;

  public ApiCoreWorkflowMetaModelsReference pageNum(Integer pageNum) {
    this.pageNum = pageNum;
    return this;
  }

   /**
   * The number of the page that is referenced. Starts at one.
   * @return pageNum
  **/
  public Integer getPageNum() {
    return pageNum;
  }

  public void setPageNum(Integer pageNum) {
    this.pageNum = pageNum;
  }

  public ApiCoreWorkflowMetaModelsReference bboxId(Integer bboxId) {
    this.bboxId = bboxId;
    return this;
  }

   /**
   * The ID of the bounding box on this page. Starts at one.
   * @return bboxId
  **/
  public Integer getBboxId() {
    return bboxId;
  }

  public void setBboxId(Integer bboxId) {
    this.bboxId = bboxId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiCoreWorkflowMetaModelsReference apiCoreWorkflowMetaModelsReference = (ApiCoreWorkflowMetaModelsReference) o;
    return Objects.equals(this.pageNum, apiCoreWorkflowMetaModelsReference.pageNum) &&
        Objects.equals(this.bboxId, apiCoreWorkflowMetaModelsReference.bboxId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pageNum, bboxId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiCoreWorkflowMetaModelsReference {\n");
    
    sb.append("    pageNum: ").append(toIndentedString(pageNum)).append("\n");
    sb.append("    bboxId: ").append(toIndentedString(bboxId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
