/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.ResellercustomersOrganizationalInfo;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.UUID;
/**
 * ApiRoutesV3PublicResellerSchemasResponsesCustomerResponse
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class ApiRoutesV3PublicResellerSchemasResponsesCustomerResponse {
  @JsonProperty("customer_id")
  private UUID customerId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("organizational_info")
  private ResellercustomersOrganizationalInfo organizationalInfo = null;

  @JsonProperty("use_technical_interface")
  private Boolean useTechnicalInterface = null;

  public ApiRoutesV3PublicResellerSchemasResponsesCustomerResponse customerId(UUID customerId) {
    this.customerId = customerId;
    return this;
  }

   /**
   * Get customerId
   * @return customerId
  **/
  public UUID getCustomerId() {
    return customerId;
  }

  public void setCustomerId(UUID customerId) {
    this.customerId = customerId;
  }

  public ApiRoutesV3PublicResellerSchemasResponsesCustomerResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ApiRoutesV3PublicResellerSchemasResponsesCustomerResponse organizationalInfo(ResellercustomersOrganizationalInfo organizationalInfo) {
    this.organizationalInfo = organizationalInfo;
    return this;
  }

   /**
   * Get organizationalInfo
   * @return organizationalInfo
  **/
  public ResellercustomersOrganizationalInfo getOrganizationalInfo() {
    return organizationalInfo;
  }

  public void setOrganizationalInfo(ResellercustomersOrganizationalInfo organizationalInfo) {
    this.organizationalInfo = organizationalInfo;
  }

  public ApiRoutesV3PublicResellerSchemasResponsesCustomerResponse useTechnicalInterface(Boolean useTechnicalInterface) {
    this.useTechnicalInterface = useTechnicalInterface;
    return this;
  }

   /**
   * Get useTechnicalInterface
   * @return useTechnicalInterface
  **/
  public Boolean isUseTechnicalInterface() {
    return useTechnicalInterface;
  }

  public void setUseTechnicalInterface(Boolean useTechnicalInterface) {
    this.useTechnicalInterface = useTechnicalInterface;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiRoutesV3PublicResellerSchemasResponsesCustomerResponse apiRoutesV3PublicResellerSchemasResponsesCustomerResponse = (ApiRoutesV3PublicResellerSchemasResponsesCustomerResponse) o;
    return Objects.equals(this.customerId, apiRoutesV3PublicResellerSchemasResponsesCustomerResponse.customerId) &&
        Objects.equals(this.name, apiRoutesV3PublicResellerSchemasResponsesCustomerResponse.name) &&
        Objects.equals(this.organizationalInfo, apiRoutesV3PublicResellerSchemasResponsesCustomerResponse.organizationalInfo) &&
        Objects.equals(this.useTechnicalInterface, apiRoutesV3PublicResellerSchemasResponsesCustomerResponse.useTechnicalInterface);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerId, name, organizationalInfo, useTechnicalInterface);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiRoutesV3PublicResellerSchemasResponsesCustomerResponse {\n");
    
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    organizationalInfo: ").append(toIndentedString(organizationalInfo)).append("\n");
    sb.append("    useTechnicalInterface: ").append(toIndentedString(useTechnicalInterface)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
