/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * AvailableWorkflowResponse
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class AvailableWorkflowResponse {
  @JsonProperty("workflow_id")
  private String workflowId = null;

  @JsonProperty("category")
  private String category = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("long_description")
  private String longDescription = null;

  @JsonProperty("image")
  private String image = null;

  /**
   * An enumeration.
   */
  public enum VisibilityEnum {
    PUBLIC("public"),
    CUSTOM("custom");

    private String value;

    VisibilityEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static VisibilityEnum fromValue(String input) {
      for (VisibilityEnum b : VisibilityEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("visibility")
  private VisibilityEnum visibility = null;

  /**
   * An enumeration.
   */
  public enum PermissionsEnum {
    READ("read"),
    PROCESS("process"),
    MANAGE("manage");

    private String value;

    PermissionsEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PermissionsEnum fromValue(String input) {
      for (PermissionsEnum b : PermissionsEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("permissions")
  private List<PermissionsEnum> permissions = new ArrayList<>();

  @JsonProperty("retrievable_results")
  private List<String> retrievableResults = null;

  public AvailableWorkflowResponse workflowId(String workflowId) {
    this.workflowId = workflowId;
    return this;
  }

   /**
   * The unique identifier for the workflow.
   * @return workflowId
  **/
  public String getWorkflowId() {
    return workflowId;
  }

  public void setWorkflowId(String workflowId) {
    this.workflowId = workflowId;
  }

  public AvailableWorkflowResponse category(String category) {
    this.category = category;
    return this;
  }

   /**
   * Describes what kind of workflow it is, determining e.g. how it can be managed.
   * @return category
  **/
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public AvailableWorkflowResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The display name of the workflow.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AvailableWorkflowResponse description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A short summary of the workflow.
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public AvailableWorkflowResponse longDescription(String longDescription) {
    this.longDescription = longDescription;
    return this;
  }

   /**
   * A more detailed description of the workflow.
   * @return longDescription
  **/
  public String getLongDescription() {
    return longDescription;
  }

  public void setLongDescription(String longDescription) {
    this.longDescription = longDescription;
  }

  public AvailableWorkflowResponse image(String image) {
    this.image = image;
    return this;
  }

   /**
   * An image that represents or illustrates the workflow, represented as relative URL.
   * @return image
  **/
  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }

  public AvailableWorkflowResponse visibility(VisibilityEnum visibility) {
    this.visibility = visibility;
    return this;
  }

   /**
   * An enumeration.
   * @return visibility
  **/
  public VisibilityEnum getVisibility() {
    return visibility;
  }

  public void setVisibility(VisibilityEnum visibility) {
    this.visibility = visibility;
  }

  public AvailableWorkflowResponse permissions(List<PermissionsEnum> permissions) {
    this.permissions = permissions;
    return this;
  }

  public AvailableWorkflowResponse addPermissionsItem(PermissionsEnum permissionsItem) {
    this.permissions.add(permissionsItem);
    return this;
  }

   /**
   * Get permissions
   * @return permissions
  **/
  public List<PermissionsEnum> getPermissions() {
    return permissions;
  }

  public void setPermissions(List<PermissionsEnum> permissions) {
    this.permissions = permissions;
  }

  public AvailableWorkflowResponse retrievableResults(List<String> retrievableResults) {
    this.retrievableResults = retrievableResults;
    return this;
  }

  public AvailableWorkflowResponse addRetrievableResultsItem(String retrievableResultsItem) {
    if (this.retrievableResults == null) {
      this.retrievableResults = new ArrayList<>();
    }
    this.retrievableResults.add(retrievableResultsItem);
    return this;
  }

   /**
   * Lists all the results that this workflow extracts for submitted documents.
   * @return retrievableResults
  **/
  public List<String> getRetrievableResults() {
    return retrievableResults;
  }

  public void setRetrievableResults(List<String> retrievableResults) {
    this.retrievableResults = retrievableResults;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AvailableWorkflowResponse availableWorkflowResponse = (AvailableWorkflowResponse) o;
    return Objects.equals(this.workflowId, availableWorkflowResponse.workflowId) &&
        Objects.equals(this.category, availableWorkflowResponse.category) &&
        Objects.equals(this.name, availableWorkflowResponse.name) &&
        Objects.equals(this.description, availableWorkflowResponse.description) &&
        Objects.equals(this.longDescription, availableWorkflowResponse.longDescription) &&
        Objects.equals(this.image, availableWorkflowResponse.image) &&
        Objects.equals(this.visibility, availableWorkflowResponse.visibility) &&
        Objects.equals(this.permissions, availableWorkflowResponse.permissions) &&
        Objects.equals(this.retrievableResults, availableWorkflowResponse.retrievableResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workflowId, category, name, description, longDescription, image, visibility, permissions, retrievableResults);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AvailableWorkflowResponse {\n");
    
    sb.append("    workflowId: ").append(toIndentedString(workflowId)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    longDescription: ").append(toIndentedString(longDescription)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    visibility: ").append(toIndentedString(visibility)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    retrievableResults: ").append(toIndentedString(retrievableResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
