/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.DateExtraction1;
import com.axonivy.connector.idp.connector.model.StringExtraction1;
import com.axonivy.connector.idp.connector.model.Transaction1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * BankStatement
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class BankStatement {
  /**
   * Gets or Sets schemaVersion
   */
  public enum SchemaVersionEnum {
    NUMBER_1(1);

    private Integer value;

    SchemaVersionEnum(Integer value) {
      this.value = value;
    }
    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SchemaVersionEnum fromValue(Integer input) {
      for (SchemaVersionEnum b : SchemaVersionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("schema_version")
  private SchemaVersionEnum schemaVersion = SchemaVersionEnum.NUMBER_1;

  /**
   * Gets or Sets documentType
   */
  public enum DocumentTypeEnum {
    BANK_STATEMENT("bank_statement");

    private String value;

    DocumentTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static DocumentTypeEnum fromValue(String input) {
      for (DocumentTypeEnum b : DocumentTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("document_type")
  private DocumentTypeEnum documentType = null;

  @JsonProperty("transactions")
  private List<Transaction1> transactions = new ArrayList<>();

  @JsonProperty("document_date")
  private DateExtraction1 documentDate = null;

  @JsonProperty("period")
  private StringExtraction1 period = null;

  public BankStatement schemaVersion(SchemaVersionEnum schemaVersion) {
    this.schemaVersion = schemaVersion;
    return this;
  }

   /**
   * Get schemaVersion
   * @return schemaVersion
  **/
  public SchemaVersionEnum getSchemaVersion() {
    return schemaVersion;
  }

  public void setSchemaVersion(SchemaVersionEnum schemaVersion) {
    this.schemaVersion = schemaVersion;
  }

  public BankStatement documentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
    return this;
  }

   /**
   * Get documentType
   * @return documentType
  **/
  public DocumentTypeEnum getDocumentType() {
    return documentType;
  }

  public void setDocumentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
  }

  public BankStatement transactions(List<Transaction1> transactions) {
    this.transactions = transactions;
    return this;
  }

  public BankStatement addTransactionsItem(Transaction1 transactionsItem) {
    this.transactions.add(transactionsItem);
    return this;
  }

   /**
   * Get transactions
   * @return transactions
  **/
  public List<Transaction1> getTransactions() {
    return transactions;
  }

  public void setTransactions(List<Transaction1> transactions) {
    this.transactions = transactions;
  }

  public BankStatement documentDate(DateExtraction1 documentDate) {
    this.documentDate = documentDate;
    return this;
  }

   /**
   * Get documentDate
   * @return documentDate
  **/
  public DateExtraction1 getDocumentDate() {
    return documentDate;
  }

  public void setDocumentDate(DateExtraction1 documentDate) {
    this.documentDate = documentDate;
  }

  public BankStatement period(StringExtraction1 period) {
    this.period = period;
    return this;
  }

   /**
   * Get period
   * @return period
  **/
  public StringExtraction1 getPeriod() {
    return period;
  }

  public void setPeriod(StringExtraction1 period) {
    this.period = period;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankStatement bankStatement = (BankStatement) o;
    return Objects.equals(this.schemaVersion, bankStatement.schemaVersion) &&
        Objects.equals(this.documentType, bankStatement.documentType) &&
        Objects.equals(this.transactions, bankStatement.transactions) &&
        Objects.equals(this.documentDate, bankStatement.documentDate) &&
        Objects.equals(this.period, bankStatement.period);
  }

  @Override
  public int hashCode() {
    return Objects.hash(schemaVersion, documentType, transactions, documentDate, period);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankStatement {\n");
    
    sb.append("    schemaVersion: ").append(toIndentedString(schemaVersion)).append("\n");
    sb.append("    documentType: ").append(toIndentedString(documentType)).append("\n");
    sb.append("    transactions: ").append(toIndentedString(transactions)).append("\n");
    sb.append("    documentDate: ").append(toIndentedString(documentDate)).append("\n");
    sb.append("    period: ").append(toIndentedString(period)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
