/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * BodyObtainAccessTokenTokenPost
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class BodyObtainAccessTokenTokenPost {
  /**
   * An enumeration.
   */
  public enum GrantTypeEnum {
    PASSWORD("password"),
    REFRESH_TOKEN("refresh_token");

    private String value;

    GrantTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static GrantTypeEnum fromValue(String input) {
      for (GrantTypeEnum b : GrantTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("grant_type")
  private GrantTypeEnum grantType = GrantTypeEnum.PASSWORD;

  @JsonProperty("username")
  private String username = null;

  @JsonProperty("password")
  private String password = null;

  @JsonProperty("refresh_token")
  private String refreshToken = null;

  @JsonProperty("scope")
  private String scope = "capturing_read capturing_write";

  public BodyObtainAccessTokenTokenPost grantType(GrantTypeEnum grantType) {
    this.grantType = grantType;
    return this;
  }

   /**
   * An enumeration.
   * @return grantType
  **/
  public GrantTypeEnum getGrantType() {
    return grantType;
  }

  public void setGrantType(GrantTypeEnum grantType) {
    this.grantType = grantType;
  }

  public BodyObtainAccessTokenTokenPost username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Required if the grant type is &#x60;password&#x60;.
   * @return username
  **/
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public BodyObtainAccessTokenTokenPost password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Required if the grant type is &#x60;password&#x60;.
   * @return password
  **/
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public BodyObtainAccessTokenTokenPost refreshToken(String refreshToken) {
    this.refreshToken = refreshToken;
    return this;
  }

   /**
   * Required if the grant type is &#x60;refresh_token&#x60;. The value is a valid refresh token previously returned by this endpoint.
   * @return refreshToken
  **/
  public String getRefreshToken() {
    return refreshToken;
  }

  public void setRefreshToken(String refreshToken) {
    this.refreshToken = refreshToken;
  }

  public BodyObtainAccessTokenTokenPost scope(String scope) {
    this.scope = scope;
    return this;
  }

   /**
   * Required if the grant type is &#x60;password&#x60;. A whitespace separated list of scopes that the returned token should have access to. Scopes are a mechanism to limit access to your user&#x27;s account and resources.  Available scopes: &#x60;capturing_write&#x60;, &#x60;capturing_read&#x60;, &#x60;postprocessing&#x60;, &#x60;user_management&#x60;, &#x60;client_management&#x60; (the OpenID Connect scopes &#x60;email&#x60; and &#x60;profile&#x60; will always be claimed)
   * @return scope
  **/
  public String getScope() {
    return scope;
  }

  public void setScope(String scope) {
    this.scope = scope;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BodyObtainAccessTokenTokenPost bodyObtainAccessTokenTokenPost = (BodyObtainAccessTokenTokenPost) o;
    return Objects.equals(this.grantType, bodyObtainAccessTokenTokenPost.grantType) &&
        Objects.equals(this.username, bodyObtainAccessTokenTokenPost.username) &&
        Objects.equals(this.password, bodyObtainAccessTokenTokenPost.password) &&
        Objects.equals(this.refreshToken, bodyObtainAccessTokenTokenPost.refreshToken) &&
        Objects.equals(this.scope, bodyObtainAccessTokenTokenPost.scope);
  }

  @Override
  public int hashCode() {
    return Objects.hash(grantType, username, password, refreshToken, scope);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BodyObtainAccessTokenTokenPost {\n");
    
    sb.append("    grantType: ").append(toIndentedString(grantType)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    refreshToken: ").append(toIndentedString(refreshToken)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
