/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.CurrencyExtraction1;
import com.axonivy.connector.idp.connector.model.FloatExtraction1;
import com.axonivy.connector.idp.connector.model.StringExtraction1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CommitmentInterest1
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class CommitmentInterest1 {
  @JsonProperty("start_date")
  private StringExtraction1 startDate = null;

  @JsonProperty("percentage")
  private FloatExtraction1 percentage = null;

  @JsonProperty("currency")
  private CurrencyExtraction1 currency = null;

  @JsonProperty("payment_method")
  private StringExtraction1 paymentMethod = null;

  public CommitmentInterest1 startDate(StringExtraction1 startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  public StringExtraction1 getStartDate() {
    return startDate;
  }

  public void setStartDate(StringExtraction1 startDate) {
    this.startDate = startDate;
  }

  public CommitmentInterest1 percentage(FloatExtraction1 percentage) {
    this.percentage = percentage;
    return this;
  }

   /**
   * Get percentage
   * @return percentage
  **/
  public FloatExtraction1 getPercentage() {
    return percentage;
  }

  public void setPercentage(FloatExtraction1 percentage) {
    this.percentage = percentage;
  }

  public CommitmentInterest1 currency(CurrencyExtraction1 currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  public CurrencyExtraction1 getCurrency() {
    return currency;
  }

  public void setCurrency(CurrencyExtraction1 currency) {
    this.currency = currency;
  }

  public CommitmentInterest1 paymentMethod(StringExtraction1 paymentMethod) {
    this.paymentMethod = paymentMethod;
    return this;
  }

   /**
   * Get paymentMethod
   * @return paymentMethod
  **/
  public StringExtraction1 getPaymentMethod() {
    return paymentMethod;
  }

  public void setPaymentMethod(StringExtraction1 paymentMethod) {
    this.paymentMethod = paymentMethod;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommitmentInterest1 commitmentInterest1 = (CommitmentInterest1) o;
    return Objects.equals(this.startDate, commitmentInterest1.startDate) &&
        Objects.equals(this.percentage, commitmentInterest1.percentage) &&
        Objects.equals(this.currency, commitmentInterest1.currency) &&
        Objects.equals(this.paymentMethod, commitmentInterest1.paymentMethod);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startDate, percentage, currency, paymentMethod);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommitmentInterest1 {\n");
    
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    percentage: ").append(toIndentedString(percentage)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
