/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.Name;
import com.axonivy.connector.idp.connector.model.StringExtraction2;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ContactPerson
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class ContactPerson {
  @JsonProperty("name")
  private Name name = null;

  @JsonProperty("phone")
  private StringExtraction2 phone = null;

  @JsonProperty("fax")
  private StringExtraction2 fax = null;

  @JsonProperty("e_mail")
  private StringExtraction2 eMail = null;

  public ContactPerson name(Name name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public Name getName() {
    return name;
  }

  public void setName(Name name) {
    this.name = name;
  }

  public ContactPerson phone(StringExtraction2 phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  public StringExtraction2 getPhone() {
    return phone;
  }

  public void setPhone(StringExtraction2 phone) {
    this.phone = phone;
  }

  public ContactPerson fax(StringExtraction2 fax) {
    this.fax = fax;
    return this;
  }

   /**
   * Get fax
   * @return fax
  **/
  public StringExtraction2 getFax() {
    return fax;
  }

  public void setFax(StringExtraction2 fax) {
    this.fax = fax;
  }

  public ContactPerson eMail(StringExtraction2 eMail) {
    this.eMail = eMail;
    return this;
  }

   /**
   * Get eMail
   * @return eMail
  **/
  public StringExtraction2 getEMail() {
    return eMail;
  }

  public void setEMail(StringExtraction2 eMail) {
    this.eMail = eMail;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContactPerson contactPerson = (ContactPerson) o;
    return Objects.equals(this.name, contactPerson.name) &&
        Objects.equals(this.phone, contactPerson.phone) &&
        Objects.equals(this.fax, contactPerson.fax) &&
        Objects.equals(this.eMail, contactPerson.eMail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, phone, fax, eMail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContactPerson {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    fax: ").append(toIndentedString(fax)).append("\n");
    sb.append("    eMail: ").append(toIndentedString(eMail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
