/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.General1;
import com.axonivy.connector.idp.connector.model.Hoist1;
import com.axonivy.connector.idp.connector.model.Jib1;
import com.axonivy.connector.idp.connector.model.Kbk1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Crane
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class Crane {
  /**
   * Gets or Sets schemaVersion
   */
  public enum SchemaVersionEnum {
    NUMBER_1(1);

    private Integer value;

    SchemaVersionEnum(Integer value) {
      this.value = value;
    }
    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SchemaVersionEnum fromValue(Integer input) {
      for (SchemaVersionEnum b : SchemaVersionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("schema_version")
  private SchemaVersionEnum schemaVersion = SchemaVersionEnum.NUMBER_1;

  /**
   * Gets or Sets documentType
   */
  public enum DocumentTypeEnum {
    CRANE("crane");

    private String value;

    DocumentTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static DocumentTypeEnum fromValue(String input) {
      for (DocumentTypeEnum b : DocumentTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("document_type")
  private DocumentTypeEnum documentType = null;

  @JsonProperty("general")
  private General1 general = null;

  @JsonProperty("hoist")
  private Hoist1 hoist = null;

  @JsonProperty("jib")
  private Jib1 jib = null;

  @JsonProperty("kbk")
  private Kbk1 kbk = null;

  public Crane schemaVersion(SchemaVersionEnum schemaVersion) {
    this.schemaVersion = schemaVersion;
    return this;
  }

   /**
   * Get schemaVersion
   * @return schemaVersion
  **/
  public SchemaVersionEnum getSchemaVersion() {
    return schemaVersion;
  }

  public void setSchemaVersion(SchemaVersionEnum schemaVersion) {
    this.schemaVersion = schemaVersion;
  }

  public Crane documentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
    return this;
  }

   /**
   * Get documentType
   * @return documentType
  **/
  public DocumentTypeEnum getDocumentType() {
    return documentType;
  }

  public void setDocumentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
  }

  public Crane general(General1 general) {
    this.general = general;
    return this;
  }

   /**
   * Get general
   * @return general
  **/
  public General1 getGeneral() {
    return general;
  }

  public void setGeneral(General1 general) {
    this.general = general;
  }

  public Crane hoist(Hoist1 hoist) {
    this.hoist = hoist;
    return this;
  }

   /**
   * Get hoist
   * @return hoist
  **/
  public Hoist1 getHoist() {
    return hoist;
  }

  public void setHoist(Hoist1 hoist) {
    this.hoist = hoist;
  }

  public Crane jib(Jib1 jib) {
    this.jib = jib;
    return this;
  }

   /**
   * Get jib
   * @return jib
  **/
  public Jib1 getJib() {
    return jib;
  }

  public void setJib(Jib1 jib) {
    this.jib = jib;
  }

  public Crane kbk(Kbk1 kbk) {
    this.kbk = kbk;
    return this;
  }

   /**
   * Get kbk
   * @return kbk
  **/
  public Kbk1 getKbk() {
    return kbk;
  }

  public void setKbk(Kbk1 kbk) {
    this.kbk = kbk;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Crane crane = (Crane) o;
    return Objects.equals(this.schemaVersion, crane.schemaVersion) &&
        Objects.equals(this.documentType, crane.documentType) &&
        Objects.equals(this.general, crane.general) &&
        Objects.equals(this.hoist, crane.hoist) &&
        Objects.equals(this.jib, crane.jib) &&
        Objects.equals(this.kbk, crane.kbk);
  }

  @Override
  public int hashCode() {
    return Objects.hash(schemaVersion, documentType, general, hoist, jib, kbk);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Crane {\n");
    
    sb.append("    schemaVersion: ").append(toIndentedString(schemaVersion)).append("\n");
    sb.append("    documentType: ").append(toIndentedString(documentType)).append("\n");
    sb.append("    general: ").append(toIndentedString(general)).append("\n");
    sb.append("    hoist: ").append(toIndentedString(hoist)).append("\n");
    sb.append("    jib: ").append(toIndentedString(jib)).append("\n");
    sb.append("    kbk: ").append(toIndentedString(kbk)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
