/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.OrganizationalInfo1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreateCustomerForm1
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class CreateCustomerForm1 {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("organizational_info")
  private OrganizationalInfo1 organizationalInfo = null;

  @JsonProperty("use_technical_interface")
  private Boolean useTechnicalInterface = null;

  public CreateCustomerForm1 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CreateCustomerForm1 organizationalInfo(OrganizationalInfo1 organizationalInfo) {
    this.organizationalInfo = organizationalInfo;
    return this;
  }

   /**
   * Get organizationalInfo
   * @return organizationalInfo
  **/
  public OrganizationalInfo1 getOrganizationalInfo() {
    return organizationalInfo;
  }

  public void setOrganizationalInfo(OrganizationalInfo1 organizationalInfo) {
    this.organizationalInfo = organizationalInfo;
  }

  public CreateCustomerForm1 useTechnicalInterface(Boolean useTechnicalInterface) {
    this.useTechnicalInterface = useTechnicalInterface;
    return this;
  }

   /**
   * Determines which web interface will be displayed after login at https://platform.natif.ai for all users within this customer. - &#x60;false&#x60;: the new Api-Hub interface - &#x60;true&#x60;: the previous, more technical interface
   * @return useTechnicalInterface
  **/
  public Boolean isUseTechnicalInterface() {
    return useTechnicalInterface;
  }

  public void setUseTechnicalInterface(Boolean useTechnicalInterface) {
    this.useTechnicalInterface = useTechnicalInterface;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateCustomerForm1 createCustomerForm1 = (CreateCustomerForm1) o;
    return Objects.equals(this.name, createCustomerForm1.name) &&
        Objects.equals(this.organizationalInfo, createCustomerForm1.organizationalInfo) &&
        Objects.equals(this.useTechnicalInterface, createCustomerForm1.useTechnicalInterface);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, organizationalInfo, useTechnicalInterface);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateCustomerForm1 {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    organizationalInfo: ").append(toIndentedString(organizationalInfo)).append("\n");
    sb.append("    useTechnicalInterface: ").append(toIndentedString(useTechnicalInterface)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
