/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.Address1AddressLine1;
import com.axonivy.connector.idp.connector.model.Address1AddressLine2;
import com.axonivy.connector.idp.connector.model.Address1City;
import com.axonivy.connector.idp.connector.model.Address1Zip;
import com.axonivy.connector.idp.connector.model.CountryExtraction1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Customer13Address
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class Customer13Address {
  @JsonProperty("address_line_1")
  private Address1AddressLine1 addressLine1 = null;

  @JsonProperty("address_line_2")
  private Address1AddressLine2 addressLine2 = null;

  @JsonProperty("city")
  private Address1City city = null;

  @JsonProperty("zip")
  private Address1Zip zip = null;

  @JsonProperty("country")
  private CountryExtraction1 country = null;

  public Customer13Address addressLine1(Address1AddressLine1 addressLine1) {
    this.addressLine1 = addressLine1;
    return this;
  }

   /**
   * Get addressLine1
   * @return addressLine1
  **/
  public Address1AddressLine1 getAddressLine1() {
    return addressLine1;
  }

  public void setAddressLine1(Address1AddressLine1 addressLine1) {
    this.addressLine1 = addressLine1;
  }

  public Customer13Address addressLine2(Address1AddressLine2 addressLine2) {
    this.addressLine2 = addressLine2;
    return this;
  }

   /**
   * Get addressLine2
   * @return addressLine2
  **/
  public Address1AddressLine2 getAddressLine2() {
    return addressLine2;
  }

  public void setAddressLine2(Address1AddressLine2 addressLine2) {
    this.addressLine2 = addressLine2;
  }

  public Customer13Address city(Address1City city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  public Address1City getCity() {
    return city;
  }

  public void setCity(Address1City city) {
    this.city = city;
  }

  public Customer13Address zip(Address1Zip zip) {
    this.zip = zip;
    return this;
  }

   /**
   * Get zip
   * @return zip
  **/
  public Address1Zip getZip() {
    return zip;
  }

  public void setZip(Address1Zip zip) {
    this.zip = zip;
  }

  public Customer13Address country(CountryExtraction1 country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  public CountryExtraction1 getCountry() {
    return country;
  }

  public void setCountry(CountryExtraction1 country) {
    this.country = country;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Customer13Address customer13Address = (Customer13Address) o;
    return Objects.equals(this.addressLine1, customer13Address.addressLine1) &&
        Objects.equals(this.addressLine2, customer13Address.addressLine2) &&
        Objects.equals(this.city, customer13Address.city) &&
        Objects.equals(this.zip, customer13Address.zip) &&
        Objects.equals(this.country, customer13Address.country);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressLine1, addressLine2, city, zip, country);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Customer13Address {\n");
    
    sb.append("    addressLine1: ").append(toIndentedString(addressLine1)).append("\n");
    sb.append("    addressLine2: ").append(toIndentedString(addressLine2)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    zip: ").append(toIndentedString(zip)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
