/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.DateExtraction1;
import com.axonivy.connector.idp.connector.model.FloatExtraction1;
import com.axonivy.connector.idp.connector.model.StringExtraction1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration {
  /**
   * Gets or Sets schemaVersion
   */
  public enum SchemaVersionEnum {
    NUMBER_1(1);

    private Integer value;

    SchemaVersionEnum(Integer value) {
      this.value = value;
    }
    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SchemaVersionEnum fromValue(Integer input) {
      for (SchemaVersionEnum b : SchemaVersionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("schema_version")
  private SchemaVersionEnum schemaVersion = SchemaVersionEnum.NUMBER_1;

  /**
   * Gets or Sets documentType
   */
  public enum DocumentTypeEnum {
    VEHICLE_REGISTRATION("vehicle_registration");

    private String value;

    DocumentTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static DocumentTypeEnum fromValue(String input) {
      for (DocumentTypeEnum b : DocumentTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("document_type")
  private DocumentTypeEnum documentType = null;

  @JsonProperty("fahrzeugschein_nr")
  private StringExtraction1 fahrzeugscheinNr = null;

  @JsonProperty("a_amtliches_kennzeichen")
  private StringExtraction1 aAmtlichesKennzeichen = null;

  @JsonProperty("c_1_1_name_des_halters")
  private StringExtraction1 c11NameDesHalters = null;

  @JsonProperty("c_1__2_vorname")
  private StringExtraction1 c12Vorname = null;

  @JsonProperty("c_1_3_anschrift")
  private StringExtraction1 c13Anschrift = null;

  @JsonProperty("x_naechste_hu")
  private StringExtraction1 xNaechsteHu = null;

  @JsonProperty("i_ausstellungsdatum")
  private DateExtraction1 iAusstellungsdatum = null;

  @JsonProperty("austellungsort")
  private StringExtraction1 austellungsort = null;

  @JsonProperty("b_datum_erstzulassung")
  private DateExtraction1 bDatumErstzulassung = null;

  @JsonProperty("n_2_1_HSN")
  private StringExtraction1 n21HSN = null;

  @JsonProperty("n_2_2_TSN")
  private StringExtraction1 n22TSN = null;

  @JsonProperty("j_fahrzeugklasse")
  private StringExtraction1 jFahrzeugklasse = null;

  @JsonProperty("n_4_art_des_aufbaus")
  private StringExtraction1 n4ArtDesAufbaus = null;

  @JsonProperty("e_fahrgestellnummer")
  private StringExtraction1 eFahrgestellnummer = null;

  @JsonProperty("n_3_pruefziffer_fgn")
  private StringExtraction1 n3PruefzifferFgn = null;

  @JsonProperty("d_1_fahrzeugmarke")
  private StringExtraction1 d1Fahrzeugmarke = null;

  @JsonProperty("d_2_typ_variante_version")
  private StringExtraction1 d2TypVarianteVersion = null;

  @JsonProperty("d_3_handelsbezeichnung")
  private StringExtraction1 d3Handelsbezeichnung = null;

  @JsonProperty("n_2_herst_kurzbez")
  private StringExtraction1 n2HerstKurzbez = null;

  @JsonProperty("n_5_fahrzeugklasse")
  private StringExtraction1 n5Fahrzeugklasse = null;

  @JsonProperty("v_9_schadstoffklasse")
  private StringExtraction1 v9Schadstoffklasse = null;

  @JsonProperty("n_14_emissionsklasse")
  private StringExtraction1 n14Emissionsklasse = null;

  @JsonProperty("p_3_kraftstoffart")
  private StringExtraction1 p3Kraftstoffart = null;

  @JsonProperty("n_10_code_zu_p_3")
  private StringExtraction1 n10CodeZuP3 = null;

  @JsonProperty("n_14_1_code_zu_v_9_o_14")
  private StringExtraction1 n141CodeZuV9O14 = null;

  @JsonProperty("p_1_hubraum")
  private StringExtraction1 p1Hubraum = null;

  @JsonProperty("n_22_bemerkungen")
  private StringExtraction1 n22Bemerkungen = null;

  @JsonProperty("l_anzahl_achsen")
  private FloatExtraction1 lAnzahlAchsen = null;

  @JsonProperty("n_9_anzahl_antriebsachsen")
  private StringExtraction1 n9AnzahlAntriebsachsen = null;

  @JsonProperty("p_2_p_4_nennl")
  private StringExtraction1 p2P4Nennl = null;

  @JsonProperty("t_hoechstgeschw")
  private FloatExtraction1 tHoechstgeschw = null;

  @JsonProperty("n_18_laenge_in_mm")
  private FloatExtraction1 n18LaengeInMm = null;

  @JsonProperty("n_19_breite_in_mm")
  private FloatExtraction1 n19BreiteInMm = null;

  @JsonProperty("n_20_hoehe_in_mm")
  private FloatExtraction1 n20HoeheInMm = null;

  @JsonProperty("g_leermasse")
  private FloatExtraction1 gLeermasse = null;

  @JsonProperty("n_12_rauminhalt_tank")
  private FloatExtraction1 n12RauminhaltTank = null;

  @JsonProperty("n_13_stuetzlast")
  private FloatExtraction1 n13Stuetzlast = null;

  @JsonProperty("q_leistungsgewicht")
  private FloatExtraction1 qLeistungsgewicht = null;

  @JsonProperty("v_7_co2")
  private FloatExtraction1 v7Co2 = null;

  @JsonProperty("f_1_gesamtmasse")
  private FloatExtraction1 f1Gesamtmasse = null;

  @JsonProperty("f_2_gesamtmasse")
  private FloatExtraction1 f2Gesamtmasse = null;

  @JsonProperty("n_7_1_achslast_a_1")
  private FloatExtraction1 n71AchslastA1 = null;

  @JsonProperty("n_7_2_achslast_a_2")
  private FloatExtraction1 n72AchslastA2 = null;

  @JsonProperty("n_7_3_achslast_a_3")
  private FloatExtraction1 n73AchslastA3 = null;

  @JsonProperty("n_8_1_achslast_mgs_a_1")
  private FloatExtraction1 n81AchslastMgsA1 = null;

  @JsonProperty("n_8_2_achslast_mgs_a_2")
  private FloatExtraction1 n82AchslastMgsA2 = null;

  @JsonProperty("n_8_3_achslast_mgs_a_3")
  private FloatExtraction1 n83AchslastMgsA3 = null;

  @JsonProperty("u_1_standger")
  private FloatExtraction1 u1Standger = null;

  @JsonProperty("u_2_drehzahl")
  private FloatExtraction1 u2Drehzahl = null;

  @JsonProperty("u_3_fahrger")
  private StringExtraction1 u3Fahrger = null;

  @JsonProperty("o_1_anhaengelast_gebr")
  private FloatExtraction1 o1AnhaengelastGebr = null;

  @JsonProperty("o_2_anhaengelast_ungebr")
  private FloatExtraction1 o2AnhaengelastUngebr = null;

  @JsonProperty("s_1_sitzplaetze")
  private FloatExtraction1 s1Sitzplaetze = null;

  @JsonProperty("s_2_stehplaetze")
  private FloatExtraction1 s2Stehplaetze = null;

  @JsonProperty("n_15_1_bereifung_achse_1")
  private StringExtraction1 n151BereifungAchse1 = null;

  @JsonProperty("n_15_2_bereifung_achse_2")
  private StringExtraction1 n152BereifungAchse2 = null;

  @JsonProperty("n_15_3_bereifung_achse_3")
  private StringExtraction1 n153BereifungAchse3 = null;

  @JsonProperty("r_farbe")
  private StringExtraction1 rFarbe = null;

  @JsonProperty("n_11_code_zur_farbe")
  private StringExtraction1 n11CodeZurFarbe = null;

  @JsonProperty("k_betriebserlaubnis")
  private StringExtraction1 kBetriebserlaubnis = null;

  @JsonProperty("n_6_eg_typengenehmigung")
  private DateExtraction1 n6EgTypengenehmigung = null;

  @JsonProperty("n_17_merk_betriebserl")
  private StringExtraction1 n17MerkBetriebserl = null;

  @JsonProperty("n_16_nummer_zb_teil_2")
  private StringExtraction1 n16NummerZbTeil2 = null;

  @JsonProperty("n_21_vermerke")
  private StringExtraction1 n21Vermerke = null;

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration schemaVersion(SchemaVersionEnum schemaVersion) {
    this.schemaVersion = schemaVersion;
    return this;
  }

   /**
   * Get schemaVersion
   * @return schemaVersion
  **/
  public SchemaVersionEnum getSchemaVersion() {
    return schemaVersion;
  }

  public void setSchemaVersion(SchemaVersionEnum schemaVersion) {
    this.schemaVersion = schemaVersion;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration documentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
    return this;
  }

   /**
   * Get documentType
   * @return documentType
  **/
  public DocumentTypeEnum getDocumentType() {
    return documentType;
  }

  public void setDocumentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration fahrzeugscheinNr(StringExtraction1 fahrzeugscheinNr) {
    this.fahrzeugscheinNr = fahrzeugscheinNr;
    return this;
  }

   /**
   * Get fahrzeugscheinNr
   * @return fahrzeugscheinNr
  **/
  public StringExtraction1 getFahrzeugscheinNr() {
    return fahrzeugscheinNr;
  }

  public void setFahrzeugscheinNr(StringExtraction1 fahrzeugscheinNr) {
    this.fahrzeugscheinNr = fahrzeugscheinNr;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration aAmtlichesKennzeichen(StringExtraction1 aAmtlichesKennzeichen) {
    this.aAmtlichesKennzeichen = aAmtlichesKennzeichen;
    return this;
  }

   /**
   * Get aAmtlichesKennzeichen
   * @return aAmtlichesKennzeichen
  **/
  public StringExtraction1 getAAmtlichesKennzeichen() {
    return aAmtlichesKennzeichen;
  }

  public void setAAmtlichesKennzeichen(StringExtraction1 aAmtlichesKennzeichen) {
    this.aAmtlichesKennzeichen = aAmtlichesKennzeichen;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration c11NameDesHalters(StringExtraction1 c11NameDesHalters) {
    this.c11NameDesHalters = c11NameDesHalters;
    return this;
  }

   /**
   * Get c11NameDesHalters
   * @return c11NameDesHalters
  **/
  public StringExtraction1 getC11NameDesHalters() {
    return c11NameDesHalters;
  }

  public void setC11NameDesHalters(StringExtraction1 c11NameDesHalters) {
    this.c11NameDesHalters = c11NameDesHalters;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration c12Vorname(StringExtraction1 c12Vorname) {
    this.c12Vorname = c12Vorname;
    return this;
  }

   /**
   * Get c12Vorname
   * @return c12Vorname
  **/
  public StringExtraction1 getC12Vorname() {
    return c12Vorname;
  }

  public void setC12Vorname(StringExtraction1 c12Vorname) {
    this.c12Vorname = c12Vorname;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration c13Anschrift(StringExtraction1 c13Anschrift) {
    this.c13Anschrift = c13Anschrift;
    return this;
  }

   /**
   * Get c13Anschrift
   * @return c13Anschrift
  **/
  public StringExtraction1 getC13Anschrift() {
    return c13Anschrift;
  }

  public void setC13Anschrift(StringExtraction1 c13Anschrift) {
    this.c13Anschrift = c13Anschrift;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration xNaechsteHu(StringExtraction1 xNaechsteHu) {
    this.xNaechsteHu = xNaechsteHu;
    return this;
  }

   /**
   * Get xNaechsteHu
   * @return xNaechsteHu
  **/
  public StringExtraction1 getXNaechsteHu() {
    return xNaechsteHu;
  }

  public void setXNaechsteHu(StringExtraction1 xNaechsteHu) {
    this.xNaechsteHu = xNaechsteHu;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration iAusstellungsdatum(DateExtraction1 iAusstellungsdatum) {
    this.iAusstellungsdatum = iAusstellungsdatum;
    return this;
  }

   /**
   * Get iAusstellungsdatum
   * @return iAusstellungsdatum
  **/
  public DateExtraction1 getIAusstellungsdatum() {
    return iAusstellungsdatum;
  }

  public void setIAusstellungsdatum(DateExtraction1 iAusstellungsdatum) {
    this.iAusstellungsdatum = iAusstellungsdatum;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration austellungsort(StringExtraction1 austellungsort) {
    this.austellungsort = austellungsort;
    return this;
  }

   /**
   * Get austellungsort
   * @return austellungsort
  **/
  public StringExtraction1 getAustellungsort() {
    return austellungsort;
  }

  public void setAustellungsort(StringExtraction1 austellungsort) {
    this.austellungsort = austellungsort;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration bDatumErstzulassung(DateExtraction1 bDatumErstzulassung) {
    this.bDatumErstzulassung = bDatumErstzulassung;
    return this;
  }

   /**
   * Get bDatumErstzulassung
   * @return bDatumErstzulassung
  **/
  public DateExtraction1 getBDatumErstzulassung() {
    return bDatumErstzulassung;
  }

  public void setBDatumErstzulassung(DateExtraction1 bDatumErstzulassung) {
    this.bDatumErstzulassung = bDatumErstzulassung;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n21HSN(StringExtraction1 n21HSN) {
    this.n21HSN = n21HSN;
    return this;
  }

   /**
   * Get n21HSN
   * @return n21HSN
  **/
  public StringExtraction1 getN21HSN() {
    return n21HSN;
  }

  public void setN21HSN(StringExtraction1 n21HSN) {
    this.n21HSN = n21HSN;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n22TSN(StringExtraction1 n22TSN) {
    this.n22TSN = n22TSN;
    return this;
  }

   /**
   * Get n22TSN
   * @return n22TSN
  **/
  public StringExtraction1 getN22TSN() {
    return n22TSN;
  }

  public void setN22TSN(StringExtraction1 n22TSN) {
    this.n22TSN = n22TSN;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration jFahrzeugklasse(StringExtraction1 jFahrzeugklasse) {
    this.jFahrzeugklasse = jFahrzeugklasse;
    return this;
  }

   /**
   * Get jFahrzeugklasse
   * @return jFahrzeugklasse
  **/
  public StringExtraction1 getJFahrzeugklasse() {
    return jFahrzeugklasse;
  }

  public void setJFahrzeugklasse(StringExtraction1 jFahrzeugklasse) {
    this.jFahrzeugklasse = jFahrzeugklasse;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n4ArtDesAufbaus(StringExtraction1 n4ArtDesAufbaus) {
    this.n4ArtDesAufbaus = n4ArtDesAufbaus;
    return this;
  }

   /**
   * Get n4ArtDesAufbaus
   * @return n4ArtDesAufbaus
  **/
  public StringExtraction1 getN4ArtDesAufbaus() {
    return n4ArtDesAufbaus;
  }

  public void setN4ArtDesAufbaus(StringExtraction1 n4ArtDesAufbaus) {
    this.n4ArtDesAufbaus = n4ArtDesAufbaus;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration eFahrgestellnummer(StringExtraction1 eFahrgestellnummer) {
    this.eFahrgestellnummer = eFahrgestellnummer;
    return this;
  }

   /**
   * Get eFahrgestellnummer
   * @return eFahrgestellnummer
  **/
  public StringExtraction1 getEFahrgestellnummer() {
    return eFahrgestellnummer;
  }

  public void setEFahrgestellnummer(StringExtraction1 eFahrgestellnummer) {
    this.eFahrgestellnummer = eFahrgestellnummer;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n3PruefzifferFgn(StringExtraction1 n3PruefzifferFgn) {
    this.n3PruefzifferFgn = n3PruefzifferFgn;
    return this;
  }

   /**
   * Get n3PruefzifferFgn
   * @return n3PruefzifferFgn
  **/
  public StringExtraction1 getN3PruefzifferFgn() {
    return n3PruefzifferFgn;
  }

  public void setN3PruefzifferFgn(StringExtraction1 n3PruefzifferFgn) {
    this.n3PruefzifferFgn = n3PruefzifferFgn;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration d1Fahrzeugmarke(StringExtraction1 d1Fahrzeugmarke) {
    this.d1Fahrzeugmarke = d1Fahrzeugmarke;
    return this;
  }

   /**
   * Get d1Fahrzeugmarke
   * @return d1Fahrzeugmarke
  **/
  public StringExtraction1 getD1Fahrzeugmarke() {
    return d1Fahrzeugmarke;
  }

  public void setD1Fahrzeugmarke(StringExtraction1 d1Fahrzeugmarke) {
    this.d1Fahrzeugmarke = d1Fahrzeugmarke;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration d2TypVarianteVersion(StringExtraction1 d2TypVarianteVersion) {
    this.d2TypVarianteVersion = d2TypVarianteVersion;
    return this;
  }

   /**
   * Get d2TypVarianteVersion
   * @return d2TypVarianteVersion
  **/
  public StringExtraction1 getD2TypVarianteVersion() {
    return d2TypVarianteVersion;
  }

  public void setD2TypVarianteVersion(StringExtraction1 d2TypVarianteVersion) {
    this.d2TypVarianteVersion = d2TypVarianteVersion;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration d3Handelsbezeichnung(StringExtraction1 d3Handelsbezeichnung) {
    this.d3Handelsbezeichnung = d3Handelsbezeichnung;
    return this;
  }

   /**
   * Get d3Handelsbezeichnung
   * @return d3Handelsbezeichnung
  **/
  public StringExtraction1 getD3Handelsbezeichnung() {
    return d3Handelsbezeichnung;
  }

  public void setD3Handelsbezeichnung(StringExtraction1 d3Handelsbezeichnung) {
    this.d3Handelsbezeichnung = d3Handelsbezeichnung;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n2HerstKurzbez(StringExtraction1 n2HerstKurzbez) {
    this.n2HerstKurzbez = n2HerstKurzbez;
    return this;
  }

   /**
   * Get n2HerstKurzbez
   * @return n2HerstKurzbez
  **/
  public StringExtraction1 getN2HerstKurzbez() {
    return n2HerstKurzbez;
  }

  public void setN2HerstKurzbez(StringExtraction1 n2HerstKurzbez) {
    this.n2HerstKurzbez = n2HerstKurzbez;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n5Fahrzeugklasse(StringExtraction1 n5Fahrzeugklasse) {
    this.n5Fahrzeugklasse = n5Fahrzeugklasse;
    return this;
  }

   /**
   * Get n5Fahrzeugklasse
   * @return n5Fahrzeugklasse
  **/
  public StringExtraction1 getN5Fahrzeugklasse() {
    return n5Fahrzeugklasse;
  }

  public void setN5Fahrzeugklasse(StringExtraction1 n5Fahrzeugklasse) {
    this.n5Fahrzeugklasse = n5Fahrzeugklasse;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration v9Schadstoffklasse(StringExtraction1 v9Schadstoffklasse) {
    this.v9Schadstoffklasse = v9Schadstoffklasse;
    return this;
  }

   /**
   * Get v9Schadstoffklasse
   * @return v9Schadstoffklasse
  **/
  public StringExtraction1 getV9Schadstoffklasse() {
    return v9Schadstoffklasse;
  }

  public void setV9Schadstoffklasse(StringExtraction1 v9Schadstoffklasse) {
    this.v9Schadstoffklasse = v9Schadstoffklasse;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n14Emissionsklasse(StringExtraction1 n14Emissionsklasse) {
    this.n14Emissionsklasse = n14Emissionsklasse;
    return this;
  }

   /**
   * Get n14Emissionsklasse
   * @return n14Emissionsklasse
  **/
  public StringExtraction1 getN14Emissionsklasse() {
    return n14Emissionsklasse;
  }

  public void setN14Emissionsklasse(StringExtraction1 n14Emissionsklasse) {
    this.n14Emissionsklasse = n14Emissionsklasse;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration p3Kraftstoffart(StringExtraction1 p3Kraftstoffart) {
    this.p3Kraftstoffart = p3Kraftstoffart;
    return this;
  }

   /**
   * Get p3Kraftstoffart
   * @return p3Kraftstoffart
  **/
  public StringExtraction1 getP3Kraftstoffart() {
    return p3Kraftstoffart;
  }

  public void setP3Kraftstoffart(StringExtraction1 p3Kraftstoffart) {
    this.p3Kraftstoffart = p3Kraftstoffart;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n10CodeZuP3(StringExtraction1 n10CodeZuP3) {
    this.n10CodeZuP3 = n10CodeZuP3;
    return this;
  }

   /**
   * Get n10CodeZuP3
   * @return n10CodeZuP3
  **/
  public StringExtraction1 getN10CodeZuP3() {
    return n10CodeZuP3;
  }

  public void setN10CodeZuP3(StringExtraction1 n10CodeZuP3) {
    this.n10CodeZuP3 = n10CodeZuP3;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n141CodeZuV9O14(StringExtraction1 n141CodeZuV9O14) {
    this.n141CodeZuV9O14 = n141CodeZuV9O14;
    return this;
  }

   /**
   * Get n141CodeZuV9O14
   * @return n141CodeZuV9O14
  **/
  public StringExtraction1 getN141CodeZuV9O14() {
    return n141CodeZuV9O14;
  }

  public void setN141CodeZuV9O14(StringExtraction1 n141CodeZuV9O14) {
    this.n141CodeZuV9O14 = n141CodeZuV9O14;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration p1Hubraum(StringExtraction1 p1Hubraum) {
    this.p1Hubraum = p1Hubraum;
    return this;
  }

   /**
   * Get p1Hubraum
   * @return p1Hubraum
  **/
  public StringExtraction1 getP1Hubraum() {
    return p1Hubraum;
  }

  public void setP1Hubraum(StringExtraction1 p1Hubraum) {
    this.p1Hubraum = p1Hubraum;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n22Bemerkungen(StringExtraction1 n22Bemerkungen) {
    this.n22Bemerkungen = n22Bemerkungen;
    return this;
  }

   /**
   * Get n22Bemerkungen
   * @return n22Bemerkungen
  **/
  public StringExtraction1 getN22Bemerkungen() {
    return n22Bemerkungen;
  }

  public void setN22Bemerkungen(StringExtraction1 n22Bemerkungen) {
    this.n22Bemerkungen = n22Bemerkungen;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration lAnzahlAchsen(FloatExtraction1 lAnzahlAchsen) {
    this.lAnzahlAchsen = lAnzahlAchsen;
    return this;
  }

   /**
   * Get lAnzahlAchsen
   * @return lAnzahlAchsen
  **/
  public FloatExtraction1 getLAnzahlAchsen() {
    return lAnzahlAchsen;
  }

  public void setLAnzahlAchsen(FloatExtraction1 lAnzahlAchsen) {
    this.lAnzahlAchsen = lAnzahlAchsen;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n9AnzahlAntriebsachsen(StringExtraction1 n9AnzahlAntriebsachsen) {
    this.n9AnzahlAntriebsachsen = n9AnzahlAntriebsachsen;
    return this;
  }

   /**
   * Get n9AnzahlAntriebsachsen
   * @return n9AnzahlAntriebsachsen
  **/
  public StringExtraction1 getN9AnzahlAntriebsachsen() {
    return n9AnzahlAntriebsachsen;
  }

  public void setN9AnzahlAntriebsachsen(StringExtraction1 n9AnzahlAntriebsachsen) {
    this.n9AnzahlAntriebsachsen = n9AnzahlAntriebsachsen;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration p2P4Nennl(StringExtraction1 p2P4Nennl) {
    this.p2P4Nennl = p2P4Nennl;
    return this;
  }

   /**
   * Get p2P4Nennl
   * @return p2P4Nennl
  **/
  public StringExtraction1 getP2P4Nennl() {
    return p2P4Nennl;
  }

  public void setP2P4Nennl(StringExtraction1 p2P4Nennl) {
    this.p2P4Nennl = p2P4Nennl;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration tHoechstgeschw(FloatExtraction1 tHoechstgeschw) {
    this.tHoechstgeschw = tHoechstgeschw;
    return this;
  }

   /**
   * Get tHoechstgeschw
   * @return tHoechstgeschw
  **/
  public FloatExtraction1 getTHoechstgeschw() {
    return tHoechstgeschw;
  }

  public void setTHoechstgeschw(FloatExtraction1 tHoechstgeschw) {
    this.tHoechstgeschw = tHoechstgeschw;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n18LaengeInMm(FloatExtraction1 n18LaengeInMm) {
    this.n18LaengeInMm = n18LaengeInMm;
    return this;
  }

   /**
   * Get n18LaengeInMm
   * @return n18LaengeInMm
  **/
  public FloatExtraction1 getN18LaengeInMm() {
    return n18LaengeInMm;
  }

  public void setN18LaengeInMm(FloatExtraction1 n18LaengeInMm) {
    this.n18LaengeInMm = n18LaengeInMm;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n19BreiteInMm(FloatExtraction1 n19BreiteInMm) {
    this.n19BreiteInMm = n19BreiteInMm;
    return this;
  }

   /**
   * Get n19BreiteInMm
   * @return n19BreiteInMm
  **/
  public FloatExtraction1 getN19BreiteInMm() {
    return n19BreiteInMm;
  }

  public void setN19BreiteInMm(FloatExtraction1 n19BreiteInMm) {
    this.n19BreiteInMm = n19BreiteInMm;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n20HoeheInMm(FloatExtraction1 n20HoeheInMm) {
    this.n20HoeheInMm = n20HoeheInMm;
    return this;
  }

   /**
   * Get n20HoeheInMm
   * @return n20HoeheInMm
  **/
  public FloatExtraction1 getN20HoeheInMm() {
    return n20HoeheInMm;
  }

  public void setN20HoeheInMm(FloatExtraction1 n20HoeheInMm) {
    this.n20HoeheInMm = n20HoeheInMm;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration gLeermasse(FloatExtraction1 gLeermasse) {
    this.gLeermasse = gLeermasse;
    return this;
  }

   /**
   * Get gLeermasse
   * @return gLeermasse
  **/
  public FloatExtraction1 getGLeermasse() {
    return gLeermasse;
  }

  public void setGLeermasse(FloatExtraction1 gLeermasse) {
    this.gLeermasse = gLeermasse;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n12RauminhaltTank(FloatExtraction1 n12RauminhaltTank) {
    this.n12RauminhaltTank = n12RauminhaltTank;
    return this;
  }

   /**
   * Get n12RauminhaltTank
   * @return n12RauminhaltTank
  **/
  public FloatExtraction1 getN12RauminhaltTank() {
    return n12RauminhaltTank;
  }

  public void setN12RauminhaltTank(FloatExtraction1 n12RauminhaltTank) {
    this.n12RauminhaltTank = n12RauminhaltTank;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n13Stuetzlast(FloatExtraction1 n13Stuetzlast) {
    this.n13Stuetzlast = n13Stuetzlast;
    return this;
  }

   /**
   * Get n13Stuetzlast
   * @return n13Stuetzlast
  **/
  public FloatExtraction1 getN13Stuetzlast() {
    return n13Stuetzlast;
  }

  public void setN13Stuetzlast(FloatExtraction1 n13Stuetzlast) {
    this.n13Stuetzlast = n13Stuetzlast;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration qLeistungsgewicht(FloatExtraction1 qLeistungsgewicht) {
    this.qLeistungsgewicht = qLeistungsgewicht;
    return this;
  }

   /**
   * Get qLeistungsgewicht
   * @return qLeistungsgewicht
  **/
  public FloatExtraction1 getQLeistungsgewicht() {
    return qLeistungsgewicht;
  }

  public void setQLeistungsgewicht(FloatExtraction1 qLeistungsgewicht) {
    this.qLeistungsgewicht = qLeistungsgewicht;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration v7Co2(FloatExtraction1 v7Co2) {
    this.v7Co2 = v7Co2;
    return this;
  }

   /**
   * Get v7Co2
   * @return v7Co2
  **/
  public FloatExtraction1 getV7Co2() {
    return v7Co2;
  }

  public void setV7Co2(FloatExtraction1 v7Co2) {
    this.v7Co2 = v7Co2;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration f1Gesamtmasse(FloatExtraction1 f1Gesamtmasse) {
    this.f1Gesamtmasse = f1Gesamtmasse;
    return this;
  }

   /**
   * Get f1Gesamtmasse
   * @return f1Gesamtmasse
  **/
  public FloatExtraction1 getF1Gesamtmasse() {
    return f1Gesamtmasse;
  }

  public void setF1Gesamtmasse(FloatExtraction1 f1Gesamtmasse) {
    this.f1Gesamtmasse = f1Gesamtmasse;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration f2Gesamtmasse(FloatExtraction1 f2Gesamtmasse) {
    this.f2Gesamtmasse = f2Gesamtmasse;
    return this;
  }

   /**
   * Get f2Gesamtmasse
   * @return f2Gesamtmasse
  **/
  public FloatExtraction1 getF2Gesamtmasse() {
    return f2Gesamtmasse;
  }

  public void setF2Gesamtmasse(FloatExtraction1 f2Gesamtmasse) {
    this.f2Gesamtmasse = f2Gesamtmasse;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n71AchslastA1(FloatExtraction1 n71AchslastA1) {
    this.n71AchslastA1 = n71AchslastA1;
    return this;
  }

   /**
   * Get n71AchslastA1
   * @return n71AchslastA1
  **/
  public FloatExtraction1 getN71AchslastA1() {
    return n71AchslastA1;
  }

  public void setN71AchslastA1(FloatExtraction1 n71AchslastA1) {
    this.n71AchslastA1 = n71AchslastA1;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n72AchslastA2(FloatExtraction1 n72AchslastA2) {
    this.n72AchslastA2 = n72AchslastA2;
    return this;
  }

   /**
   * Get n72AchslastA2
   * @return n72AchslastA2
  **/
  public FloatExtraction1 getN72AchslastA2() {
    return n72AchslastA2;
  }

  public void setN72AchslastA2(FloatExtraction1 n72AchslastA2) {
    this.n72AchslastA2 = n72AchslastA2;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n73AchslastA3(FloatExtraction1 n73AchslastA3) {
    this.n73AchslastA3 = n73AchslastA3;
    return this;
  }

   /**
   * Get n73AchslastA3
   * @return n73AchslastA3
  **/
  public FloatExtraction1 getN73AchslastA3() {
    return n73AchslastA3;
  }

  public void setN73AchslastA3(FloatExtraction1 n73AchslastA3) {
    this.n73AchslastA3 = n73AchslastA3;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n81AchslastMgsA1(FloatExtraction1 n81AchslastMgsA1) {
    this.n81AchslastMgsA1 = n81AchslastMgsA1;
    return this;
  }

   /**
   * Get n81AchslastMgsA1
   * @return n81AchslastMgsA1
  **/
  public FloatExtraction1 getN81AchslastMgsA1() {
    return n81AchslastMgsA1;
  }

  public void setN81AchslastMgsA1(FloatExtraction1 n81AchslastMgsA1) {
    this.n81AchslastMgsA1 = n81AchslastMgsA1;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n82AchslastMgsA2(FloatExtraction1 n82AchslastMgsA2) {
    this.n82AchslastMgsA2 = n82AchslastMgsA2;
    return this;
  }

   /**
   * Get n82AchslastMgsA2
   * @return n82AchslastMgsA2
  **/
  public FloatExtraction1 getN82AchslastMgsA2() {
    return n82AchslastMgsA2;
  }

  public void setN82AchslastMgsA2(FloatExtraction1 n82AchslastMgsA2) {
    this.n82AchslastMgsA2 = n82AchslastMgsA2;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n83AchslastMgsA3(FloatExtraction1 n83AchslastMgsA3) {
    this.n83AchslastMgsA3 = n83AchslastMgsA3;
    return this;
  }

   /**
   * Get n83AchslastMgsA3
   * @return n83AchslastMgsA3
  **/
  public FloatExtraction1 getN83AchslastMgsA3() {
    return n83AchslastMgsA3;
  }

  public void setN83AchslastMgsA3(FloatExtraction1 n83AchslastMgsA3) {
    this.n83AchslastMgsA3 = n83AchslastMgsA3;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration u1Standger(FloatExtraction1 u1Standger) {
    this.u1Standger = u1Standger;
    return this;
  }

   /**
   * Get u1Standger
   * @return u1Standger
  **/
  public FloatExtraction1 getU1Standger() {
    return u1Standger;
  }

  public void setU1Standger(FloatExtraction1 u1Standger) {
    this.u1Standger = u1Standger;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration u2Drehzahl(FloatExtraction1 u2Drehzahl) {
    this.u2Drehzahl = u2Drehzahl;
    return this;
  }

   /**
   * Get u2Drehzahl
   * @return u2Drehzahl
  **/
  public FloatExtraction1 getU2Drehzahl() {
    return u2Drehzahl;
  }

  public void setU2Drehzahl(FloatExtraction1 u2Drehzahl) {
    this.u2Drehzahl = u2Drehzahl;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration u3Fahrger(StringExtraction1 u3Fahrger) {
    this.u3Fahrger = u3Fahrger;
    return this;
  }

   /**
   * Get u3Fahrger
   * @return u3Fahrger
  **/
  public StringExtraction1 getU3Fahrger() {
    return u3Fahrger;
  }

  public void setU3Fahrger(StringExtraction1 u3Fahrger) {
    this.u3Fahrger = u3Fahrger;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration o1AnhaengelastGebr(FloatExtraction1 o1AnhaengelastGebr) {
    this.o1AnhaengelastGebr = o1AnhaengelastGebr;
    return this;
  }

   /**
   * Get o1AnhaengelastGebr
   * @return o1AnhaengelastGebr
  **/
  public FloatExtraction1 getO1AnhaengelastGebr() {
    return o1AnhaengelastGebr;
  }

  public void setO1AnhaengelastGebr(FloatExtraction1 o1AnhaengelastGebr) {
    this.o1AnhaengelastGebr = o1AnhaengelastGebr;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration o2AnhaengelastUngebr(FloatExtraction1 o2AnhaengelastUngebr) {
    this.o2AnhaengelastUngebr = o2AnhaengelastUngebr;
    return this;
  }

   /**
   * Get o2AnhaengelastUngebr
   * @return o2AnhaengelastUngebr
  **/
  public FloatExtraction1 getO2AnhaengelastUngebr() {
    return o2AnhaengelastUngebr;
  }

  public void setO2AnhaengelastUngebr(FloatExtraction1 o2AnhaengelastUngebr) {
    this.o2AnhaengelastUngebr = o2AnhaengelastUngebr;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration s1Sitzplaetze(FloatExtraction1 s1Sitzplaetze) {
    this.s1Sitzplaetze = s1Sitzplaetze;
    return this;
  }

   /**
   * Get s1Sitzplaetze
   * @return s1Sitzplaetze
  **/
  public FloatExtraction1 getS1Sitzplaetze() {
    return s1Sitzplaetze;
  }

  public void setS1Sitzplaetze(FloatExtraction1 s1Sitzplaetze) {
    this.s1Sitzplaetze = s1Sitzplaetze;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration s2Stehplaetze(FloatExtraction1 s2Stehplaetze) {
    this.s2Stehplaetze = s2Stehplaetze;
    return this;
  }

   /**
   * Get s2Stehplaetze
   * @return s2Stehplaetze
  **/
  public FloatExtraction1 getS2Stehplaetze() {
    return s2Stehplaetze;
  }

  public void setS2Stehplaetze(FloatExtraction1 s2Stehplaetze) {
    this.s2Stehplaetze = s2Stehplaetze;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n151BereifungAchse1(StringExtraction1 n151BereifungAchse1) {
    this.n151BereifungAchse1 = n151BereifungAchse1;
    return this;
  }

   /**
   * Get n151BereifungAchse1
   * @return n151BereifungAchse1
  **/
  public StringExtraction1 getN151BereifungAchse1() {
    return n151BereifungAchse1;
  }

  public void setN151BereifungAchse1(StringExtraction1 n151BereifungAchse1) {
    this.n151BereifungAchse1 = n151BereifungAchse1;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n152BereifungAchse2(StringExtraction1 n152BereifungAchse2) {
    this.n152BereifungAchse2 = n152BereifungAchse2;
    return this;
  }

   /**
   * Get n152BereifungAchse2
   * @return n152BereifungAchse2
  **/
  public StringExtraction1 getN152BereifungAchse2() {
    return n152BereifungAchse2;
  }

  public void setN152BereifungAchse2(StringExtraction1 n152BereifungAchse2) {
    this.n152BereifungAchse2 = n152BereifungAchse2;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n153BereifungAchse3(StringExtraction1 n153BereifungAchse3) {
    this.n153BereifungAchse3 = n153BereifungAchse3;
    return this;
  }

   /**
   * Get n153BereifungAchse3
   * @return n153BereifungAchse3
  **/
  public StringExtraction1 getN153BereifungAchse3() {
    return n153BereifungAchse3;
  }

  public void setN153BereifungAchse3(StringExtraction1 n153BereifungAchse3) {
    this.n153BereifungAchse3 = n153BereifungAchse3;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration rFarbe(StringExtraction1 rFarbe) {
    this.rFarbe = rFarbe;
    return this;
  }

   /**
   * Get rFarbe
   * @return rFarbe
  **/
  public StringExtraction1 getRFarbe() {
    return rFarbe;
  }

  public void setRFarbe(StringExtraction1 rFarbe) {
    this.rFarbe = rFarbe;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n11CodeZurFarbe(StringExtraction1 n11CodeZurFarbe) {
    this.n11CodeZurFarbe = n11CodeZurFarbe;
    return this;
  }

   /**
   * Get n11CodeZurFarbe
   * @return n11CodeZurFarbe
  **/
  public StringExtraction1 getN11CodeZurFarbe() {
    return n11CodeZurFarbe;
  }

  public void setN11CodeZurFarbe(StringExtraction1 n11CodeZurFarbe) {
    this.n11CodeZurFarbe = n11CodeZurFarbe;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration kBetriebserlaubnis(StringExtraction1 kBetriebserlaubnis) {
    this.kBetriebserlaubnis = kBetriebserlaubnis;
    return this;
  }

   /**
   * Get kBetriebserlaubnis
   * @return kBetriebserlaubnis
  **/
  public StringExtraction1 getKBetriebserlaubnis() {
    return kBetriebserlaubnis;
  }

  public void setKBetriebserlaubnis(StringExtraction1 kBetriebserlaubnis) {
    this.kBetriebserlaubnis = kBetriebserlaubnis;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n6EgTypengenehmigung(DateExtraction1 n6EgTypengenehmigung) {
    this.n6EgTypengenehmigung = n6EgTypengenehmigung;
    return this;
  }

   /**
   * Get n6EgTypengenehmigung
   * @return n6EgTypengenehmigung
  **/
  public DateExtraction1 getN6EgTypengenehmigung() {
    return n6EgTypengenehmigung;
  }

  public void setN6EgTypengenehmigung(DateExtraction1 n6EgTypengenehmigung) {
    this.n6EgTypengenehmigung = n6EgTypengenehmigung;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n17MerkBetriebserl(StringExtraction1 n17MerkBetriebserl) {
    this.n17MerkBetriebserl = n17MerkBetriebserl;
    return this;
  }

   /**
   * Get n17MerkBetriebserl
   * @return n17MerkBetriebserl
  **/
  public StringExtraction1 getN17MerkBetriebserl() {
    return n17MerkBetriebserl;
  }

  public void setN17MerkBetriebserl(StringExtraction1 n17MerkBetriebserl) {
    this.n17MerkBetriebserl = n17MerkBetriebserl;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n16NummerZbTeil2(StringExtraction1 n16NummerZbTeil2) {
    this.n16NummerZbTeil2 = n16NummerZbTeil2;
    return this;
  }

   /**
   * Get n16NummerZbTeil2
   * @return n16NummerZbTeil2
  **/
  public StringExtraction1 getN16NummerZbTeil2() {
    return n16NummerZbTeil2;
  }

  public void setN16NummerZbTeil2(StringExtraction1 n16NummerZbTeil2) {
    this.n16NummerZbTeil2 = n16NummerZbTeil2;
  }

  public DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration n21Vermerke(StringExtraction1 n21Vermerke) {
    this.n21Vermerke = n21Vermerke;
    return this;
  }

   /**
   * Get n21Vermerke
   * @return n21Vermerke
  **/
  public StringExtraction1 getN21Vermerke() {
    return n21Vermerke;
  }

  public void setN21Vermerke(StringExtraction1 n21Vermerke) {
    this.n21Vermerke = n21Vermerke;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration = (DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration) o;
    return Objects.equals(this.schemaVersion, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.schemaVersion) &&
        Objects.equals(this.documentType, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.documentType) &&
        Objects.equals(this.fahrzeugscheinNr, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.fahrzeugscheinNr) &&
        Objects.equals(this.aAmtlichesKennzeichen, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.aAmtlichesKennzeichen) &&
        Objects.equals(this.c11NameDesHalters, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.c11NameDesHalters) &&
        Objects.equals(this.c12Vorname, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.c12Vorname) &&
        Objects.equals(this.c13Anschrift, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.c13Anschrift) &&
        Objects.equals(this.xNaechsteHu, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.xNaechsteHu) &&
        Objects.equals(this.iAusstellungsdatum, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.iAusstellungsdatum) &&
        Objects.equals(this.austellungsort, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.austellungsort) &&
        Objects.equals(this.bDatumErstzulassung, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.bDatumErstzulassung) &&
        Objects.equals(this.n21HSN, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n21HSN) &&
        Objects.equals(this.n22TSN, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n22TSN) &&
        Objects.equals(this.jFahrzeugklasse, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.jFahrzeugklasse) &&
        Objects.equals(this.n4ArtDesAufbaus, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n4ArtDesAufbaus) &&
        Objects.equals(this.eFahrgestellnummer, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.eFahrgestellnummer) &&
        Objects.equals(this.n3PruefzifferFgn, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n3PruefzifferFgn) &&
        Objects.equals(this.d1Fahrzeugmarke, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.d1Fahrzeugmarke) &&
        Objects.equals(this.d2TypVarianteVersion, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.d2TypVarianteVersion) &&
        Objects.equals(this.d3Handelsbezeichnung, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.d3Handelsbezeichnung) &&
        Objects.equals(this.n2HerstKurzbez, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n2HerstKurzbez) &&
        Objects.equals(this.n5Fahrzeugklasse, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n5Fahrzeugklasse) &&
        Objects.equals(this.v9Schadstoffklasse, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.v9Schadstoffklasse) &&
        Objects.equals(this.n14Emissionsklasse, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n14Emissionsklasse) &&
        Objects.equals(this.p3Kraftstoffart, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.p3Kraftstoffart) &&
        Objects.equals(this.n10CodeZuP3, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n10CodeZuP3) &&
        Objects.equals(this.n141CodeZuV9O14, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n141CodeZuV9O14) &&
        Objects.equals(this.p1Hubraum, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.p1Hubraum) &&
        Objects.equals(this.n22Bemerkungen, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n22Bemerkungen) &&
        Objects.equals(this.lAnzahlAchsen, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.lAnzahlAchsen) &&
        Objects.equals(this.n9AnzahlAntriebsachsen, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n9AnzahlAntriebsachsen) &&
        Objects.equals(this.p2P4Nennl, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.p2P4Nennl) &&
        Objects.equals(this.tHoechstgeschw, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.tHoechstgeschw) &&
        Objects.equals(this.n18LaengeInMm, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n18LaengeInMm) &&
        Objects.equals(this.n19BreiteInMm, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n19BreiteInMm) &&
        Objects.equals(this.n20HoeheInMm, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n20HoeheInMm) &&
        Objects.equals(this.gLeermasse, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.gLeermasse) &&
        Objects.equals(this.n12RauminhaltTank, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n12RauminhaltTank) &&
        Objects.equals(this.n13Stuetzlast, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n13Stuetzlast) &&
        Objects.equals(this.qLeistungsgewicht, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.qLeistungsgewicht) &&
        Objects.equals(this.v7Co2, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.v7Co2) &&
        Objects.equals(this.f1Gesamtmasse, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.f1Gesamtmasse) &&
        Objects.equals(this.f2Gesamtmasse, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.f2Gesamtmasse) &&
        Objects.equals(this.n71AchslastA1, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n71AchslastA1) &&
        Objects.equals(this.n72AchslastA2, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n72AchslastA2) &&
        Objects.equals(this.n73AchslastA3, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n73AchslastA3) &&
        Objects.equals(this.n81AchslastMgsA1, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n81AchslastMgsA1) &&
        Objects.equals(this.n82AchslastMgsA2, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n82AchslastMgsA2) &&
        Objects.equals(this.n83AchslastMgsA3, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n83AchslastMgsA3) &&
        Objects.equals(this.u1Standger, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.u1Standger) &&
        Objects.equals(this.u2Drehzahl, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.u2Drehzahl) &&
        Objects.equals(this.u3Fahrger, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.u3Fahrger) &&
        Objects.equals(this.o1AnhaengelastGebr, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.o1AnhaengelastGebr) &&
        Objects.equals(this.o2AnhaengelastUngebr, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.o2AnhaengelastUngebr) &&
        Objects.equals(this.s1Sitzplaetze, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.s1Sitzplaetze) &&
        Objects.equals(this.s2Stehplaetze, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.s2Stehplaetze) &&
        Objects.equals(this.n151BereifungAchse1, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n151BereifungAchse1) &&
        Objects.equals(this.n152BereifungAchse2, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n152BereifungAchse2) &&
        Objects.equals(this.n153BereifungAchse3, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n153BereifungAchse3) &&
        Objects.equals(this.rFarbe, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.rFarbe) &&
        Objects.equals(this.n11CodeZurFarbe, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n11CodeZurFarbe) &&
        Objects.equals(this.kBetriebserlaubnis, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.kBetriebserlaubnis) &&
        Objects.equals(this.n6EgTypengenehmigung, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n6EgTypengenehmigung) &&
        Objects.equals(this.n17MerkBetriebserl, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n17MerkBetriebserl) &&
        Objects.equals(this.n16NummerZbTeil2, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n16NummerZbTeil2) &&
        Objects.equals(this.n21Vermerke, dataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration.n21Vermerke);
  }

  @Override
  public int hashCode() {
    return Objects.hash(schemaVersion, documentType, fahrzeugscheinNr, aAmtlichesKennzeichen, c11NameDesHalters, c12Vorname, c13Anschrift, xNaechsteHu, iAusstellungsdatum, austellungsort, bDatumErstzulassung, n21HSN, n22TSN, jFahrzeugklasse, n4ArtDesAufbaus, eFahrgestellnummer, n3PruefzifferFgn, d1Fahrzeugmarke, d2TypVarianteVersion, d3Handelsbezeichnung, n2HerstKurzbez, n5Fahrzeugklasse, v9Schadstoffklasse, n14Emissionsklasse, p3Kraftstoffart, n10CodeZuP3, n141CodeZuV9O14, p1Hubraum, n22Bemerkungen, lAnzahlAchsen, n9AnzahlAntriebsachsen, p2P4Nennl, tHoechstgeschw, n18LaengeInMm, n19BreiteInMm, n20HoeheInMm, gLeermasse, n12RauminhaltTank, n13Stuetzlast, qLeistungsgewicht, v7Co2, f1Gesamtmasse, f2Gesamtmasse, n71AchslastA1, n72AchslastA2, n73AchslastA3, n81AchslastMgsA1, n82AchslastMgsA2, n83AchslastMgsA3, u1Standger, u2Drehzahl, u3Fahrger, o1AnhaengelastGebr, o2AnhaengelastUngebr, s1Sitzplaetze, s2Stehplaetze, n151BereifungAchse1, n152BereifungAchse2, n153BereifungAchse3, rFarbe, n11CodeZurFarbe, kBetriebserlaubnis, n6EgTypengenehmigung, n17MerkBetriebserl, n16NummerZbTeil2, n21Vermerke);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataAccessSchemasVehicleRegistrationVehicleRegistrationV1VehicleRegistration {\n");
    
    sb.append("    schemaVersion: ").append(toIndentedString(schemaVersion)).append("\n");
    sb.append("    documentType: ").append(toIndentedString(documentType)).append("\n");
    sb.append("    fahrzeugscheinNr: ").append(toIndentedString(fahrzeugscheinNr)).append("\n");
    sb.append("    aAmtlichesKennzeichen: ").append(toIndentedString(aAmtlichesKennzeichen)).append("\n");
    sb.append("    c11NameDesHalters: ").append(toIndentedString(c11NameDesHalters)).append("\n");
    sb.append("    c12Vorname: ").append(toIndentedString(c12Vorname)).append("\n");
    sb.append("    c13Anschrift: ").append(toIndentedString(c13Anschrift)).append("\n");
    sb.append("    xNaechsteHu: ").append(toIndentedString(xNaechsteHu)).append("\n");
    sb.append("    iAusstellungsdatum: ").append(toIndentedString(iAusstellungsdatum)).append("\n");
    sb.append("    austellungsort: ").append(toIndentedString(austellungsort)).append("\n");
    sb.append("    bDatumErstzulassung: ").append(toIndentedString(bDatumErstzulassung)).append("\n");
    sb.append("    n21HSN: ").append(toIndentedString(n21HSN)).append("\n");
    sb.append("    n22TSN: ").append(toIndentedString(n22TSN)).append("\n");
    sb.append("    jFahrzeugklasse: ").append(toIndentedString(jFahrzeugklasse)).append("\n");
    sb.append("    n4ArtDesAufbaus: ").append(toIndentedString(n4ArtDesAufbaus)).append("\n");
    sb.append("    eFahrgestellnummer: ").append(toIndentedString(eFahrgestellnummer)).append("\n");
    sb.append("    n3PruefzifferFgn: ").append(toIndentedString(n3PruefzifferFgn)).append("\n");
    sb.append("    d1Fahrzeugmarke: ").append(toIndentedString(d1Fahrzeugmarke)).append("\n");
    sb.append("    d2TypVarianteVersion: ").append(toIndentedString(d2TypVarianteVersion)).append("\n");
    sb.append("    d3Handelsbezeichnung: ").append(toIndentedString(d3Handelsbezeichnung)).append("\n");
    sb.append("    n2HerstKurzbez: ").append(toIndentedString(n2HerstKurzbez)).append("\n");
    sb.append("    n5Fahrzeugklasse: ").append(toIndentedString(n5Fahrzeugklasse)).append("\n");
    sb.append("    v9Schadstoffklasse: ").append(toIndentedString(v9Schadstoffklasse)).append("\n");
    sb.append("    n14Emissionsklasse: ").append(toIndentedString(n14Emissionsklasse)).append("\n");
    sb.append("    p3Kraftstoffart: ").append(toIndentedString(p3Kraftstoffart)).append("\n");
    sb.append("    n10CodeZuP3: ").append(toIndentedString(n10CodeZuP3)).append("\n");
    sb.append("    n141CodeZuV9O14: ").append(toIndentedString(n141CodeZuV9O14)).append("\n");
    sb.append("    p1Hubraum: ").append(toIndentedString(p1Hubraum)).append("\n");
    sb.append("    n22Bemerkungen: ").append(toIndentedString(n22Bemerkungen)).append("\n");
    sb.append("    lAnzahlAchsen: ").append(toIndentedString(lAnzahlAchsen)).append("\n");
    sb.append("    n9AnzahlAntriebsachsen: ").append(toIndentedString(n9AnzahlAntriebsachsen)).append("\n");
    sb.append("    p2P4Nennl: ").append(toIndentedString(p2P4Nennl)).append("\n");
    sb.append("    tHoechstgeschw: ").append(toIndentedString(tHoechstgeschw)).append("\n");
    sb.append("    n18LaengeInMm: ").append(toIndentedString(n18LaengeInMm)).append("\n");
    sb.append("    n19BreiteInMm: ").append(toIndentedString(n19BreiteInMm)).append("\n");
    sb.append("    n20HoeheInMm: ").append(toIndentedString(n20HoeheInMm)).append("\n");
    sb.append("    gLeermasse: ").append(toIndentedString(gLeermasse)).append("\n");
    sb.append("    n12RauminhaltTank: ").append(toIndentedString(n12RauminhaltTank)).append("\n");
    sb.append("    n13Stuetzlast: ").append(toIndentedString(n13Stuetzlast)).append("\n");
    sb.append("    qLeistungsgewicht: ").append(toIndentedString(qLeistungsgewicht)).append("\n");
    sb.append("    v7Co2: ").append(toIndentedString(v7Co2)).append("\n");
    sb.append("    f1Gesamtmasse: ").append(toIndentedString(f1Gesamtmasse)).append("\n");
    sb.append("    f2Gesamtmasse: ").append(toIndentedString(f2Gesamtmasse)).append("\n");
    sb.append("    n71AchslastA1: ").append(toIndentedString(n71AchslastA1)).append("\n");
    sb.append("    n72AchslastA2: ").append(toIndentedString(n72AchslastA2)).append("\n");
    sb.append("    n73AchslastA3: ").append(toIndentedString(n73AchslastA3)).append("\n");
    sb.append("    n81AchslastMgsA1: ").append(toIndentedString(n81AchslastMgsA1)).append("\n");
    sb.append("    n82AchslastMgsA2: ").append(toIndentedString(n82AchslastMgsA2)).append("\n");
    sb.append("    n83AchslastMgsA3: ").append(toIndentedString(n83AchslastMgsA3)).append("\n");
    sb.append("    u1Standger: ").append(toIndentedString(u1Standger)).append("\n");
    sb.append("    u2Drehzahl: ").append(toIndentedString(u2Drehzahl)).append("\n");
    sb.append("    u3Fahrger: ").append(toIndentedString(u3Fahrger)).append("\n");
    sb.append("    o1AnhaengelastGebr: ").append(toIndentedString(o1AnhaengelastGebr)).append("\n");
    sb.append("    o2AnhaengelastUngebr: ").append(toIndentedString(o2AnhaengelastUngebr)).append("\n");
    sb.append("    s1Sitzplaetze: ").append(toIndentedString(s1Sitzplaetze)).append("\n");
    sb.append("    s2Stehplaetze: ").append(toIndentedString(s2Stehplaetze)).append("\n");
    sb.append("    n151BereifungAchse1: ").append(toIndentedString(n151BereifungAchse1)).append("\n");
    sb.append("    n152BereifungAchse2: ").append(toIndentedString(n152BereifungAchse2)).append("\n");
    sb.append("    n153BereifungAchse3: ").append(toIndentedString(n153BereifungAchse3)).append("\n");
    sb.append("    rFarbe: ").append(toIndentedString(rFarbe)).append("\n");
    sb.append("    n11CodeZurFarbe: ").append(toIndentedString(n11CodeZurFarbe)).append("\n");
    sb.append("    kBetriebserlaubnis: ").append(toIndentedString(kBetriebserlaubnis)).append("\n");
    sb.append("    n6EgTypengenehmigung: ").append(toIndentedString(n6EgTypengenehmigung)).append("\n");
    sb.append("    n17MerkBetriebserl: ").append(toIndentedString(n17MerkBetriebserl)).append("\n");
    sb.append("    n16NummerZbTeil2: ").append(toIndentedString(n16NummerZbTeil2)).append("\n");
    sb.append("    n21Vermerke: ").append(toIndentedString(n21Vermerke)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
