/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.Reference;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
/**
 * DataAccessSchemasConstantsBaseExtractionsBaseExtractionsV1CurrencyExtraction
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class DataAccessSchemasConstantsBaseExtractionsBaseExtractionsV1CurrencyExtraction {
  @JsonProperty("validation_problem")
  private Boolean validationProblem = false;

  @JsonProperty("note")
  private String note = "";

  @JsonProperty("confidence")
  private BigDecimal confidence = new BigDecimal(0.0);

  @JsonProperty("bbox_refs")
  private List<Reference> bboxRefs = null;

  @JsonProperty("value")
  private String value = null;

  public DataAccessSchemasConstantsBaseExtractionsBaseExtractionsV1CurrencyExtraction validationProblem(Boolean validationProblem) {
    this.validationProblem = validationProblem;
    return this;
  }

   /**
   * Get validationProblem
   * @return validationProblem
  **/
  public Boolean isValidationProblem() {
    return validationProblem;
  }

  public void setValidationProblem(Boolean validationProblem) {
    this.validationProblem = validationProblem;
  }

  public DataAccessSchemasConstantsBaseExtractionsBaseExtractionsV1CurrencyExtraction note(String note) {
    this.note = note;
    return this;
  }

   /**
   * Get note
   * @return note
  **/
  public String getNote() {
    return note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  public DataAccessSchemasConstantsBaseExtractionsBaseExtractionsV1CurrencyExtraction confidence(BigDecimal confidence) {
    this.confidence = confidence;
    return this;
  }

   /**
   * Get confidence
   * @return confidence
  **/
  public BigDecimal getConfidence() {
    return confidence;
  }

  public void setConfidence(BigDecimal confidence) {
    this.confidence = confidence;
  }

  public DataAccessSchemasConstantsBaseExtractionsBaseExtractionsV1CurrencyExtraction bboxRefs(List<Reference> bboxRefs) {
    this.bboxRefs = bboxRefs;
    return this;
  }

  public DataAccessSchemasConstantsBaseExtractionsBaseExtractionsV1CurrencyExtraction addBboxRefsItem(Reference bboxRefsItem) {
    if (this.bboxRefs == null) {
      this.bboxRefs = new ArrayList<>();
    }
    this.bboxRefs.add(bboxRefsItem);
    return this;
  }

   /**
   * Get bboxRefs
   * @return bboxRefs
  **/
  public List<Reference> getBboxRefs() {
    return bboxRefs;
  }

  public void setBboxRefs(List<Reference> bboxRefs) {
    this.bboxRefs = bboxRefs;
  }

  public DataAccessSchemasConstantsBaseExtractionsBaseExtractionsV1CurrencyExtraction value(String value) {
    this.value = value;
    return this;
  }

   /**
   * ISO 4217 alphabetic code of currency.
   * @return value
  **/
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataAccessSchemasConstantsBaseExtractionsBaseExtractionsV1CurrencyExtraction dataAccessSchemasConstantsBaseExtractionsBaseExtractionsV1CurrencyExtraction = (DataAccessSchemasConstantsBaseExtractionsBaseExtractionsV1CurrencyExtraction) o;
    return Objects.equals(this.validationProblem, dataAccessSchemasConstantsBaseExtractionsBaseExtractionsV1CurrencyExtraction.validationProblem) &&
        Objects.equals(this.note, dataAccessSchemasConstantsBaseExtractionsBaseExtractionsV1CurrencyExtraction.note) &&
        Objects.equals(this.confidence, dataAccessSchemasConstantsBaseExtractionsBaseExtractionsV1CurrencyExtraction.confidence) &&
        Objects.equals(this.bboxRefs, dataAccessSchemasConstantsBaseExtractionsBaseExtractionsV1CurrencyExtraction.bboxRefs) &&
        Objects.equals(this.value, dataAccessSchemasConstantsBaseExtractionsBaseExtractionsV1CurrencyExtraction.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(validationProblem, note, confidence, bboxRefs, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataAccessSchemasConstantsBaseExtractionsBaseExtractionsV1CurrencyExtraction {\n");
    
    sb.append("    validationProblem: ").append(toIndentedString(validationProblem)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("    bboxRefs: ").append(toIndentedString(bboxRefs)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
