/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.FloatExtraction1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * DataAccessSchemasSalaryStatementSalaryStatementV3MonthlyTotals
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class DataAccessSchemasSalaryStatementSalaryStatementV3MonthlyTotals {
  @JsonProperty("monthly_base_salary")
  private FloatExtraction1 monthlyBaseSalary = null;

  @JsonProperty("monthly_gross_total")
  private FloatExtraction1 monthlyGrossTotal = null;

  @JsonProperty("monthly_net_total")
  private FloatExtraction1 monthlyNetTotal = null;

  @JsonProperty("monthly_net_payout")
  private FloatExtraction1 monthlyNetPayout = null;

  @JsonProperty("monthly_health_insurance")
  private FloatExtraction1 monthlyHealthInsurance = null;

  public DataAccessSchemasSalaryStatementSalaryStatementV3MonthlyTotals monthlyBaseSalary(FloatExtraction1 monthlyBaseSalary) {
    this.monthlyBaseSalary = monthlyBaseSalary;
    return this;
  }

   /**
   * Get monthlyBaseSalary
   * @return monthlyBaseSalary
  **/
  public FloatExtraction1 getMonthlyBaseSalary() {
    return monthlyBaseSalary;
  }

  public void setMonthlyBaseSalary(FloatExtraction1 monthlyBaseSalary) {
    this.monthlyBaseSalary = monthlyBaseSalary;
  }

  public DataAccessSchemasSalaryStatementSalaryStatementV3MonthlyTotals monthlyGrossTotal(FloatExtraction1 monthlyGrossTotal) {
    this.monthlyGrossTotal = monthlyGrossTotal;
    return this;
  }

   /**
   * Get monthlyGrossTotal
   * @return monthlyGrossTotal
  **/
  public FloatExtraction1 getMonthlyGrossTotal() {
    return monthlyGrossTotal;
  }

  public void setMonthlyGrossTotal(FloatExtraction1 monthlyGrossTotal) {
    this.monthlyGrossTotal = monthlyGrossTotal;
  }

  public DataAccessSchemasSalaryStatementSalaryStatementV3MonthlyTotals monthlyNetTotal(FloatExtraction1 monthlyNetTotal) {
    this.monthlyNetTotal = monthlyNetTotal;
    return this;
  }

   /**
   * Get monthlyNetTotal
   * @return monthlyNetTotal
  **/
  public FloatExtraction1 getMonthlyNetTotal() {
    return monthlyNetTotal;
  }

  public void setMonthlyNetTotal(FloatExtraction1 monthlyNetTotal) {
    this.monthlyNetTotal = monthlyNetTotal;
  }

  public DataAccessSchemasSalaryStatementSalaryStatementV3MonthlyTotals monthlyNetPayout(FloatExtraction1 monthlyNetPayout) {
    this.monthlyNetPayout = monthlyNetPayout;
    return this;
  }

   /**
   * Get monthlyNetPayout
   * @return monthlyNetPayout
  **/
  public FloatExtraction1 getMonthlyNetPayout() {
    return monthlyNetPayout;
  }

  public void setMonthlyNetPayout(FloatExtraction1 monthlyNetPayout) {
    this.monthlyNetPayout = monthlyNetPayout;
  }

  public DataAccessSchemasSalaryStatementSalaryStatementV3MonthlyTotals monthlyHealthInsurance(FloatExtraction1 monthlyHealthInsurance) {
    this.monthlyHealthInsurance = monthlyHealthInsurance;
    return this;
  }

   /**
   * Get monthlyHealthInsurance
   * @return monthlyHealthInsurance
  **/
  public FloatExtraction1 getMonthlyHealthInsurance() {
    return monthlyHealthInsurance;
  }

  public void setMonthlyHealthInsurance(FloatExtraction1 monthlyHealthInsurance) {
    this.monthlyHealthInsurance = monthlyHealthInsurance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataAccessSchemasSalaryStatementSalaryStatementV3MonthlyTotals dataAccessSchemasSalaryStatementSalaryStatementV3MonthlyTotals = (DataAccessSchemasSalaryStatementSalaryStatementV3MonthlyTotals) o;
    return Objects.equals(this.monthlyBaseSalary, dataAccessSchemasSalaryStatementSalaryStatementV3MonthlyTotals.monthlyBaseSalary) &&
        Objects.equals(this.monthlyGrossTotal, dataAccessSchemasSalaryStatementSalaryStatementV3MonthlyTotals.monthlyGrossTotal) &&
        Objects.equals(this.monthlyNetTotal, dataAccessSchemasSalaryStatementSalaryStatementV3MonthlyTotals.monthlyNetTotal) &&
        Objects.equals(this.monthlyNetPayout, dataAccessSchemasSalaryStatementSalaryStatementV3MonthlyTotals.monthlyNetPayout) &&
        Objects.equals(this.monthlyHealthInsurance, dataAccessSchemasSalaryStatementSalaryStatementV3MonthlyTotals.monthlyHealthInsurance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(monthlyBaseSalary, monthlyGrossTotal, monthlyNetTotal, monthlyNetPayout, monthlyHealthInsurance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataAccessSchemasSalaryStatementSalaryStatementV3MonthlyTotals {\n");
    
    sb.append("    monthlyBaseSalary: ").append(toIndentedString(monthlyBaseSalary)).append("\n");
    sb.append("    monthlyGrossTotal: ").append(toIndentedString(monthlyGrossTotal)).append("\n");
    sb.append("    monthlyNetTotal: ").append(toIndentedString(monthlyNetTotal)).append("\n");
    sb.append("    monthlyNetPayout: ").append(toIndentedString(monthlyNetPayout)).append("\n");
    sb.append("    monthlyHealthInsurance: ").append(toIndentedString(monthlyHealthInsurance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
