/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.BankingInformation1;
import com.axonivy.connector.idp.connector.model.FloatExtraction1;
import com.axonivy.connector.idp.connector.model.StringExtraction1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * DataAccessSchemasLetterLetterV1PaymentInformation
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class DataAccessSchemasLetterLetterV1PaymentInformation {
  @JsonProperty("receiver")
  private StringExtraction1 receiver = null;

  @JsonProperty("banking_information")
  private List<BankingInformation1> bankingInformation = new ArrayList<>();

  @JsonProperty("reference")
  private StringExtraction1 reference = null;

  @JsonProperty("amount")
  private FloatExtraction1 amount = null;

  public DataAccessSchemasLetterLetterV1PaymentInformation receiver(StringExtraction1 receiver) {
    this.receiver = receiver;
    return this;
  }

   /**
   * Get receiver
   * @return receiver
  **/
  public StringExtraction1 getReceiver() {
    return receiver;
  }

  public void setReceiver(StringExtraction1 receiver) {
    this.receiver = receiver;
  }

  public DataAccessSchemasLetterLetterV1PaymentInformation bankingInformation(List<BankingInformation1> bankingInformation) {
    this.bankingInformation = bankingInformation;
    return this;
  }

  public DataAccessSchemasLetterLetterV1PaymentInformation addBankingInformationItem(BankingInformation1 bankingInformationItem) {
    this.bankingInformation.add(bankingInformationItem);
    return this;
  }

   /**
   * Get bankingInformation
   * @return bankingInformation
  **/
  public List<BankingInformation1> getBankingInformation() {
    return bankingInformation;
  }

  public void setBankingInformation(List<BankingInformation1> bankingInformation) {
    this.bankingInformation = bankingInformation;
  }

  public DataAccessSchemasLetterLetterV1PaymentInformation reference(StringExtraction1 reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  public StringExtraction1 getReference() {
    return reference;
  }

  public void setReference(StringExtraction1 reference) {
    this.reference = reference;
  }

  public DataAccessSchemasLetterLetterV1PaymentInformation amount(FloatExtraction1 amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  public FloatExtraction1 getAmount() {
    return amount;
  }

  public void setAmount(FloatExtraction1 amount) {
    this.amount = amount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataAccessSchemasLetterLetterV1PaymentInformation dataAccessSchemasLetterLetterV1PaymentInformation = (DataAccessSchemasLetterLetterV1PaymentInformation) o;
    return Objects.equals(this.receiver, dataAccessSchemasLetterLetterV1PaymentInformation.receiver) &&
        Objects.equals(this.bankingInformation, dataAccessSchemasLetterLetterV1PaymentInformation.bankingInformation) &&
        Objects.equals(this.reference, dataAccessSchemasLetterLetterV1PaymentInformation.reference) &&
        Objects.equals(this.amount, dataAccessSchemasLetterLetterV1PaymentInformation.amount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(receiver, bankingInformation, reference, amount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataAccessSchemasLetterLetterV1PaymentInformation {\n");
    
    sb.append("    receiver: ").append(toIndentedString(receiver)).append("\n");
    sb.append("    bankingInformation: ").append(toIndentedString(bankingInformation)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
