/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.FloatExtraction1;
import com.axonivy.connector.idp.connector.model.StringExtraction1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * DataAccessSchemasDeliveryNoteDeliveryNoteV1LineItem
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class DataAccessSchemasDeliveryNoteDeliveryNoteV1LineItem {
  @JsonProperty("pos_id")
  private StringExtraction1 posId = null;

  @JsonProperty("article_id")
  private StringExtraction1 articleId = null;

  @JsonProperty("description")
  private StringExtraction1 description = null;

  @JsonProperty("quantity_ordered")
  private FloatExtraction1 quantityOrdered = null;

  @JsonProperty("quantity_delivered")
  private FloatExtraction1 quantityDelivered = null;

  @JsonProperty("unit")
  private FloatExtraction1 unit = null;

  @JsonProperty("weight")
  private FloatExtraction1 weight = null;

  public DataAccessSchemasDeliveryNoteDeliveryNoteV1LineItem posId(StringExtraction1 posId) {
    this.posId = posId;
    return this;
  }

   /**
   * Get posId
   * @return posId
  **/
  public StringExtraction1 getPosId() {
    return posId;
  }

  public void setPosId(StringExtraction1 posId) {
    this.posId = posId;
  }

  public DataAccessSchemasDeliveryNoteDeliveryNoteV1LineItem articleId(StringExtraction1 articleId) {
    this.articleId = articleId;
    return this;
  }

   /**
   * Get articleId
   * @return articleId
  **/
  public StringExtraction1 getArticleId() {
    return articleId;
  }

  public void setArticleId(StringExtraction1 articleId) {
    this.articleId = articleId;
  }

  public DataAccessSchemasDeliveryNoteDeliveryNoteV1LineItem description(StringExtraction1 description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public StringExtraction1 getDescription() {
    return description;
  }

  public void setDescription(StringExtraction1 description) {
    this.description = description;
  }

  public DataAccessSchemasDeliveryNoteDeliveryNoteV1LineItem quantityOrdered(FloatExtraction1 quantityOrdered) {
    this.quantityOrdered = quantityOrdered;
    return this;
  }

   /**
   * Get quantityOrdered
   * @return quantityOrdered
  **/
  public FloatExtraction1 getQuantityOrdered() {
    return quantityOrdered;
  }

  public void setQuantityOrdered(FloatExtraction1 quantityOrdered) {
    this.quantityOrdered = quantityOrdered;
  }

  public DataAccessSchemasDeliveryNoteDeliveryNoteV1LineItem quantityDelivered(FloatExtraction1 quantityDelivered) {
    this.quantityDelivered = quantityDelivered;
    return this;
  }

   /**
   * Get quantityDelivered
   * @return quantityDelivered
  **/
  public FloatExtraction1 getQuantityDelivered() {
    return quantityDelivered;
  }

  public void setQuantityDelivered(FloatExtraction1 quantityDelivered) {
    this.quantityDelivered = quantityDelivered;
  }

  public DataAccessSchemasDeliveryNoteDeliveryNoteV1LineItem unit(FloatExtraction1 unit) {
    this.unit = unit;
    return this;
  }

   /**
   * Get unit
   * @return unit
  **/
  public FloatExtraction1 getUnit() {
    return unit;
  }

  public void setUnit(FloatExtraction1 unit) {
    this.unit = unit;
  }

  public DataAccessSchemasDeliveryNoteDeliveryNoteV1LineItem weight(FloatExtraction1 weight) {
    this.weight = weight;
    return this;
  }

   /**
   * Get weight
   * @return weight
  **/
  public FloatExtraction1 getWeight() {
    return weight;
  }

  public void setWeight(FloatExtraction1 weight) {
    this.weight = weight;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataAccessSchemasDeliveryNoteDeliveryNoteV1LineItem dataAccessSchemasDeliveryNoteDeliveryNoteV1LineItem = (DataAccessSchemasDeliveryNoteDeliveryNoteV1LineItem) o;
    return Objects.equals(this.posId, dataAccessSchemasDeliveryNoteDeliveryNoteV1LineItem.posId) &&
        Objects.equals(this.articleId, dataAccessSchemasDeliveryNoteDeliveryNoteV1LineItem.articleId) &&
        Objects.equals(this.description, dataAccessSchemasDeliveryNoteDeliveryNoteV1LineItem.description) &&
        Objects.equals(this.quantityOrdered, dataAccessSchemasDeliveryNoteDeliveryNoteV1LineItem.quantityOrdered) &&
        Objects.equals(this.quantityDelivered, dataAccessSchemasDeliveryNoteDeliveryNoteV1LineItem.quantityDelivered) &&
        Objects.equals(this.unit, dataAccessSchemasDeliveryNoteDeliveryNoteV1LineItem.unit) &&
        Objects.equals(this.weight, dataAccessSchemasDeliveryNoteDeliveryNoteV1LineItem.weight);
  }

  @Override
  public int hashCode() {
    return Objects.hash(posId, articleId, description, quantityOrdered, quantityDelivered, unit, weight);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataAccessSchemasDeliveryNoteDeliveryNoteV1LineItem {\n");
    
    sb.append("    posId: ").append(toIndentedString(posId)).append("\n");
    sb.append("    articleId: ").append(toIndentedString(articleId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    quantityOrdered: ").append(toIndentedString(quantityOrdered)).append("\n");
    sb.append("    quantityDelivered: ").append(toIndentedString(quantityDelivered)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
