/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.SalaryStatementSingle1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * DataAccessSchemasSalaryStatementSalaryStatementV3SalaryStatement
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class DataAccessSchemasSalaryStatementSalaryStatementV3SalaryStatement {
  /**
   * Gets or Sets schemaVersion
   */
  public enum SchemaVersionEnum {
    NUMBER_3(3);

    private Integer value;

    SchemaVersionEnum(Integer value) {
      this.value = value;
    }
    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SchemaVersionEnum fromValue(Integer input) {
      for (SchemaVersionEnum b : SchemaVersionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("schema_version")
  private SchemaVersionEnum schemaVersion = SchemaVersionEnum.NUMBER_3;

  /**
   * Gets or Sets documentType
   */
  public enum DocumentTypeEnum {
    SALARY_STATEMENT("salary_statement");

    private String value;

    DocumentTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static DocumentTypeEnum fromValue(String input) {
      for (DocumentTypeEnum b : DocumentTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("document_type")
  private DocumentTypeEnum documentType = null;

  @JsonProperty("documents")
  private List<SalaryStatementSingle1> documents = new ArrayList<>();

  public DataAccessSchemasSalaryStatementSalaryStatementV3SalaryStatement schemaVersion(SchemaVersionEnum schemaVersion) {
    this.schemaVersion = schemaVersion;
    return this;
  }

   /**
   * Get schemaVersion
   * @return schemaVersion
  **/
  public SchemaVersionEnum getSchemaVersion() {
    return schemaVersion;
  }

  public void setSchemaVersion(SchemaVersionEnum schemaVersion) {
    this.schemaVersion = schemaVersion;
  }

  public DataAccessSchemasSalaryStatementSalaryStatementV3SalaryStatement documentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
    return this;
  }

   /**
   * Get documentType
   * @return documentType
  **/
  public DocumentTypeEnum getDocumentType() {
    return documentType;
  }

  public void setDocumentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
  }

  public DataAccessSchemasSalaryStatementSalaryStatementV3SalaryStatement documents(List<SalaryStatementSingle1> documents) {
    this.documents = documents;
    return this;
  }

  public DataAccessSchemasSalaryStatementSalaryStatementV3SalaryStatement addDocumentsItem(SalaryStatementSingle1 documentsItem) {
    this.documents.add(documentsItem);
    return this;
  }

   /**
   * Get documents
   * @return documents
  **/
  public List<SalaryStatementSingle1> getDocuments() {
    return documents;
  }

  public void setDocuments(List<SalaryStatementSingle1> documents) {
    this.documents = documents;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataAccessSchemasSalaryStatementSalaryStatementV3SalaryStatement dataAccessSchemasSalaryStatementSalaryStatementV3SalaryStatement = (DataAccessSchemasSalaryStatementSalaryStatementV3SalaryStatement) o;
    return Objects.equals(this.schemaVersion, dataAccessSchemasSalaryStatementSalaryStatementV3SalaryStatement.schemaVersion) &&
        Objects.equals(this.documentType, dataAccessSchemasSalaryStatementSalaryStatementV3SalaryStatement.documentType) &&
        Objects.equals(this.documents, dataAccessSchemasSalaryStatementSalaryStatementV3SalaryStatement.documents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(schemaVersion, documentType, documents);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataAccessSchemasSalaryStatementSalaryStatementV3SalaryStatement {\n");
    
    sb.append("    schemaVersion: ").append(toIndentedString(schemaVersion)).append("\n");
    sb.append("    documentType: ").append(toIndentedString(documentType)).append("\n");
    sb.append("    documents: ").append(toIndentedString(documents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
