/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.Address1;
import com.axonivy.connector.idp.connector.model.BankingInformation1;
import com.axonivy.connector.idp.connector.model.StringExtraction1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * DataAccessSchemasInvoiceDmgInvoiceDmgV1Customer
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class DataAccessSchemasInvoiceDmgInvoiceDmgV1Customer {
  @JsonProperty("name")
  private StringExtraction1 name = null;

  @JsonProperty("address")
  private Address1 address = null;

  @JsonProperty("vat_id")
  private StringExtraction1 vatId = null;

  @JsonProperty("tax_number")
  private StringExtraction1 taxNumber = null;

  @JsonProperty("eori_number")
  private StringExtraction1 eoriNumber = null;

  @JsonProperty("customer_number")
  private StringExtraction1 customerNumber = null;

  @JsonProperty("banking_information")
  private List<BankingInformation1> bankingInformation = new ArrayList<>();

  public DataAccessSchemasInvoiceDmgInvoiceDmgV1Customer name(StringExtraction1 name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public StringExtraction1 getName() {
    return name;
  }

  public void setName(StringExtraction1 name) {
    this.name = name;
  }

  public DataAccessSchemasInvoiceDmgInvoiceDmgV1Customer address(Address1 address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  public Address1 getAddress() {
    return address;
  }

  public void setAddress(Address1 address) {
    this.address = address;
  }

  public DataAccessSchemasInvoiceDmgInvoiceDmgV1Customer vatId(StringExtraction1 vatId) {
    this.vatId = vatId;
    return this;
  }

   /**
   * Get vatId
   * @return vatId
  **/
  public StringExtraction1 getVatId() {
    return vatId;
  }

  public void setVatId(StringExtraction1 vatId) {
    this.vatId = vatId;
  }

  public DataAccessSchemasInvoiceDmgInvoiceDmgV1Customer taxNumber(StringExtraction1 taxNumber) {
    this.taxNumber = taxNumber;
    return this;
  }

   /**
   * Get taxNumber
   * @return taxNumber
  **/
  public StringExtraction1 getTaxNumber() {
    return taxNumber;
  }

  public void setTaxNumber(StringExtraction1 taxNumber) {
    this.taxNumber = taxNumber;
  }

  public DataAccessSchemasInvoiceDmgInvoiceDmgV1Customer eoriNumber(StringExtraction1 eoriNumber) {
    this.eoriNumber = eoriNumber;
    return this;
  }

   /**
   * Get eoriNumber
   * @return eoriNumber
  **/
  public StringExtraction1 getEoriNumber() {
    return eoriNumber;
  }

  public void setEoriNumber(StringExtraction1 eoriNumber) {
    this.eoriNumber = eoriNumber;
  }

  public DataAccessSchemasInvoiceDmgInvoiceDmgV1Customer customerNumber(StringExtraction1 customerNumber) {
    this.customerNumber = customerNumber;
    return this;
  }

   /**
   * Get customerNumber
   * @return customerNumber
  **/
  public StringExtraction1 getCustomerNumber() {
    return customerNumber;
  }

  public void setCustomerNumber(StringExtraction1 customerNumber) {
    this.customerNumber = customerNumber;
  }

  public DataAccessSchemasInvoiceDmgInvoiceDmgV1Customer bankingInformation(List<BankingInformation1> bankingInformation) {
    this.bankingInformation = bankingInformation;
    return this;
  }

  public DataAccessSchemasInvoiceDmgInvoiceDmgV1Customer addBankingInformationItem(BankingInformation1 bankingInformationItem) {
    this.bankingInformation.add(bankingInformationItem);
    return this;
  }

   /**
   * Get bankingInformation
   * @return bankingInformation
  **/
  public List<BankingInformation1> getBankingInformation() {
    return bankingInformation;
  }

  public void setBankingInformation(List<BankingInformation1> bankingInformation) {
    this.bankingInformation = bankingInformation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataAccessSchemasInvoiceDmgInvoiceDmgV1Customer dataAccessSchemasInvoiceDmgInvoiceDmgV1Customer = (DataAccessSchemasInvoiceDmgInvoiceDmgV1Customer) o;
    return Objects.equals(this.name, dataAccessSchemasInvoiceDmgInvoiceDmgV1Customer.name) &&
        Objects.equals(this.address, dataAccessSchemasInvoiceDmgInvoiceDmgV1Customer.address) &&
        Objects.equals(this.vatId, dataAccessSchemasInvoiceDmgInvoiceDmgV1Customer.vatId) &&
        Objects.equals(this.taxNumber, dataAccessSchemasInvoiceDmgInvoiceDmgV1Customer.taxNumber) &&
        Objects.equals(this.eoriNumber, dataAccessSchemasInvoiceDmgInvoiceDmgV1Customer.eoriNumber) &&
        Objects.equals(this.customerNumber, dataAccessSchemasInvoiceDmgInvoiceDmgV1Customer.customerNumber) &&
        Objects.equals(this.bankingInformation, dataAccessSchemasInvoiceDmgInvoiceDmgV1Customer.bankingInformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, address, vatId, taxNumber, eoriNumber, customerNumber, bankingInformation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataAccessSchemasInvoiceDmgInvoiceDmgV1Customer {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    vatId: ").append(toIndentedString(vatId)).append("\n");
    sb.append("    taxNumber: ").append(toIndentedString(taxNumber)).append("\n");
    sb.append("    eoriNumber: ").append(toIndentedString(eoriNumber)).append("\n");
    sb.append("    customerNumber: ").append(toIndentedString(customerNumber)).append("\n");
    sb.append("    bankingInformation: ").append(toIndentedString(bankingInformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
