/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.AddressOptions1;
import com.axonivy.connector.idp.connector.model.BankingInformation2;
import com.axonivy.connector.idp.connector.model.StringExtractionOptions1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * DataAccessSchemasPurchaseOrderPurchaseOrderV1BilledParty
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class DataAccessSchemasPurchaseOrderPurchaseOrderV1BilledParty {
  @JsonProperty("name")
  private StringExtractionOptions1 name = null;

  @JsonProperty("address")
  private AddressOptions1 address = null;

  @JsonProperty("vat_id")
  private StringExtractionOptions1 vatId = null;

  @JsonProperty("number")
  private StringExtractionOptions1 number = null;

  @JsonProperty("banking_information")
  private List<BankingInformation2> bankingInformation = new ArrayList<>();

  @JsonProperty("phone")
  private StringExtractionOptions1 phone = null;

  @JsonProperty("fax")
  private StringExtractionOptions1 fax = null;

  @JsonProperty("e_mail")
  private StringExtractionOptions1 eMail = null;

  public DataAccessSchemasPurchaseOrderPurchaseOrderV1BilledParty name(StringExtractionOptions1 name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public StringExtractionOptions1 getName() {
    return name;
  }

  public void setName(StringExtractionOptions1 name) {
    this.name = name;
  }

  public DataAccessSchemasPurchaseOrderPurchaseOrderV1BilledParty address(AddressOptions1 address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  public AddressOptions1 getAddress() {
    return address;
  }

  public void setAddress(AddressOptions1 address) {
    this.address = address;
  }

  public DataAccessSchemasPurchaseOrderPurchaseOrderV1BilledParty vatId(StringExtractionOptions1 vatId) {
    this.vatId = vatId;
    return this;
  }

   /**
   * Get vatId
   * @return vatId
  **/
  public StringExtractionOptions1 getVatId() {
    return vatId;
  }

  public void setVatId(StringExtractionOptions1 vatId) {
    this.vatId = vatId;
  }

  public DataAccessSchemasPurchaseOrderPurchaseOrderV1BilledParty number(StringExtractionOptions1 number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  public StringExtractionOptions1 getNumber() {
    return number;
  }

  public void setNumber(StringExtractionOptions1 number) {
    this.number = number;
  }

  public DataAccessSchemasPurchaseOrderPurchaseOrderV1BilledParty bankingInformation(List<BankingInformation2> bankingInformation) {
    this.bankingInformation = bankingInformation;
    return this;
  }

  public DataAccessSchemasPurchaseOrderPurchaseOrderV1BilledParty addBankingInformationItem(BankingInformation2 bankingInformationItem) {
    this.bankingInformation.add(bankingInformationItem);
    return this;
  }

   /**
   * Get bankingInformation
   * @return bankingInformation
  **/
  public List<BankingInformation2> getBankingInformation() {
    return bankingInformation;
  }

  public void setBankingInformation(List<BankingInformation2> bankingInformation) {
    this.bankingInformation = bankingInformation;
  }

  public DataAccessSchemasPurchaseOrderPurchaseOrderV1BilledParty phone(StringExtractionOptions1 phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  public StringExtractionOptions1 getPhone() {
    return phone;
  }

  public void setPhone(StringExtractionOptions1 phone) {
    this.phone = phone;
  }

  public DataAccessSchemasPurchaseOrderPurchaseOrderV1BilledParty fax(StringExtractionOptions1 fax) {
    this.fax = fax;
    return this;
  }

   /**
   * Get fax
   * @return fax
  **/
  public StringExtractionOptions1 getFax() {
    return fax;
  }

  public void setFax(StringExtractionOptions1 fax) {
    this.fax = fax;
  }

  public DataAccessSchemasPurchaseOrderPurchaseOrderV1BilledParty eMail(StringExtractionOptions1 eMail) {
    this.eMail = eMail;
    return this;
  }

   /**
   * Get eMail
   * @return eMail
  **/
  public StringExtractionOptions1 getEMail() {
    return eMail;
  }

  public void setEMail(StringExtractionOptions1 eMail) {
    this.eMail = eMail;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataAccessSchemasPurchaseOrderPurchaseOrderV1BilledParty dataAccessSchemasPurchaseOrderPurchaseOrderV1BilledParty = (DataAccessSchemasPurchaseOrderPurchaseOrderV1BilledParty) o;
    return Objects.equals(this.name, dataAccessSchemasPurchaseOrderPurchaseOrderV1BilledParty.name) &&
        Objects.equals(this.address, dataAccessSchemasPurchaseOrderPurchaseOrderV1BilledParty.address) &&
        Objects.equals(this.vatId, dataAccessSchemasPurchaseOrderPurchaseOrderV1BilledParty.vatId) &&
        Objects.equals(this.number, dataAccessSchemasPurchaseOrderPurchaseOrderV1BilledParty.number) &&
        Objects.equals(this.bankingInformation, dataAccessSchemasPurchaseOrderPurchaseOrderV1BilledParty.bankingInformation) &&
        Objects.equals(this.phone, dataAccessSchemasPurchaseOrderPurchaseOrderV1BilledParty.phone) &&
        Objects.equals(this.fax, dataAccessSchemasPurchaseOrderPurchaseOrderV1BilledParty.fax) &&
        Objects.equals(this.eMail, dataAccessSchemasPurchaseOrderPurchaseOrderV1BilledParty.eMail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, address, vatId, number, bankingInformation, phone, fax, eMail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataAccessSchemasPurchaseOrderPurchaseOrderV1BilledParty {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    vatId: ").append(toIndentedString(vatId)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    bankingInformation: ").append(toIndentedString(bankingInformation)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    fax: ").append(toIndentedString(fax)).append("\n");
    sb.append("    eMail: ").append(toIndentedString(eMail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
