/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.Address1;
import com.axonivy.connector.idp.connector.model.BankingInformation1;
import com.axonivy.connector.idp.connector.model.Name1;
import com.axonivy.connector.idp.connector.model.Registration1;
import com.axonivy.connector.idp.connector.model.StringExtraction1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * DataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class DataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor {
  @JsonProperty("name")
  private Name1 name = null;

  @JsonProperty("address")
  private Address1 address = null;

  @JsonProperty("vat_id")
  private StringExtraction1 vatId = null;

  @JsonProperty("tax_number")
  private StringExtraction1 taxNumber = null;

  @JsonProperty("eori_number")
  private StringExtraction1 eoriNumber = null;

  @JsonProperty("registration")
  private Registration1 registration = null;

  @JsonProperty("banking_information")
  private List<BankingInformation1> bankingInformation = new ArrayList<>();

  @JsonProperty("phone")
  private StringExtraction1 phone = null;

  @JsonProperty("mobile")
  private StringExtraction1 mobile = null;

  @JsonProperty("fax")
  private StringExtraction1 fax = null;

  @JsonProperty("url")
  private StringExtraction1 url = null;

  @JsonProperty("e_mail")
  private StringExtraction1 eMail = null;

  public DataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor name(Name1 name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public Name1 getName() {
    return name;
  }

  public void setName(Name1 name) {
    this.name = name;
  }

  public DataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor address(Address1 address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  public Address1 getAddress() {
    return address;
  }

  public void setAddress(Address1 address) {
    this.address = address;
  }

  public DataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor vatId(StringExtraction1 vatId) {
    this.vatId = vatId;
    return this;
  }

   /**
   * Get vatId
   * @return vatId
  **/
  public StringExtraction1 getVatId() {
    return vatId;
  }

  public void setVatId(StringExtraction1 vatId) {
    this.vatId = vatId;
  }

  public DataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor taxNumber(StringExtraction1 taxNumber) {
    this.taxNumber = taxNumber;
    return this;
  }

   /**
   * Get taxNumber
   * @return taxNumber
  **/
  public StringExtraction1 getTaxNumber() {
    return taxNumber;
  }

  public void setTaxNumber(StringExtraction1 taxNumber) {
    this.taxNumber = taxNumber;
  }

  public DataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor eoriNumber(StringExtraction1 eoriNumber) {
    this.eoriNumber = eoriNumber;
    return this;
  }

   /**
   * Get eoriNumber
   * @return eoriNumber
  **/
  public StringExtraction1 getEoriNumber() {
    return eoriNumber;
  }

  public void setEoriNumber(StringExtraction1 eoriNumber) {
    this.eoriNumber = eoriNumber;
  }

  public DataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor registration(Registration1 registration) {
    this.registration = registration;
    return this;
  }

   /**
   * Get registration
   * @return registration
  **/
  public Registration1 getRegistration() {
    return registration;
  }

  public void setRegistration(Registration1 registration) {
    this.registration = registration;
  }

  public DataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor bankingInformation(List<BankingInformation1> bankingInformation) {
    this.bankingInformation = bankingInformation;
    return this;
  }

  public DataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor addBankingInformationItem(BankingInformation1 bankingInformationItem) {
    this.bankingInformation.add(bankingInformationItem);
    return this;
  }

   /**
   * Get bankingInformation
   * @return bankingInformation
  **/
  public List<BankingInformation1> getBankingInformation() {
    return bankingInformation;
  }

  public void setBankingInformation(List<BankingInformation1> bankingInformation) {
    this.bankingInformation = bankingInformation;
  }

  public DataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor phone(StringExtraction1 phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  public StringExtraction1 getPhone() {
    return phone;
  }

  public void setPhone(StringExtraction1 phone) {
    this.phone = phone;
  }

  public DataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor mobile(StringExtraction1 mobile) {
    this.mobile = mobile;
    return this;
  }

   /**
   * Get mobile
   * @return mobile
  **/
  public StringExtraction1 getMobile() {
    return mobile;
  }

  public void setMobile(StringExtraction1 mobile) {
    this.mobile = mobile;
  }

  public DataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor fax(StringExtraction1 fax) {
    this.fax = fax;
    return this;
  }

   /**
   * Get fax
   * @return fax
  **/
  public StringExtraction1 getFax() {
    return fax;
  }

  public void setFax(StringExtraction1 fax) {
    this.fax = fax;
  }

  public DataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor url(StringExtraction1 url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public StringExtraction1 getUrl() {
    return url;
  }

  public void setUrl(StringExtraction1 url) {
    this.url = url;
  }

  public DataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor eMail(StringExtraction1 eMail) {
    this.eMail = eMail;
    return this;
  }

   /**
   * Get eMail
   * @return eMail
  **/
  public StringExtraction1 getEMail() {
    return eMail;
  }

  public void setEMail(StringExtraction1 eMail) {
    this.eMail = eMail;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor dataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor = (DataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor) o;
    return Objects.equals(this.name, dataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor.name) &&
        Objects.equals(this.address, dataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor.address) &&
        Objects.equals(this.vatId, dataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor.vatId) &&
        Objects.equals(this.taxNumber, dataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor.taxNumber) &&
        Objects.equals(this.eoriNumber, dataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor.eoriNumber) &&
        Objects.equals(this.registration, dataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor.registration) &&
        Objects.equals(this.bankingInformation, dataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor.bankingInformation) &&
        Objects.equals(this.phone, dataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor.phone) &&
        Objects.equals(this.mobile, dataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor.mobile) &&
        Objects.equals(this.fax, dataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor.fax) &&
        Objects.equals(this.url, dataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor.url) &&
        Objects.equals(this.eMail, dataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor.eMail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, address, vatId, taxNumber, eoriNumber, registration, bankingInformation, phone, mobile, fax, url, eMail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataAccessSchemasInvoiceNerGroupingsMigrationInvoiceNerGroupingsMigrationV1Vendor {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    vatId: ").append(toIndentedString(vatId)).append("\n");
    sb.append("    taxNumber: ").append(toIndentedString(taxNumber)).append("\n");
    sb.append("    eoriNumber: ").append(toIndentedString(eoriNumber)).append("\n");
    sb.append("    registration: ").append(toIndentedString(registration)).append("\n");
    sb.append("    bankingInformation: ").append(toIndentedString(bankingInformation)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    mobile: ").append(toIndentedString(mobile)).append("\n");
    sb.append("    fax: ").append(toIndentedString(fax)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    eMail: ").append(toIndentedString(eMail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
