/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.ExtendedLineItem1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * DataAccessSchemasEnforcementOrderEnforcementOrderV1Interest
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class DataAccessSchemasEnforcementOrderEnforcementOrderV1Interest {
  @JsonProperty("line_items")
  private List<ExtendedLineItem1> lineItems = new ArrayList<>();

  public DataAccessSchemasEnforcementOrderEnforcementOrderV1Interest lineItems(List<ExtendedLineItem1> lineItems) {
    this.lineItems = lineItems;
    return this;
  }

  public DataAccessSchemasEnforcementOrderEnforcementOrderV1Interest addLineItemsItem(ExtendedLineItem1 lineItemsItem) {
    this.lineItems.add(lineItemsItem);
    return this;
  }

   /**
   * Get lineItems
   * @return lineItems
  **/
  public List<ExtendedLineItem1> getLineItems() {
    return lineItems;
  }

  public void setLineItems(List<ExtendedLineItem1> lineItems) {
    this.lineItems = lineItems;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataAccessSchemasEnforcementOrderEnforcementOrderV1Interest dataAccessSchemasEnforcementOrderEnforcementOrderV1Interest = (DataAccessSchemasEnforcementOrderEnforcementOrderV1Interest) o;
    return Objects.equals(this.lineItems, dataAccessSchemasEnforcementOrderEnforcementOrderV1Interest.lineItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lineItems);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataAccessSchemasEnforcementOrderEnforcementOrderV1Interest {\n");
    
    sb.append("    lineItems: ").append(toIndentedString(lineItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
