/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.Address1;
import com.axonivy.connector.idp.connector.model.Name1CompanyName;
import com.axonivy.connector.idp.connector.model.Name1FirstName;
import com.axonivy.connector.idp.connector.model.Name1LastName;
import com.axonivy.connector.idp.connector.model.Name1Title;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * DataAccessSchemasCorrespondenceCorrespondenceV1Receiver
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class DataAccessSchemasCorrespondenceCorrespondenceV1Receiver {
  @JsonProperty("company_name")
  private Name1CompanyName companyName = null;

  @JsonProperty("title")
  private Name1Title title = null;

  @JsonProperty("first_name")
  private Name1FirstName firstName = null;

  @JsonProperty("last_name")
  private Name1LastName lastName = null;

  @JsonProperty("address")
  private Address1 address = null;

  public DataAccessSchemasCorrespondenceCorrespondenceV1Receiver companyName(Name1CompanyName companyName) {
    this.companyName = companyName;
    return this;
  }

   /**
   * Get companyName
   * @return companyName
  **/
  public Name1CompanyName getCompanyName() {
    return companyName;
  }

  public void setCompanyName(Name1CompanyName companyName) {
    this.companyName = companyName;
  }

  public DataAccessSchemasCorrespondenceCorrespondenceV1Receiver title(Name1Title title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  public Name1Title getTitle() {
    return title;
  }

  public void setTitle(Name1Title title) {
    this.title = title;
  }

  public DataAccessSchemasCorrespondenceCorrespondenceV1Receiver firstName(Name1FirstName firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  public Name1FirstName getFirstName() {
    return firstName;
  }

  public void setFirstName(Name1FirstName firstName) {
    this.firstName = firstName;
  }

  public DataAccessSchemasCorrespondenceCorrespondenceV1Receiver lastName(Name1LastName lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  public Name1LastName getLastName() {
    return lastName;
  }

  public void setLastName(Name1LastName lastName) {
    this.lastName = lastName;
  }

  public DataAccessSchemasCorrespondenceCorrespondenceV1Receiver address(Address1 address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  public Address1 getAddress() {
    return address;
  }

  public void setAddress(Address1 address) {
    this.address = address;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataAccessSchemasCorrespondenceCorrespondenceV1Receiver dataAccessSchemasCorrespondenceCorrespondenceV1Receiver = (DataAccessSchemasCorrespondenceCorrespondenceV1Receiver) o;
    return Objects.equals(this.companyName, dataAccessSchemasCorrespondenceCorrespondenceV1Receiver.companyName) &&
        Objects.equals(this.title, dataAccessSchemasCorrespondenceCorrespondenceV1Receiver.title) &&
        Objects.equals(this.firstName, dataAccessSchemasCorrespondenceCorrespondenceV1Receiver.firstName) &&
        Objects.equals(this.lastName, dataAccessSchemasCorrespondenceCorrespondenceV1Receiver.lastName) &&
        Objects.equals(this.address, dataAccessSchemasCorrespondenceCorrespondenceV1Receiver.address);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyName, title, firstName, lastName, address);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataAccessSchemasCorrespondenceCorrespondenceV1Receiver {\n");
    
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
