/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.DateExtraction1;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsDeliveryNoteNumber1;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsGrossAmount;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsLicensePlateNumber;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsOrderConfirmationNumber1;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsOrderNumber1;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsOriginOfGoods;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsShippingNumber;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsTotalQuantity;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsTotalWeight;
import com.axonivy.connector.idp.connector.model.LineItem10;
import com.axonivy.connector.idp.connector.model.Receiver1;
import com.axonivy.connector.idp.connector.model.Sender1;
import com.axonivy.connector.idp.connector.model.StringExtraction1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * DeliveryNoteConstruction
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class DeliveryNoteConstruction {
  /**
   * Gets or Sets schemaVersion
   */
  public enum SchemaVersionEnum {
    NUMBER_1(1);

    private Integer value;

    SchemaVersionEnum(Integer value) {
      this.value = value;
    }
    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SchemaVersionEnum fromValue(Integer input) {
      for (SchemaVersionEnum b : SchemaVersionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("schema_version")
  private SchemaVersionEnum schemaVersion = SchemaVersionEnum.NUMBER_1;

  /**
   * Gets or Sets documentType
   */
  public enum DocumentTypeEnum {
    DELIVERY_NOTE("delivery_note");

    private String value;

    DocumentTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static DocumentTypeEnum fromValue(String input) {
      for (DocumentTypeEnum b : DocumentTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("document_type")
  private DocumentTypeEnum documentType = null;

  @JsonProperty("receiver")
  private Receiver1 receiver = null;

  @JsonProperty("sender")
  private Sender1 sender = null;

  @JsonProperty("number")
  private DocumentsdocumentIdextractionsDeliveryNoteNumber1 number = null;

  @JsonProperty("order_number")
  private DocumentsdocumentIdextractionsOrderNumber1 orderNumber = null;

  @JsonProperty("order_confirmation_number")
  private DocumentsdocumentIdextractionsOrderConfirmationNumber1 orderConfirmationNumber = null;

  @JsonProperty("shipping_number")
  private DocumentsdocumentIdextractionsShippingNumber shippingNumber = null;

  @JsonProperty("date")
  private DateExtraction1 date = null;

  @JsonProperty("shipping_date")
  private DateExtraction1 shippingDate = null;

  @JsonProperty("delivery_date")
  private DateExtraction1 deliveryDate = null;

  @JsonProperty("total_weight")
  private DocumentsdocumentIdextractionsTotalWeight totalWeight = null;

  @JsonProperty("total_quantity")
  private DocumentsdocumentIdextractionsTotalQuantity totalQuantity = null;

  @JsonProperty("total_goods_value")
  private DocumentsdocumentIdextractionsGrossAmount totalGoodsValue = null;

  @JsonProperty("origin_of_goods")
  private DocumentsdocumentIdextractionsOriginOfGoods originOfGoods = null;

  @JsonProperty("goods")
  private List<LineItem10> goods = null;

  @JsonProperty("license_plate_number")
  private DocumentsdocumentIdextractionsLicensePlateNumber licensePlateNumber = null;

  @JsonProperty("construction_site_number")
  private StringExtraction1 constructionSiteNumber = null;

  @JsonProperty("construction_site_designation")
  private StringExtraction1 constructionSiteDesignation = null;

  public DeliveryNoteConstruction schemaVersion(SchemaVersionEnum schemaVersion) {
    this.schemaVersion = schemaVersion;
    return this;
  }

   /**
   * Get schemaVersion
   * @return schemaVersion
  **/
  public SchemaVersionEnum getSchemaVersion() {
    return schemaVersion;
  }

  public void setSchemaVersion(SchemaVersionEnum schemaVersion) {
    this.schemaVersion = schemaVersion;
  }

  public DeliveryNoteConstruction documentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
    return this;
  }

   /**
   * Get documentType
   * @return documentType
  **/
  public DocumentTypeEnum getDocumentType() {
    return documentType;
  }

  public void setDocumentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
  }

  public DeliveryNoteConstruction receiver(Receiver1 receiver) {
    this.receiver = receiver;
    return this;
  }

   /**
   * Get receiver
   * @return receiver
  **/
  public Receiver1 getReceiver() {
    return receiver;
  }

  public void setReceiver(Receiver1 receiver) {
    this.receiver = receiver;
  }

  public DeliveryNoteConstruction sender(Sender1 sender) {
    this.sender = sender;
    return this;
  }

   /**
   * Get sender
   * @return sender
  **/
  public Sender1 getSender() {
    return sender;
  }

  public void setSender(Sender1 sender) {
    this.sender = sender;
  }

  public DeliveryNoteConstruction number(DocumentsdocumentIdextractionsDeliveryNoteNumber1 number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  public DocumentsdocumentIdextractionsDeliveryNoteNumber1 getNumber() {
    return number;
  }

  public void setNumber(DocumentsdocumentIdextractionsDeliveryNoteNumber1 number) {
    this.number = number;
  }

  public DeliveryNoteConstruction orderNumber(DocumentsdocumentIdextractionsOrderNumber1 orderNumber) {
    this.orderNumber = orderNumber;
    return this;
  }

   /**
   * Get orderNumber
   * @return orderNumber
  **/
  public DocumentsdocumentIdextractionsOrderNumber1 getOrderNumber() {
    return orderNumber;
  }

  public void setOrderNumber(DocumentsdocumentIdextractionsOrderNumber1 orderNumber) {
    this.orderNumber = orderNumber;
  }

  public DeliveryNoteConstruction orderConfirmationNumber(DocumentsdocumentIdextractionsOrderConfirmationNumber1 orderConfirmationNumber) {
    this.orderConfirmationNumber = orderConfirmationNumber;
    return this;
  }

   /**
   * Get orderConfirmationNumber
   * @return orderConfirmationNumber
  **/
  public DocumentsdocumentIdextractionsOrderConfirmationNumber1 getOrderConfirmationNumber() {
    return orderConfirmationNumber;
  }

  public void setOrderConfirmationNumber(DocumentsdocumentIdextractionsOrderConfirmationNumber1 orderConfirmationNumber) {
    this.orderConfirmationNumber = orderConfirmationNumber;
  }

  public DeliveryNoteConstruction shippingNumber(DocumentsdocumentIdextractionsShippingNumber shippingNumber) {
    this.shippingNumber = shippingNumber;
    return this;
  }

   /**
   * Get shippingNumber
   * @return shippingNumber
  **/
  public DocumentsdocumentIdextractionsShippingNumber getShippingNumber() {
    return shippingNumber;
  }

  public void setShippingNumber(DocumentsdocumentIdextractionsShippingNumber shippingNumber) {
    this.shippingNumber = shippingNumber;
  }

  public DeliveryNoteConstruction date(DateExtraction1 date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  public DateExtraction1 getDate() {
    return date;
  }

  public void setDate(DateExtraction1 date) {
    this.date = date;
  }

  public DeliveryNoteConstruction shippingDate(DateExtraction1 shippingDate) {
    this.shippingDate = shippingDate;
    return this;
  }

   /**
   * Get shippingDate
   * @return shippingDate
  **/
  public DateExtraction1 getShippingDate() {
    return shippingDate;
  }

  public void setShippingDate(DateExtraction1 shippingDate) {
    this.shippingDate = shippingDate;
  }

  public DeliveryNoteConstruction deliveryDate(DateExtraction1 deliveryDate) {
    this.deliveryDate = deliveryDate;
    return this;
  }

   /**
   * Get deliveryDate
   * @return deliveryDate
  **/
  public DateExtraction1 getDeliveryDate() {
    return deliveryDate;
  }

  public void setDeliveryDate(DateExtraction1 deliveryDate) {
    this.deliveryDate = deliveryDate;
  }

  public DeliveryNoteConstruction totalWeight(DocumentsdocumentIdextractionsTotalWeight totalWeight) {
    this.totalWeight = totalWeight;
    return this;
  }

   /**
   * Get totalWeight
   * @return totalWeight
  **/
  public DocumentsdocumentIdextractionsTotalWeight getTotalWeight() {
    return totalWeight;
  }

  public void setTotalWeight(DocumentsdocumentIdextractionsTotalWeight totalWeight) {
    this.totalWeight = totalWeight;
  }

  public DeliveryNoteConstruction totalQuantity(DocumentsdocumentIdextractionsTotalQuantity totalQuantity) {
    this.totalQuantity = totalQuantity;
    return this;
  }

   /**
   * Get totalQuantity
   * @return totalQuantity
  **/
  public DocumentsdocumentIdextractionsTotalQuantity getTotalQuantity() {
    return totalQuantity;
  }

  public void setTotalQuantity(DocumentsdocumentIdextractionsTotalQuantity totalQuantity) {
    this.totalQuantity = totalQuantity;
  }

  public DeliveryNoteConstruction totalGoodsValue(DocumentsdocumentIdextractionsGrossAmount totalGoodsValue) {
    this.totalGoodsValue = totalGoodsValue;
    return this;
  }

   /**
   * Get totalGoodsValue
   * @return totalGoodsValue
  **/
  public DocumentsdocumentIdextractionsGrossAmount getTotalGoodsValue() {
    return totalGoodsValue;
  }

  public void setTotalGoodsValue(DocumentsdocumentIdextractionsGrossAmount totalGoodsValue) {
    this.totalGoodsValue = totalGoodsValue;
  }

  public DeliveryNoteConstruction originOfGoods(DocumentsdocumentIdextractionsOriginOfGoods originOfGoods) {
    this.originOfGoods = originOfGoods;
    return this;
  }

   /**
   * Get originOfGoods
   * @return originOfGoods
  **/
  public DocumentsdocumentIdextractionsOriginOfGoods getOriginOfGoods() {
    return originOfGoods;
  }

  public void setOriginOfGoods(DocumentsdocumentIdextractionsOriginOfGoods originOfGoods) {
    this.originOfGoods = originOfGoods;
  }

  public DeliveryNoteConstruction goods(List<LineItem10> goods) {
    this.goods = goods;
    return this;
  }

  public DeliveryNoteConstruction addGoodsItem(LineItem10 goodsItem) {
    if (this.goods == null) {
      this.goods = new ArrayList<>();
    }
    this.goods.add(goodsItem);
    return this;
  }

   /**
   * Get goods
   * @return goods
  **/
  public List<LineItem10> getGoods() {
    return goods;
  }

  public void setGoods(List<LineItem10> goods) {
    this.goods = goods;
  }

  public DeliveryNoteConstruction licensePlateNumber(DocumentsdocumentIdextractionsLicensePlateNumber licensePlateNumber) {
    this.licensePlateNumber = licensePlateNumber;
    return this;
  }

   /**
   * Get licensePlateNumber
   * @return licensePlateNumber
  **/
  public DocumentsdocumentIdextractionsLicensePlateNumber getLicensePlateNumber() {
    return licensePlateNumber;
  }

  public void setLicensePlateNumber(DocumentsdocumentIdextractionsLicensePlateNumber licensePlateNumber) {
    this.licensePlateNumber = licensePlateNumber;
  }

  public DeliveryNoteConstruction constructionSiteNumber(StringExtraction1 constructionSiteNumber) {
    this.constructionSiteNumber = constructionSiteNumber;
    return this;
  }

   /**
   * Get constructionSiteNumber
   * @return constructionSiteNumber
  **/
  public StringExtraction1 getConstructionSiteNumber() {
    return constructionSiteNumber;
  }

  public void setConstructionSiteNumber(StringExtraction1 constructionSiteNumber) {
    this.constructionSiteNumber = constructionSiteNumber;
  }

  public DeliveryNoteConstruction constructionSiteDesignation(StringExtraction1 constructionSiteDesignation) {
    this.constructionSiteDesignation = constructionSiteDesignation;
    return this;
  }

   /**
   * Get constructionSiteDesignation
   * @return constructionSiteDesignation
  **/
  public StringExtraction1 getConstructionSiteDesignation() {
    return constructionSiteDesignation;
  }

  public void setConstructionSiteDesignation(StringExtraction1 constructionSiteDesignation) {
    this.constructionSiteDesignation = constructionSiteDesignation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeliveryNoteConstruction deliveryNoteConstruction = (DeliveryNoteConstruction) o;
    return Objects.equals(this.schemaVersion, deliveryNoteConstruction.schemaVersion) &&
        Objects.equals(this.documentType, deliveryNoteConstruction.documentType) &&
        Objects.equals(this.receiver, deliveryNoteConstruction.receiver) &&
        Objects.equals(this.sender, deliveryNoteConstruction.sender) &&
        Objects.equals(this.number, deliveryNoteConstruction.number) &&
        Objects.equals(this.orderNumber, deliveryNoteConstruction.orderNumber) &&
        Objects.equals(this.orderConfirmationNumber, deliveryNoteConstruction.orderConfirmationNumber) &&
        Objects.equals(this.shippingNumber, deliveryNoteConstruction.shippingNumber) &&
        Objects.equals(this.date, deliveryNoteConstruction.date) &&
        Objects.equals(this.shippingDate, deliveryNoteConstruction.shippingDate) &&
        Objects.equals(this.deliveryDate, deliveryNoteConstruction.deliveryDate) &&
        Objects.equals(this.totalWeight, deliveryNoteConstruction.totalWeight) &&
        Objects.equals(this.totalQuantity, deliveryNoteConstruction.totalQuantity) &&
        Objects.equals(this.totalGoodsValue, deliveryNoteConstruction.totalGoodsValue) &&
        Objects.equals(this.originOfGoods, deliveryNoteConstruction.originOfGoods) &&
        Objects.equals(this.goods, deliveryNoteConstruction.goods) &&
        Objects.equals(this.licensePlateNumber, deliveryNoteConstruction.licensePlateNumber) &&
        Objects.equals(this.constructionSiteNumber, deliveryNoteConstruction.constructionSiteNumber) &&
        Objects.equals(this.constructionSiteDesignation, deliveryNoteConstruction.constructionSiteDesignation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(schemaVersion, documentType, receiver, sender, number, orderNumber, orderConfirmationNumber, shippingNumber, date, shippingDate, deliveryDate, totalWeight, totalQuantity, totalGoodsValue, originOfGoods, goods, licensePlateNumber, constructionSiteNumber, constructionSiteDesignation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeliveryNoteConstruction {\n");
    
    sb.append("    schemaVersion: ").append(toIndentedString(schemaVersion)).append("\n");
    sb.append("    documentType: ").append(toIndentedString(documentType)).append("\n");
    sb.append("    receiver: ").append(toIndentedString(receiver)).append("\n");
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    orderNumber: ").append(toIndentedString(orderNumber)).append("\n");
    sb.append("    orderConfirmationNumber: ").append(toIndentedString(orderConfirmationNumber)).append("\n");
    sb.append("    shippingNumber: ").append(toIndentedString(shippingNumber)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    shippingDate: ").append(toIndentedString(shippingDate)).append("\n");
    sb.append("    deliveryDate: ").append(toIndentedString(deliveryDate)).append("\n");
    sb.append("    totalWeight: ").append(toIndentedString(totalWeight)).append("\n");
    sb.append("    totalQuantity: ").append(toIndentedString(totalQuantity)).append("\n");
    sb.append("    totalGoodsValue: ").append(toIndentedString(totalGoodsValue)).append("\n");
    sb.append("    originOfGoods: ").append(toIndentedString(originOfGoods)).append("\n");
    sb.append("    goods: ").append(toIndentedString(goods)).append("\n");
    sb.append("    licensePlateNumber: ").append(toIndentedString(licensePlateNumber)).append("\n");
    sb.append("    constructionSiteNumber: ").append(toIndentedString(constructionSiteNumber)).append("\n");
    sb.append("    constructionSiteDesignation: ").append(toIndentedString(constructionSiteDesignation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
