/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.DateExtraction1;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsDiscountAmount;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsDiscountPercentage;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsNewAmount;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * EarlyPaymentBenefit1
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class EarlyPaymentBenefit1 {
  @JsonProperty("early_payment_date")
  private DateExtraction1 earlyPaymentDate = null;

  @JsonProperty("discount_percentage")
  private DocumentsdocumentIdextractionsDiscountPercentage discountPercentage = null;

  @JsonProperty("discount_amount")
  private DocumentsdocumentIdextractionsDiscountAmount discountAmount = null;

  @JsonProperty("new_amount")
  private DocumentsdocumentIdextractionsNewAmount newAmount = null;

  public EarlyPaymentBenefit1 earlyPaymentDate(DateExtraction1 earlyPaymentDate) {
    this.earlyPaymentDate = earlyPaymentDate;
    return this;
  }

   /**
   * Get earlyPaymentDate
   * @return earlyPaymentDate
  **/
  public DateExtraction1 getEarlyPaymentDate() {
    return earlyPaymentDate;
  }

  public void setEarlyPaymentDate(DateExtraction1 earlyPaymentDate) {
    this.earlyPaymentDate = earlyPaymentDate;
  }

  public EarlyPaymentBenefit1 discountPercentage(DocumentsdocumentIdextractionsDiscountPercentage discountPercentage) {
    this.discountPercentage = discountPercentage;
    return this;
  }

   /**
   * Get discountPercentage
   * @return discountPercentage
  **/
  public DocumentsdocumentIdextractionsDiscountPercentage getDiscountPercentage() {
    return discountPercentage;
  }

  public void setDiscountPercentage(DocumentsdocumentIdextractionsDiscountPercentage discountPercentage) {
    this.discountPercentage = discountPercentage;
  }

  public EarlyPaymentBenefit1 discountAmount(DocumentsdocumentIdextractionsDiscountAmount discountAmount) {
    this.discountAmount = discountAmount;
    return this;
  }

   /**
   * Get discountAmount
   * @return discountAmount
  **/
  public DocumentsdocumentIdextractionsDiscountAmount getDiscountAmount() {
    return discountAmount;
  }

  public void setDiscountAmount(DocumentsdocumentIdextractionsDiscountAmount discountAmount) {
    this.discountAmount = discountAmount;
  }

  public EarlyPaymentBenefit1 newAmount(DocumentsdocumentIdextractionsNewAmount newAmount) {
    this.newAmount = newAmount;
    return this;
  }

   /**
   * Get newAmount
   * @return newAmount
  **/
  public DocumentsdocumentIdextractionsNewAmount getNewAmount() {
    return newAmount;
  }

  public void setNewAmount(DocumentsdocumentIdextractionsNewAmount newAmount) {
    this.newAmount = newAmount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EarlyPaymentBenefit1 earlyPaymentBenefit1 = (EarlyPaymentBenefit1) o;
    return Objects.equals(this.earlyPaymentDate, earlyPaymentBenefit1.earlyPaymentDate) &&
        Objects.equals(this.discountPercentage, earlyPaymentBenefit1.discountPercentage) &&
        Objects.equals(this.discountAmount, earlyPaymentBenefit1.discountAmount) &&
        Objects.equals(this.newAmount, earlyPaymentBenefit1.newAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(earlyPaymentDate, discountPercentage, discountAmount, newAmount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EarlyPaymentBenefit1 {\n");
    
    sb.append("    earlyPaymentDate: ").append(toIndentedString(earlyPaymentDate)).append("\n");
    sb.append("    discountPercentage: ").append(toIndentedString(discountPercentage)).append("\n");
    sb.append("    discountAmount: ").append(toIndentedString(discountAmount)).append("\n");
    sb.append("    newAmount: ").append(toIndentedString(newAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
