/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.math.BigDecimal;
/**
 * ExtendedWorkflowUsage
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class ExtendedWorkflowUsage {
  /**
   * Gets or Sets which
   */
  public enum WhichEnum {
    EXTENDED("extended");

    private String value;

    WhichEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static WhichEnum fromValue(String input) {
      for (WhichEnum b : WhichEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("which")
  private WhichEnum which = WhichEnum.EXTENDED;

  @JsonProperty("date")
  private String date = null;

  @JsonProperty("processed_credits")
  private Integer processedCredits = 0;

  @JsonProperty("num_documents")
  private Integer numDocuments = 0;

  @JsonProperty("num_pages")
  private Integer numPages = 0;

  @JsonProperty("average_time_per_page")
  private BigDecimal averageTimePerPage = null;

  public ExtendedWorkflowUsage which(WhichEnum which) {
    this.which = which;
    return this;
  }

   /**
   * Get which
   * @return which
  **/
  public WhichEnum getWhich() {
    return which;
  }

  public void setWhich(WhichEnum which) {
    this.which = which;
  }

  public ExtendedWorkflowUsage date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Partial ISO-8601 datetime format: e.g. \&quot;YYYY-MM\&quot; or \&quot;YYYY-MM-DD\&quot; or \&quot;YYYY-MM-DDThhZ\&quot; or \&quot;YYYY-MM-DDThh:mmZ\&quot;, with an accuracy depending on the aggregation frequency.
   * @return date
  **/
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public ExtendedWorkflowUsage processedCredits(Integer processedCredits) {
    this.processedCredits = processedCredits;
    return this;
  }

   /**
   * Total credit cost for all successful workflow instances within the time window.
   * @return processedCredits
  **/
  public Integer getProcessedCredits() {
    return processedCredits;
  }

  public void setProcessedCredits(Integer processedCredits) {
    this.processedCredits = processedCredits;
  }

  public ExtendedWorkflowUsage numDocuments(Integer numDocuments) {
    this.numDocuments = numDocuments;
    return this;
  }

   /**
   * Total number of processed documents for all successful workflow instances within the time window.
   * @return numDocuments
  **/
  public Integer getNumDocuments() {
    return numDocuments;
  }

  public void setNumDocuments(Integer numDocuments) {
    this.numDocuments = numDocuments;
  }

  public ExtendedWorkflowUsage numPages(Integer numPages) {
    this.numPages = numPages;
    return this;
  }

   /**
   * Total number of processed pages for all successful workflow instances within the time window.
   * @return numPages
  **/
  public Integer getNumPages() {
    return numPages;
  }

  public void setNumPages(Integer numPages) {
    this.numPages = numPages;
  }

  public ExtendedWorkflowUsage averageTimePerPage(BigDecimal averageTimePerPage) {
    this.averageTimePerPage = averageTimePerPage;
    return this;
  }

   /**
   * Average processing time (submit until finish) per page.
   * @return averageTimePerPage
  **/
  public BigDecimal getAverageTimePerPage() {
    return averageTimePerPage;
  }

  public void setAverageTimePerPage(BigDecimal averageTimePerPage) {
    this.averageTimePerPage = averageTimePerPage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtendedWorkflowUsage extendedWorkflowUsage = (ExtendedWorkflowUsage) o;
    return Objects.equals(this.which, extendedWorkflowUsage.which) &&
        Objects.equals(this.date, extendedWorkflowUsage.date) &&
        Objects.equals(this.processedCredits, extendedWorkflowUsage.processedCredits) &&
        Objects.equals(this.numDocuments, extendedWorkflowUsage.numDocuments) &&
        Objects.equals(this.numPages, extendedWorkflowUsage.numPages) &&
        Objects.equals(this.averageTimePerPage, extendedWorkflowUsage.averageTimePerPage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(which, date, processedCredits, numDocuments, numPages, averageTimePerPage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtendedWorkflowUsage {\n");
    
    sb.append("    which: ").append(toIndentedString(which)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    processedCredits: ").append(toIndentedString(processedCredits)).append("\n");
    sb.append("    numDocuments: ").append(toIndentedString(numDocuments)).append("\n");
    sb.append("    numPages: ").append(toIndentedString(numPages)).append("\n");
    sb.append("    averageTimePerPage: ").append(toIndentedString(averageTimePerPage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
