/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.BusinessTransactionExtraction1;
import com.axonivy.connector.idp.connector.model.StringExtraction3;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * InsuranceBusinessTransaction
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class InsuranceBusinessTransaction {
  /**
   * Gets or Sets schemaVersion
   */
  public enum SchemaVersionEnum {
    NUMBER_1(1);

    private Integer value;

    SchemaVersionEnum(Integer value) {
      this.value = value;
    }
    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SchemaVersionEnum fromValue(Integer input) {
      for (SchemaVersionEnum b : SchemaVersionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("schema_version")
  private SchemaVersionEnum schemaVersion = SchemaVersionEnum.NUMBER_1;

  /**
   * Gets or Sets documentType
   */
  public enum DocumentTypeEnum {
    INSURANCE_BUSINESS_TRANSACTION("insurance_business_transaction");

    private String value;

    DocumentTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static DocumentTypeEnum fromValue(String input) {
      for (DocumentTypeEnum b : DocumentTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("document_type")
  private DocumentTypeEnum documentType = null;

  @JsonProperty("insurance_numbers")
  private List<StringExtraction3> insuranceNumbers = new ArrayList<>();

  @JsonProperty("contract_partner_numbers")
  private List<StringExtraction3> contractPartnerNumbers = new ArrayList<>();

  @JsonProperty("preliminary_review_numbers")
  private List<StringExtraction3> preliminaryReviewNumbers = new ArrayList<>();

  @JsonProperty("business_transaction")
  private BusinessTransactionExtraction1 businessTransaction = null;

  public InsuranceBusinessTransaction schemaVersion(SchemaVersionEnum schemaVersion) {
    this.schemaVersion = schemaVersion;
    return this;
  }

   /**
   * Get schemaVersion
   * @return schemaVersion
  **/
  public SchemaVersionEnum getSchemaVersion() {
    return schemaVersion;
  }

  public void setSchemaVersion(SchemaVersionEnum schemaVersion) {
    this.schemaVersion = schemaVersion;
  }

  public InsuranceBusinessTransaction documentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
    return this;
  }

   /**
   * Get documentType
   * @return documentType
  **/
  public DocumentTypeEnum getDocumentType() {
    return documentType;
  }

  public void setDocumentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
  }

  public InsuranceBusinessTransaction insuranceNumbers(List<StringExtraction3> insuranceNumbers) {
    this.insuranceNumbers = insuranceNumbers;
    return this;
  }

  public InsuranceBusinessTransaction addInsuranceNumbersItem(StringExtraction3 insuranceNumbersItem) {
    this.insuranceNumbers.add(insuranceNumbersItem);
    return this;
  }

   /**
   * Get insuranceNumbers
   * @return insuranceNumbers
  **/
  public List<StringExtraction3> getInsuranceNumbers() {
    return insuranceNumbers;
  }

  public void setInsuranceNumbers(List<StringExtraction3> insuranceNumbers) {
    this.insuranceNumbers = insuranceNumbers;
  }

  public InsuranceBusinessTransaction contractPartnerNumbers(List<StringExtraction3> contractPartnerNumbers) {
    this.contractPartnerNumbers = contractPartnerNumbers;
    return this;
  }

  public InsuranceBusinessTransaction addContractPartnerNumbersItem(StringExtraction3 contractPartnerNumbersItem) {
    this.contractPartnerNumbers.add(contractPartnerNumbersItem);
    return this;
  }

   /**
   * Get contractPartnerNumbers
   * @return contractPartnerNumbers
  **/
  public List<StringExtraction3> getContractPartnerNumbers() {
    return contractPartnerNumbers;
  }

  public void setContractPartnerNumbers(List<StringExtraction3> contractPartnerNumbers) {
    this.contractPartnerNumbers = contractPartnerNumbers;
  }

  public InsuranceBusinessTransaction preliminaryReviewNumbers(List<StringExtraction3> preliminaryReviewNumbers) {
    this.preliminaryReviewNumbers = preliminaryReviewNumbers;
    return this;
  }

  public InsuranceBusinessTransaction addPreliminaryReviewNumbersItem(StringExtraction3 preliminaryReviewNumbersItem) {
    this.preliminaryReviewNumbers.add(preliminaryReviewNumbersItem);
    return this;
  }

   /**
   * Get preliminaryReviewNumbers
   * @return preliminaryReviewNumbers
  **/
  public List<StringExtraction3> getPreliminaryReviewNumbers() {
    return preliminaryReviewNumbers;
  }

  public void setPreliminaryReviewNumbers(List<StringExtraction3> preliminaryReviewNumbers) {
    this.preliminaryReviewNumbers = preliminaryReviewNumbers;
  }

  public InsuranceBusinessTransaction businessTransaction(BusinessTransactionExtraction1 businessTransaction) {
    this.businessTransaction = businessTransaction;
    return this;
  }

   /**
   * Get businessTransaction
   * @return businessTransaction
  **/
  public BusinessTransactionExtraction1 getBusinessTransaction() {
    return businessTransaction;
  }

  public void setBusinessTransaction(BusinessTransactionExtraction1 businessTransaction) {
    this.businessTransaction = businessTransaction;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InsuranceBusinessTransaction insuranceBusinessTransaction = (InsuranceBusinessTransaction) o;
    return Objects.equals(this.schemaVersion, insuranceBusinessTransaction.schemaVersion) &&
        Objects.equals(this.documentType, insuranceBusinessTransaction.documentType) &&
        Objects.equals(this.insuranceNumbers, insuranceBusinessTransaction.insuranceNumbers) &&
        Objects.equals(this.contractPartnerNumbers, insuranceBusinessTransaction.contractPartnerNumbers) &&
        Objects.equals(this.preliminaryReviewNumbers, insuranceBusinessTransaction.preliminaryReviewNumbers) &&
        Objects.equals(this.businessTransaction, insuranceBusinessTransaction.businessTransaction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(schemaVersion, documentType, insuranceNumbers, contractPartnerNumbers, preliminaryReviewNumbers, businessTransaction);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InsuranceBusinessTransaction {\n");
    
    sb.append("    schemaVersion: ").append(toIndentedString(schemaVersion)).append("\n");
    sb.append("    documentType: ").append(toIndentedString(documentType)).append("\n");
    sb.append("    insuranceNumbers: ").append(toIndentedString(insuranceNumbers)).append("\n");
    sb.append("    contractPartnerNumbers: ").append(toIndentedString(contractPartnerNumbers)).append("\n");
    sb.append("    preliminaryReviewNumbers: ").append(toIndentedString(preliminaryReviewNumbers)).append("\n");
    sb.append("    businessTransaction: ").append(toIndentedString(businessTransaction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
