/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.FloatExtraction1;
import com.axonivy.connector.idp.connector.model.StringExtraction1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * Jib
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class Jib {
  @JsonProperty("number_of_jibs")
  private List<FloatExtraction1> numberOfJibs = new ArrayList<>();

  @JsonProperty("crane_type")
  private List<StringExtraction1> craneType = new ArrayList<>();

  @JsonProperty("pillar_mounted_attachment")
  private List<StringExtraction1> pillarMountedAttachment = new ArrayList<>();

  @JsonProperty("attachment_structure")
  private List<StringExtraction1> attachmentStructure = new ArrayList<>();

  @JsonProperty("top_edge_of_floor_to_hook")
  private List<StringExtraction1> topEdgeOfFloorToHook = new ArrayList<>();

  @JsonProperty("bottom_edge_girder_height")
  private List<StringExtraction1> bottomEdgeGirderHeight = new ArrayList<>();

  @JsonProperty("max_pillar_height")
  private List<StringExtraction1> maxPillarHeight = new ArrayList<>();

  @JsonProperty("design")
  private List<StringExtraction1> design = new ArrayList<>();

  @JsonProperty("outreach")
  private List<StringExtraction1> outreach = new ArrayList<>();

  @JsonProperty("power_supply")
  private List<StringExtraction1> powerSupply = new ArrayList<>();

  @JsonProperty("position_of_arms")
  private List<StringExtraction1> positionOfArms = new ArrayList<>();

  @JsonProperty("profile")
  private List<StringExtraction1> profile = new ArrayList<>();

  @JsonProperty("slewing")
  private List<StringExtraction1> slewing = new ArrayList<>();

  @JsonProperty("slewing_limitations")
  private List<StringExtraction1> slewingLimitations = new ArrayList<>();

  @JsonProperty("slewing_limit_switch")
  private List<StringExtraction1> slewingLimitSwitch = new ArrayList<>();

  @JsonProperty("slewing_range")
  private List<StringExtraction1> slewingRange = new ArrayList<>();

  @JsonProperty("product_key")
  private List<StringExtraction1> productKey = new ArrayList<>();

  public Jib numberOfJibs(List<FloatExtraction1> numberOfJibs) {
    this.numberOfJibs = numberOfJibs;
    return this;
  }

  public Jib addNumberOfJibsItem(FloatExtraction1 numberOfJibsItem) {
    this.numberOfJibs.add(numberOfJibsItem);
    return this;
  }

   /**
   * Get numberOfJibs
   * @return numberOfJibs
  **/
  public List<FloatExtraction1> getNumberOfJibs() {
    return numberOfJibs;
  }

  public void setNumberOfJibs(List<FloatExtraction1> numberOfJibs) {
    this.numberOfJibs = numberOfJibs;
  }

  public Jib craneType(List<StringExtraction1> craneType) {
    this.craneType = craneType;
    return this;
  }

  public Jib addCraneTypeItem(StringExtraction1 craneTypeItem) {
    this.craneType.add(craneTypeItem);
    return this;
  }

   /**
   * Get craneType
   * @return craneType
  **/
  public List<StringExtraction1> getCraneType() {
    return craneType;
  }

  public void setCraneType(List<StringExtraction1> craneType) {
    this.craneType = craneType;
  }

  public Jib pillarMountedAttachment(List<StringExtraction1> pillarMountedAttachment) {
    this.pillarMountedAttachment = pillarMountedAttachment;
    return this;
  }

  public Jib addPillarMountedAttachmentItem(StringExtraction1 pillarMountedAttachmentItem) {
    this.pillarMountedAttachment.add(pillarMountedAttachmentItem);
    return this;
  }

   /**
   * Get pillarMountedAttachment
   * @return pillarMountedAttachment
  **/
  public List<StringExtraction1> getPillarMountedAttachment() {
    return pillarMountedAttachment;
  }

  public void setPillarMountedAttachment(List<StringExtraction1> pillarMountedAttachment) {
    this.pillarMountedAttachment = pillarMountedAttachment;
  }

  public Jib attachmentStructure(List<StringExtraction1> attachmentStructure) {
    this.attachmentStructure = attachmentStructure;
    return this;
  }

  public Jib addAttachmentStructureItem(StringExtraction1 attachmentStructureItem) {
    this.attachmentStructure.add(attachmentStructureItem);
    return this;
  }

   /**
   * Get attachmentStructure
   * @return attachmentStructure
  **/
  public List<StringExtraction1> getAttachmentStructure() {
    return attachmentStructure;
  }

  public void setAttachmentStructure(List<StringExtraction1> attachmentStructure) {
    this.attachmentStructure = attachmentStructure;
  }

  public Jib topEdgeOfFloorToHook(List<StringExtraction1> topEdgeOfFloorToHook) {
    this.topEdgeOfFloorToHook = topEdgeOfFloorToHook;
    return this;
  }

  public Jib addTopEdgeOfFloorToHookItem(StringExtraction1 topEdgeOfFloorToHookItem) {
    this.topEdgeOfFloorToHook.add(topEdgeOfFloorToHookItem);
    return this;
  }

   /**
   * Get topEdgeOfFloorToHook
   * @return topEdgeOfFloorToHook
  **/
  public List<StringExtraction1> getTopEdgeOfFloorToHook() {
    return topEdgeOfFloorToHook;
  }

  public void setTopEdgeOfFloorToHook(List<StringExtraction1> topEdgeOfFloorToHook) {
    this.topEdgeOfFloorToHook = topEdgeOfFloorToHook;
  }

  public Jib bottomEdgeGirderHeight(List<StringExtraction1> bottomEdgeGirderHeight) {
    this.bottomEdgeGirderHeight = bottomEdgeGirderHeight;
    return this;
  }

  public Jib addBottomEdgeGirderHeightItem(StringExtraction1 bottomEdgeGirderHeightItem) {
    this.bottomEdgeGirderHeight.add(bottomEdgeGirderHeightItem);
    return this;
  }

   /**
   * Get bottomEdgeGirderHeight
   * @return bottomEdgeGirderHeight
  **/
  public List<StringExtraction1> getBottomEdgeGirderHeight() {
    return bottomEdgeGirderHeight;
  }

  public void setBottomEdgeGirderHeight(List<StringExtraction1> bottomEdgeGirderHeight) {
    this.bottomEdgeGirderHeight = bottomEdgeGirderHeight;
  }

  public Jib maxPillarHeight(List<StringExtraction1> maxPillarHeight) {
    this.maxPillarHeight = maxPillarHeight;
    return this;
  }

  public Jib addMaxPillarHeightItem(StringExtraction1 maxPillarHeightItem) {
    this.maxPillarHeight.add(maxPillarHeightItem);
    return this;
  }

   /**
   * Get maxPillarHeight
   * @return maxPillarHeight
  **/
  public List<StringExtraction1> getMaxPillarHeight() {
    return maxPillarHeight;
  }

  public void setMaxPillarHeight(List<StringExtraction1> maxPillarHeight) {
    this.maxPillarHeight = maxPillarHeight;
  }

  public Jib design(List<StringExtraction1> design) {
    this.design = design;
    return this;
  }

  public Jib addDesignItem(StringExtraction1 designItem) {
    this.design.add(designItem);
    return this;
  }

   /**
   * Get design
   * @return design
  **/
  public List<StringExtraction1> getDesign() {
    return design;
  }

  public void setDesign(List<StringExtraction1> design) {
    this.design = design;
  }

  public Jib outreach(List<StringExtraction1> outreach) {
    this.outreach = outreach;
    return this;
  }

  public Jib addOutreachItem(StringExtraction1 outreachItem) {
    this.outreach.add(outreachItem);
    return this;
  }

   /**
   * Get outreach
   * @return outreach
  **/
  public List<StringExtraction1> getOutreach() {
    return outreach;
  }

  public void setOutreach(List<StringExtraction1> outreach) {
    this.outreach = outreach;
  }

  public Jib powerSupply(List<StringExtraction1> powerSupply) {
    this.powerSupply = powerSupply;
    return this;
  }

  public Jib addPowerSupplyItem(StringExtraction1 powerSupplyItem) {
    this.powerSupply.add(powerSupplyItem);
    return this;
  }

   /**
   * Get powerSupply
   * @return powerSupply
  **/
  public List<StringExtraction1> getPowerSupply() {
    return powerSupply;
  }

  public void setPowerSupply(List<StringExtraction1> powerSupply) {
    this.powerSupply = powerSupply;
  }

  public Jib positionOfArms(List<StringExtraction1> positionOfArms) {
    this.positionOfArms = positionOfArms;
    return this;
  }

  public Jib addPositionOfArmsItem(StringExtraction1 positionOfArmsItem) {
    this.positionOfArms.add(positionOfArmsItem);
    return this;
  }

   /**
   * Get positionOfArms
   * @return positionOfArms
  **/
  public List<StringExtraction1> getPositionOfArms() {
    return positionOfArms;
  }

  public void setPositionOfArms(List<StringExtraction1> positionOfArms) {
    this.positionOfArms = positionOfArms;
  }

  public Jib profile(List<StringExtraction1> profile) {
    this.profile = profile;
    return this;
  }

  public Jib addProfileItem(StringExtraction1 profileItem) {
    this.profile.add(profileItem);
    return this;
  }

   /**
   * Get profile
   * @return profile
  **/
  public List<StringExtraction1> getProfile() {
    return profile;
  }

  public void setProfile(List<StringExtraction1> profile) {
    this.profile = profile;
  }

  public Jib slewing(List<StringExtraction1> slewing) {
    this.slewing = slewing;
    return this;
  }

  public Jib addSlewingItem(StringExtraction1 slewingItem) {
    this.slewing.add(slewingItem);
    return this;
  }

   /**
   * Get slewing
   * @return slewing
  **/
  public List<StringExtraction1> getSlewing() {
    return slewing;
  }

  public void setSlewing(List<StringExtraction1> slewing) {
    this.slewing = slewing;
  }

  public Jib slewingLimitations(List<StringExtraction1> slewingLimitations) {
    this.slewingLimitations = slewingLimitations;
    return this;
  }

  public Jib addSlewingLimitationsItem(StringExtraction1 slewingLimitationsItem) {
    this.slewingLimitations.add(slewingLimitationsItem);
    return this;
  }

   /**
   * Get slewingLimitations
   * @return slewingLimitations
  **/
  public List<StringExtraction1> getSlewingLimitations() {
    return slewingLimitations;
  }

  public void setSlewingLimitations(List<StringExtraction1> slewingLimitations) {
    this.slewingLimitations = slewingLimitations;
  }

  public Jib slewingLimitSwitch(List<StringExtraction1> slewingLimitSwitch) {
    this.slewingLimitSwitch = slewingLimitSwitch;
    return this;
  }

  public Jib addSlewingLimitSwitchItem(StringExtraction1 slewingLimitSwitchItem) {
    this.slewingLimitSwitch.add(slewingLimitSwitchItem);
    return this;
  }

   /**
   * Get slewingLimitSwitch
   * @return slewingLimitSwitch
  **/
  public List<StringExtraction1> getSlewingLimitSwitch() {
    return slewingLimitSwitch;
  }

  public void setSlewingLimitSwitch(List<StringExtraction1> slewingLimitSwitch) {
    this.slewingLimitSwitch = slewingLimitSwitch;
  }

  public Jib slewingRange(List<StringExtraction1> slewingRange) {
    this.slewingRange = slewingRange;
    return this;
  }

  public Jib addSlewingRangeItem(StringExtraction1 slewingRangeItem) {
    this.slewingRange.add(slewingRangeItem);
    return this;
  }

   /**
   * Get slewingRange
   * @return slewingRange
  **/
  public List<StringExtraction1> getSlewingRange() {
    return slewingRange;
  }

  public void setSlewingRange(List<StringExtraction1> slewingRange) {
    this.slewingRange = slewingRange;
  }

  public Jib productKey(List<StringExtraction1> productKey) {
    this.productKey = productKey;
    return this;
  }

  public Jib addProductKeyItem(StringExtraction1 productKeyItem) {
    this.productKey.add(productKeyItem);
    return this;
  }

   /**
   * Get productKey
   * @return productKey
  **/
  public List<StringExtraction1> getProductKey() {
    return productKey;
  }

  public void setProductKey(List<StringExtraction1> productKey) {
    this.productKey = productKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Jib jib = (Jib) o;
    return Objects.equals(this.numberOfJibs, jib.numberOfJibs) &&
        Objects.equals(this.craneType, jib.craneType) &&
        Objects.equals(this.pillarMountedAttachment, jib.pillarMountedAttachment) &&
        Objects.equals(this.attachmentStructure, jib.attachmentStructure) &&
        Objects.equals(this.topEdgeOfFloorToHook, jib.topEdgeOfFloorToHook) &&
        Objects.equals(this.bottomEdgeGirderHeight, jib.bottomEdgeGirderHeight) &&
        Objects.equals(this.maxPillarHeight, jib.maxPillarHeight) &&
        Objects.equals(this.design, jib.design) &&
        Objects.equals(this.outreach, jib.outreach) &&
        Objects.equals(this.powerSupply, jib.powerSupply) &&
        Objects.equals(this.positionOfArms, jib.positionOfArms) &&
        Objects.equals(this.profile, jib.profile) &&
        Objects.equals(this.slewing, jib.slewing) &&
        Objects.equals(this.slewingLimitations, jib.slewingLimitations) &&
        Objects.equals(this.slewingLimitSwitch, jib.slewingLimitSwitch) &&
        Objects.equals(this.slewingRange, jib.slewingRange) &&
        Objects.equals(this.productKey, jib.productKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numberOfJibs, craneType, pillarMountedAttachment, attachmentStructure, topEdgeOfFloorToHook, bottomEdgeGirderHeight, maxPillarHeight, design, outreach, powerSupply, positionOfArms, profile, slewing, slewingLimitations, slewingLimitSwitch, slewingRange, productKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Jib {\n");
    
    sb.append("    numberOfJibs: ").append(toIndentedString(numberOfJibs)).append("\n");
    sb.append("    craneType: ").append(toIndentedString(craneType)).append("\n");
    sb.append("    pillarMountedAttachment: ").append(toIndentedString(pillarMountedAttachment)).append("\n");
    sb.append("    attachmentStructure: ").append(toIndentedString(attachmentStructure)).append("\n");
    sb.append("    topEdgeOfFloorToHook: ").append(toIndentedString(topEdgeOfFloorToHook)).append("\n");
    sb.append("    bottomEdgeGirderHeight: ").append(toIndentedString(bottomEdgeGirderHeight)).append("\n");
    sb.append("    maxPillarHeight: ").append(toIndentedString(maxPillarHeight)).append("\n");
    sb.append("    design: ").append(toIndentedString(design)).append("\n");
    sb.append("    outreach: ").append(toIndentedString(outreach)).append("\n");
    sb.append("    powerSupply: ").append(toIndentedString(powerSupply)).append("\n");
    sb.append("    positionOfArms: ").append(toIndentedString(positionOfArms)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    slewing: ").append(toIndentedString(slewing)).append("\n");
    sb.append("    slewingLimitations: ").append(toIndentedString(slewingLimitations)).append("\n");
    sb.append("    slewingLimitSwitch: ").append(toIndentedString(slewingLimitSwitch)).append("\n");
    sb.append("    slewingRange: ").append(toIndentedString(slewingRange)).append("\n");
    sb.append("    productKey: ").append(toIndentedString(productKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
