/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.InvoiceKey;
import com.axonivy.connector.idp.connector.model.InvoiceValue;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * KeyValuePair3
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class KeyValuePair3 {
  @JsonProperty("key")
  private InvoiceKey key = null;

  @JsonProperty("value")
  private InvoiceValue value = null;

  public KeyValuePair3 key(InvoiceKey key) {
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  public InvoiceKey getKey() {
    return key;
  }

  public void setKey(InvoiceKey key) {
    this.key = key;
  }

  public KeyValuePair3 value(InvoiceValue value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  public InvoiceValue getValue() {
    return value;
  }

  public void setValue(InvoiceValue value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KeyValuePair3 keyValuePair3 = (KeyValuePair3) o;
    return Objects.equals(this.key, keyValuePair3.key) &&
        Objects.equals(this.value, keyValuePair3.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeyValuePair3 {\n");
    
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
