/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.StringExtraction2;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Land1
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class Land1 {
  @JsonProperty("cadastral_district")
  private StringExtraction2 cadastralDistrict = null;

  @JsonProperty("plot")
  private StringExtraction2 plot = null;

  @JsonProperty("plot_number")
  private StringExtraction2 plotNumber = null;

  public Land1 cadastralDistrict(StringExtraction2 cadastralDistrict) {
    this.cadastralDistrict = cadastralDistrict;
    return this;
  }

   /**
   * Get cadastralDistrict
   * @return cadastralDistrict
  **/
  public StringExtraction2 getCadastralDistrict() {
    return cadastralDistrict;
  }

  public void setCadastralDistrict(StringExtraction2 cadastralDistrict) {
    this.cadastralDistrict = cadastralDistrict;
  }

  public Land1 plot(StringExtraction2 plot) {
    this.plot = plot;
    return this;
  }

   /**
   * Get plot
   * @return plot
  **/
  public StringExtraction2 getPlot() {
    return plot;
  }

  public void setPlot(StringExtraction2 plot) {
    this.plot = plot;
  }

  public Land1 plotNumber(StringExtraction2 plotNumber) {
    this.plotNumber = plotNumber;
    return this;
  }

   /**
   * Get plotNumber
   * @return plotNumber
  **/
  public StringExtraction2 getPlotNumber() {
    return plotNumber;
  }

  public void setPlotNumber(StringExtraction2 plotNumber) {
    this.plotNumber = plotNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Land1 land1 = (Land1) o;
    return Objects.equals(this.cadastralDistrict, land1.cadastralDistrict) &&
        Objects.equals(this.plot, land1.plot) &&
        Objects.equals(this.plotNumber, land1.plotNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cadastralDistrict, plot, plotNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Land1 {\n");
    
    sb.append("    cadastralDistrict: ").append(toIndentedString(cadastralDistrict)).append("\n");
    sb.append("    plot: ").append(toIndentedString(plot)).append("\n");
    sb.append("    plotNumber: ").append(toIndentedString(plotNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
