/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.DateExtractionOptions1;
import com.axonivy.connector.idp.connector.model.FloatExtractionOptions1;
import com.axonivy.connector.idp.connector.model.PeriodOptions1;
import com.axonivy.connector.idp.connector.model.StringExtractionOptions1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * LineItem8
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class LineItem8 {
  @JsonProperty("pos_id")
  private StringExtractionOptions1 posId = null;

  @JsonProperty("article_id")
  private StringExtractionOptions1 articleId = null;

  @JsonProperty("ean")
  private StringExtractionOptions1 ean = null;

  @JsonProperty("description")
  private StringExtractionOptions1 description = null;

  @JsonProperty("quantity")
  private FloatExtractionOptions1 quantity = null;

  @JsonProperty("unit_of_measure")
  private StringExtractionOptions1 unitOfMeasure = null;

  @JsonProperty("service_period")
  private PeriodOptions1 servicePeriod = null;

  @JsonProperty("order_date")
  private DateExtractionOptions1 orderDate = null;

  @JsonProperty("order_confirmation_date")
  private DateExtractionOptions1 orderConfirmationDate = null;

  @JsonProperty("delivery_note_date")
  private DateExtractionOptions1 deliveryNoteDate = null;

  @JsonProperty("discount")
  private FloatExtractionOptions1 discount = null;

  @JsonProperty("additional_cost")
  private FloatExtractionOptions1 additionalCost = null;

  @JsonProperty("tax_rate")
  private FloatExtractionOptions1 taxRate = null;

  @JsonProperty("tax_code")
  private StringExtractionOptions1 taxCode = null;

  @JsonProperty("unit_price_net")
  private FloatExtractionOptions1 unitPriceNet = null;

  @JsonProperty("unit_price_gross")
  private FloatExtractionOptions1 unitPriceGross = null;

  @JsonProperty("unit_price_unknown")
  private FloatExtractionOptions1 unitPriceUnknown = null;

  @JsonProperty("price_unit")
  private StringExtractionOptions1 priceUnit = null;

  @JsonProperty("total_price_net")
  private FloatExtractionOptions1 totalPriceNet = null;

  @JsonProperty("total_price_gross")
  private FloatExtractionOptions1 totalPriceGross = null;

  @JsonProperty("total_price_tax_amount")
  private FloatExtractionOptions1 totalPriceTaxAmount = null;

  @JsonProperty("total_price_unknown")
  private FloatExtractionOptions1 totalPriceUnknown = null;

  @JsonProperty("order_number")
  private StringExtractionOptions1 orderNumber = null;

  @JsonProperty("order_confirmation_number")
  private StringExtractionOptions1 orderConfirmationNumber = null;

  @JsonProperty("delivery_note_number")
  private StringExtractionOptions1 deliveryNoteNumber = null;

  public LineItem8 posId(StringExtractionOptions1 posId) {
    this.posId = posId;
    return this;
  }

   /**
   * Get posId
   * @return posId
  **/
  public StringExtractionOptions1 getPosId() {
    return posId;
  }

  public void setPosId(StringExtractionOptions1 posId) {
    this.posId = posId;
  }

  public LineItem8 articleId(StringExtractionOptions1 articleId) {
    this.articleId = articleId;
    return this;
  }

   /**
   * Get articleId
   * @return articleId
  **/
  public StringExtractionOptions1 getArticleId() {
    return articleId;
  }

  public void setArticleId(StringExtractionOptions1 articleId) {
    this.articleId = articleId;
  }

  public LineItem8 ean(StringExtractionOptions1 ean) {
    this.ean = ean;
    return this;
  }

   /**
   * Get ean
   * @return ean
  **/
  public StringExtractionOptions1 getEan() {
    return ean;
  }

  public void setEan(StringExtractionOptions1 ean) {
    this.ean = ean;
  }

  public LineItem8 description(StringExtractionOptions1 description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public StringExtractionOptions1 getDescription() {
    return description;
  }

  public void setDescription(StringExtractionOptions1 description) {
    this.description = description;
  }

  public LineItem8 quantity(FloatExtractionOptions1 quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  public FloatExtractionOptions1 getQuantity() {
    return quantity;
  }

  public void setQuantity(FloatExtractionOptions1 quantity) {
    this.quantity = quantity;
  }

  public LineItem8 unitOfMeasure(StringExtractionOptions1 unitOfMeasure) {
    this.unitOfMeasure = unitOfMeasure;
    return this;
  }

   /**
   * Get unitOfMeasure
   * @return unitOfMeasure
  **/
  public StringExtractionOptions1 getUnitOfMeasure() {
    return unitOfMeasure;
  }

  public void setUnitOfMeasure(StringExtractionOptions1 unitOfMeasure) {
    this.unitOfMeasure = unitOfMeasure;
  }

  public LineItem8 servicePeriod(PeriodOptions1 servicePeriod) {
    this.servicePeriod = servicePeriod;
    return this;
  }

   /**
   * Get servicePeriod
   * @return servicePeriod
  **/
  public PeriodOptions1 getServicePeriod() {
    return servicePeriod;
  }

  public void setServicePeriod(PeriodOptions1 servicePeriod) {
    this.servicePeriod = servicePeriod;
  }

  public LineItem8 orderDate(DateExtractionOptions1 orderDate) {
    this.orderDate = orderDate;
    return this;
  }

   /**
   * Get orderDate
   * @return orderDate
  **/
  public DateExtractionOptions1 getOrderDate() {
    return orderDate;
  }

  public void setOrderDate(DateExtractionOptions1 orderDate) {
    this.orderDate = orderDate;
  }

  public LineItem8 orderConfirmationDate(DateExtractionOptions1 orderConfirmationDate) {
    this.orderConfirmationDate = orderConfirmationDate;
    return this;
  }

   /**
   * Get orderConfirmationDate
   * @return orderConfirmationDate
  **/
  public DateExtractionOptions1 getOrderConfirmationDate() {
    return orderConfirmationDate;
  }

  public void setOrderConfirmationDate(DateExtractionOptions1 orderConfirmationDate) {
    this.orderConfirmationDate = orderConfirmationDate;
  }

  public LineItem8 deliveryNoteDate(DateExtractionOptions1 deliveryNoteDate) {
    this.deliveryNoteDate = deliveryNoteDate;
    return this;
  }

   /**
   * Get deliveryNoteDate
   * @return deliveryNoteDate
  **/
  public DateExtractionOptions1 getDeliveryNoteDate() {
    return deliveryNoteDate;
  }

  public void setDeliveryNoteDate(DateExtractionOptions1 deliveryNoteDate) {
    this.deliveryNoteDate = deliveryNoteDate;
  }

  public LineItem8 discount(FloatExtractionOptions1 discount) {
    this.discount = discount;
    return this;
  }

   /**
   * Get discount
   * @return discount
  **/
  public FloatExtractionOptions1 getDiscount() {
    return discount;
  }

  public void setDiscount(FloatExtractionOptions1 discount) {
    this.discount = discount;
  }

  public LineItem8 additionalCost(FloatExtractionOptions1 additionalCost) {
    this.additionalCost = additionalCost;
    return this;
  }

   /**
   * Get additionalCost
   * @return additionalCost
  **/
  public FloatExtractionOptions1 getAdditionalCost() {
    return additionalCost;
  }

  public void setAdditionalCost(FloatExtractionOptions1 additionalCost) {
    this.additionalCost = additionalCost;
  }

  public LineItem8 taxRate(FloatExtractionOptions1 taxRate) {
    this.taxRate = taxRate;
    return this;
  }

   /**
   * Get taxRate
   * @return taxRate
  **/
  public FloatExtractionOptions1 getTaxRate() {
    return taxRate;
  }

  public void setTaxRate(FloatExtractionOptions1 taxRate) {
    this.taxRate = taxRate;
  }

  public LineItem8 taxCode(StringExtractionOptions1 taxCode) {
    this.taxCode = taxCode;
    return this;
  }

   /**
   * Get taxCode
   * @return taxCode
  **/
  public StringExtractionOptions1 getTaxCode() {
    return taxCode;
  }

  public void setTaxCode(StringExtractionOptions1 taxCode) {
    this.taxCode = taxCode;
  }

  public LineItem8 unitPriceNet(FloatExtractionOptions1 unitPriceNet) {
    this.unitPriceNet = unitPriceNet;
    return this;
  }

   /**
   * Get unitPriceNet
   * @return unitPriceNet
  **/
  public FloatExtractionOptions1 getUnitPriceNet() {
    return unitPriceNet;
  }

  public void setUnitPriceNet(FloatExtractionOptions1 unitPriceNet) {
    this.unitPriceNet = unitPriceNet;
  }

  public LineItem8 unitPriceGross(FloatExtractionOptions1 unitPriceGross) {
    this.unitPriceGross = unitPriceGross;
    return this;
  }

   /**
   * Get unitPriceGross
   * @return unitPriceGross
  **/
  public FloatExtractionOptions1 getUnitPriceGross() {
    return unitPriceGross;
  }

  public void setUnitPriceGross(FloatExtractionOptions1 unitPriceGross) {
    this.unitPriceGross = unitPriceGross;
  }

  public LineItem8 unitPriceUnknown(FloatExtractionOptions1 unitPriceUnknown) {
    this.unitPriceUnknown = unitPriceUnknown;
    return this;
  }

   /**
   * Get unitPriceUnknown
   * @return unitPriceUnknown
  **/
  public FloatExtractionOptions1 getUnitPriceUnknown() {
    return unitPriceUnknown;
  }

  public void setUnitPriceUnknown(FloatExtractionOptions1 unitPriceUnknown) {
    this.unitPriceUnknown = unitPriceUnknown;
  }

  public LineItem8 priceUnit(StringExtractionOptions1 priceUnit) {
    this.priceUnit = priceUnit;
    return this;
  }

   /**
   * Get priceUnit
   * @return priceUnit
  **/
  public StringExtractionOptions1 getPriceUnit() {
    return priceUnit;
  }

  public void setPriceUnit(StringExtractionOptions1 priceUnit) {
    this.priceUnit = priceUnit;
  }

  public LineItem8 totalPriceNet(FloatExtractionOptions1 totalPriceNet) {
    this.totalPriceNet = totalPriceNet;
    return this;
  }

   /**
   * Get totalPriceNet
   * @return totalPriceNet
  **/
  public FloatExtractionOptions1 getTotalPriceNet() {
    return totalPriceNet;
  }

  public void setTotalPriceNet(FloatExtractionOptions1 totalPriceNet) {
    this.totalPriceNet = totalPriceNet;
  }

  public LineItem8 totalPriceGross(FloatExtractionOptions1 totalPriceGross) {
    this.totalPriceGross = totalPriceGross;
    return this;
  }

   /**
   * Get totalPriceGross
   * @return totalPriceGross
  **/
  public FloatExtractionOptions1 getTotalPriceGross() {
    return totalPriceGross;
  }

  public void setTotalPriceGross(FloatExtractionOptions1 totalPriceGross) {
    this.totalPriceGross = totalPriceGross;
  }

  public LineItem8 totalPriceTaxAmount(FloatExtractionOptions1 totalPriceTaxAmount) {
    this.totalPriceTaxAmount = totalPriceTaxAmount;
    return this;
  }

   /**
   * Get totalPriceTaxAmount
   * @return totalPriceTaxAmount
  **/
  public FloatExtractionOptions1 getTotalPriceTaxAmount() {
    return totalPriceTaxAmount;
  }

  public void setTotalPriceTaxAmount(FloatExtractionOptions1 totalPriceTaxAmount) {
    this.totalPriceTaxAmount = totalPriceTaxAmount;
  }

  public LineItem8 totalPriceUnknown(FloatExtractionOptions1 totalPriceUnknown) {
    this.totalPriceUnknown = totalPriceUnknown;
    return this;
  }

   /**
   * Get totalPriceUnknown
   * @return totalPriceUnknown
  **/
  public FloatExtractionOptions1 getTotalPriceUnknown() {
    return totalPriceUnknown;
  }

  public void setTotalPriceUnknown(FloatExtractionOptions1 totalPriceUnknown) {
    this.totalPriceUnknown = totalPriceUnknown;
  }

  public LineItem8 orderNumber(StringExtractionOptions1 orderNumber) {
    this.orderNumber = orderNumber;
    return this;
  }

   /**
   * Get orderNumber
   * @return orderNumber
  **/
  public StringExtractionOptions1 getOrderNumber() {
    return orderNumber;
  }

  public void setOrderNumber(StringExtractionOptions1 orderNumber) {
    this.orderNumber = orderNumber;
  }

  public LineItem8 orderConfirmationNumber(StringExtractionOptions1 orderConfirmationNumber) {
    this.orderConfirmationNumber = orderConfirmationNumber;
    return this;
  }

   /**
   * Get orderConfirmationNumber
   * @return orderConfirmationNumber
  **/
  public StringExtractionOptions1 getOrderConfirmationNumber() {
    return orderConfirmationNumber;
  }

  public void setOrderConfirmationNumber(StringExtractionOptions1 orderConfirmationNumber) {
    this.orderConfirmationNumber = orderConfirmationNumber;
  }

  public LineItem8 deliveryNoteNumber(StringExtractionOptions1 deliveryNoteNumber) {
    this.deliveryNoteNumber = deliveryNoteNumber;
    return this;
  }

   /**
   * Get deliveryNoteNumber
   * @return deliveryNoteNumber
  **/
  public StringExtractionOptions1 getDeliveryNoteNumber() {
    return deliveryNoteNumber;
  }

  public void setDeliveryNoteNumber(StringExtractionOptions1 deliveryNoteNumber) {
    this.deliveryNoteNumber = deliveryNoteNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LineItem8 lineItem8 = (LineItem8) o;
    return Objects.equals(this.posId, lineItem8.posId) &&
        Objects.equals(this.articleId, lineItem8.articleId) &&
        Objects.equals(this.ean, lineItem8.ean) &&
        Objects.equals(this.description, lineItem8.description) &&
        Objects.equals(this.quantity, lineItem8.quantity) &&
        Objects.equals(this.unitOfMeasure, lineItem8.unitOfMeasure) &&
        Objects.equals(this.servicePeriod, lineItem8.servicePeriod) &&
        Objects.equals(this.orderDate, lineItem8.orderDate) &&
        Objects.equals(this.orderConfirmationDate, lineItem8.orderConfirmationDate) &&
        Objects.equals(this.deliveryNoteDate, lineItem8.deliveryNoteDate) &&
        Objects.equals(this.discount, lineItem8.discount) &&
        Objects.equals(this.additionalCost, lineItem8.additionalCost) &&
        Objects.equals(this.taxRate, lineItem8.taxRate) &&
        Objects.equals(this.taxCode, lineItem8.taxCode) &&
        Objects.equals(this.unitPriceNet, lineItem8.unitPriceNet) &&
        Objects.equals(this.unitPriceGross, lineItem8.unitPriceGross) &&
        Objects.equals(this.unitPriceUnknown, lineItem8.unitPriceUnknown) &&
        Objects.equals(this.priceUnit, lineItem8.priceUnit) &&
        Objects.equals(this.totalPriceNet, lineItem8.totalPriceNet) &&
        Objects.equals(this.totalPriceGross, lineItem8.totalPriceGross) &&
        Objects.equals(this.totalPriceTaxAmount, lineItem8.totalPriceTaxAmount) &&
        Objects.equals(this.totalPriceUnknown, lineItem8.totalPriceUnknown) &&
        Objects.equals(this.orderNumber, lineItem8.orderNumber) &&
        Objects.equals(this.orderConfirmationNumber, lineItem8.orderConfirmationNumber) &&
        Objects.equals(this.deliveryNoteNumber, lineItem8.deliveryNoteNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(posId, articleId, ean, description, quantity, unitOfMeasure, servicePeriod, orderDate, orderConfirmationDate, deliveryNoteDate, discount, additionalCost, taxRate, taxCode, unitPriceNet, unitPriceGross, unitPriceUnknown, priceUnit, totalPriceNet, totalPriceGross, totalPriceTaxAmount, totalPriceUnknown, orderNumber, orderConfirmationNumber, deliveryNoteNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LineItem8 {\n");
    
    sb.append("    posId: ").append(toIndentedString(posId)).append("\n");
    sb.append("    articleId: ").append(toIndentedString(articleId)).append("\n");
    sb.append("    ean: ").append(toIndentedString(ean)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    unitOfMeasure: ").append(toIndentedString(unitOfMeasure)).append("\n");
    sb.append("    servicePeriod: ").append(toIndentedString(servicePeriod)).append("\n");
    sb.append("    orderDate: ").append(toIndentedString(orderDate)).append("\n");
    sb.append("    orderConfirmationDate: ").append(toIndentedString(orderConfirmationDate)).append("\n");
    sb.append("    deliveryNoteDate: ").append(toIndentedString(deliveryNoteDate)).append("\n");
    sb.append("    discount: ").append(toIndentedString(discount)).append("\n");
    sb.append("    additionalCost: ").append(toIndentedString(additionalCost)).append("\n");
    sb.append("    taxRate: ").append(toIndentedString(taxRate)).append("\n");
    sb.append("    taxCode: ").append(toIndentedString(taxCode)).append("\n");
    sb.append("    unitPriceNet: ").append(toIndentedString(unitPriceNet)).append("\n");
    sb.append("    unitPriceGross: ").append(toIndentedString(unitPriceGross)).append("\n");
    sb.append("    unitPriceUnknown: ").append(toIndentedString(unitPriceUnknown)).append("\n");
    sb.append("    priceUnit: ").append(toIndentedString(priceUnit)).append("\n");
    sb.append("    totalPriceNet: ").append(toIndentedString(totalPriceNet)).append("\n");
    sb.append("    totalPriceGross: ").append(toIndentedString(totalPriceGross)).append("\n");
    sb.append("    totalPriceTaxAmount: ").append(toIndentedString(totalPriceTaxAmount)).append("\n");
    sb.append("    totalPriceUnknown: ").append(toIndentedString(totalPriceUnknown)).append("\n");
    sb.append("    orderNumber: ").append(toIndentedString(orderNumber)).append("\n");
    sb.append("    orderConfirmationNumber: ").append(toIndentedString(orderConfirmationNumber)).append("\n");
    sb.append("    deliveryNoteNumber: ").append(toIndentedString(deliveryNoteNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
