/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsAdditionalCost;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsArticleId;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsDeliveryNoteNumber1;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsDescription;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsEan;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsGrossAmount;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsOrderConfirmationNumber1;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsOrderNumber1;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsPosId;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsQuantity;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsTaxCode;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsTaxRate;
import com.axonivy.connector.idp.connector.model.DocumentsdocumentIdextractionsUnitOfMeasure;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * LineItem19
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class LineItem19 {
  @JsonProperty("pos_id")
  private DocumentsdocumentIdextractionsPosId posId = null;

  @JsonProperty("article_id")
  private DocumentsdocumentIdextractionsArticleId articleId = null;

  @JsonProperty("ean")
  private DocumentsdocumentIdextractionsEan ean = null;

  @JsonProperty("description")
  private DocumentsdocumentIdextractionsDescription description = null;

  @JsonProperty("quantity")
  private DocumentsdocumentIdextractionsQuantity quantity = null;

  @JsonProperty("unit_of_measure")
  private DocumentsdocumentIdextractionsUnitOfMeasure unitOfMeasure = null;

  @JsonProperty("service_period")
  private AnyOfLineItem19ServicePeriod servicePeriod = null;

  @JsonProperty("discount")
  private DocumentsdocumentIdextractionsAdditionalCost discount = null;

  @JsonProperty("additional_cost")
  private DocumentsdocumentIdextractionsAdditionalCost additionalCost = null;

  @JsonProperty("tax_rate")
  private DocumentsdocumentIdextractionsTaxRate taxRate = null;

  @JsonProperty("tax_code")
  private DocumentsdocumentIdextractionsTaxCode taxCode = null;

  @JsonProperty("unit_price")
  private DocumentsdocumentIdextractionsQuantity unitPrice = null;

  @JsonProperty("total_price")
  private DocumentsdocumentIdextractionsGrossAmount totalPrice = null;

  @JsonProperty("order_number")
  private DocumentsdocumentIdextractionsOrderNumber1 orderNumber = null;

  @JsonProperty("order_confirmation_number")
  private DocumentsdocumentIdextractionsOrderConfirmationNumber1 orderConfirmationNumber = null;

  @JsonProperty("delivery_note_number")
  private DocumentsdocumentIdextractionsDeliveryNoteNumber1 deliveryNoteNumber = null;

  public LineItem19 posId(DocumentsdocumentIdextractionsPosId posId) {
    this.posId = posId;
    return this;
  }

   /**
   * Get posId
   * @return posId
  **/
  public DocumentsdocumentIdextractionsPosId getPosId() {
    return posId;
  }

  public void setPosId(DocumentsdocumentIdextractionsPosId posId) {
    this.posId = posId;
  }

  public LineItem19 articleId(DocumentsdocumentIdextractionsArticleId articleId) {
    this.articleId = articleId;
    return this;
  }

   /**
   * Get articleId
   * @return articleId
  **/
  public DocumentsdocumentIdextractionsArticleId getArticleId() {
    return articleId;
  }

  public void setArticleId(DocumentsdocumentIdextractionsArticleId articleId) {
    this.articleId = articleId;
  }

  public LineItem19 ean(DocumentsdocumentIdextractionsEan ean) {
    this.ean = ean;
    return this;
  }

   /**
   * Get ean
   * @return ean
  **/
  public DocumentsdocumentIdextractionsEan getEan() {
    return ean;
  }

  public void setEan(DocumentsdocumentIdextractionsEan ean) {
    this.ean = ean;
  }

  public LineItem19 description(DocumentsdocumentIdextractionsDescription description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public DocumentsdocumentIdextractionsDescription getDescription() {
    return description;
  }

  public void setDescription(DocumentsdocumentIdextractionsDescription description) {
    this.description = description;
  }

  public LineItem19 quantity(DocumentsdocumentIdextractionsQuantity quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  public DocumentsdocumentIdextractionsQuantity getQuantity() {
    return quantity;
  }

  public void setQuantity(DocumentsdocumentIdextractionsQuantity quantity) {
    this.quantity = quantity;
  }

  public LineItem19 unitOfMeasure(DocumentsdocumentIdextractionsUnitOfMeasure unitOfMeasure) {
    this.unitOfMeasure = unitOfMeasure;
    return this;
  }

   /**
   * Get unitOfMeasure
   * @return unitOfMeasure
  **/
  public DocumentsdocumentIdextractionsUnitOfMeasure getUnitOfMeasure() {
    return unitOfMeasure;
  }

  public void setUnitOfMeasure(DocumentsdocumentIdextractionsUnitOfMeasure unitOfMeasure) {
    this.unitOfMeasure = unitOfMeasure;
  }

  public LineItem19 servicePeriod(AnyOfLineItem19ServicePeriod servicePeriod) {
    this.servicePeriod = servicePeriod;
    return this;
  }

   /**
   * Get servicePeriod
   * @return servicePeriod
  **/
  public AnyOfLineItem19ServicePeriod getServicePeriod() {
    return servicePeriod;
  }

  public void setServicePeriod(AnyOfLineItem19ServicePeriod servicePeriod) {
    this.servicePeriod = servicePeriod;
  }

  public LineItem19 discount(DocumentsdocumentIdextractionsAdditionalCost discount) {
    this.discount = discount;
    return this;
  }

   /**
   * Get discount
   * @return discount
  **/
  public DocumentsdocumentIdextractionsAdditionalCost getDiscount() {
    return discount;
  }

  public void setDiscount(DocumentsdocumentIdextractionsAdditionalCost discount) {
    this.discount = discount;
  }

  public LineItem19 additionalCost(DocumentsdocumentIdextractionsAdditionalCost additionalCost) {
    this.additionalCost = additionalCost;
    return this;
  }

   /**
   * Get additionalCost
   * @return additionalCost
  **/
  public DocumentsdocumentIdextractionsAdditionalCost getAdditionalCost() {
    return additionalCost;
  }

  public void setAdditionalCost(DocumentsdocumentIdextractionsAdditionalCost additionalCost) {
    this.additionalCost = additionalCost;
  }

  public LineItem19 taxRate(DocumentsdocumentIdextractionsTaxRate taxRate) {
    this.taxRate = taxRate;
    return this;
  }

   /**
   * Get taxRate
   * @return taxRate
  **/
  public DocumentsdocumentIdextractionsTaxRate getTaxRate() {
    return taxRate;
  }

  public void setTaxRate(DocumentsdocumentIdextractionsTaxRate taxRate) {
    this.taxRate = taxRate;
  }

  public LineItem19 taxCode(DocumentsdocumentIdextractionsTaxCode taxCode) {
    this.taxCode = taxCode;
    return this;
  }

   /**
   * Get taxCode
   * @return taxCode
  **/
  public DocumentsdocumentIdextractionsTaxCode getTaxCode() {
    return taxCode;
  }

  public void setTaxCode(DocumentsdocumentIdextractionsTaxCode taxCode) {
    this.taxCode = taxCode;
  }

  public LineItem19 unitPrice(DocumentsdocumentIdextractionsQuantity unitPrice) {
    this.unitPrice = unitPrice;
    return this;
  }

   /**
   * Get unitPrice
   * @return unitPrice
  **/
  public DocumentsdocumentIdextractionsQuantity getUnitPrice() {
    return unitPrice;
  }

  public void setUnitPrice(DocumentsdocumentIdextractionsQuantity unitPrice) {
    this.unitPrice = unitPrice;
  }

  public LineItem19 totalPrice(DocumentsdocumentIdextractionsGrossAmount totalPrice) {
    this.totalPrice = totalPrice;
    return this;
  }

   /**
   * Get totalPrice
   * @return totalPrice
  **/
  public DocumentsdocumentIdextractionsGrossAmount getTotalPrice() {
    return totalPrice;
  }

  public void setTotalPrice(DocumentsdocumentIdextractionsGrossAmount totalPrice) {
    this.totalPrice = totalPrice;
  }

  public LineItem19 orderNumber(DocumentsdocumentIdextractionsOrderNumber1 orderNumber) {
    this.orderNumber = orderNumber;
    return this;
  }

   /**
   * Get orderNumber
   * @return orderNumber
  **/
  public DocumentsdocumentIdextractionsOrderNumber1 getOrderNumber() {
    return orderNumber;
  }

  public void setOrderNumber(DocumentsdocumentIdextractionsOrderNumber1 orderNumber) {
    this.orderNumber = orderNumber;
  }

  public LineItem19 orderConfirmationNumber(DocumentsdocumentIdextractionsOrderConfirmationNumber1 orderConfirmationNumber) {
    this.orderConfirmationNumber = orderConfirmationNumber;
    return this;
  }

   /**
   * Get orderConfirmationNumber
   * @return orderConfirmationNumber
  **/
  public DocumentsdocumentIdextractionsOrderConfirmationNumber1 getOrderConfirmationNumber() {
    return orderConfirmationNumber;
  }

  public void setOrderConfirmationNumber(DocumentsdocumentIdextractionsOrderConfirmationNumber1 orderConfirmationNumber) {
    this.orderConfirmationNumber = orderConfirmationNumber;
  }

  public LineItem19 deliveryNoteNumber(DocumentsdocumentIdextractionsDeliveryNoteNumber1 deliveryNoteNumber) {
    this.deliveryNoteNumber = deliveryNoteNumber;
    return this;
  }

   /**
   * Get deliveryNoteNumber
   * @return deliveryNoteNumber
  **/
  public DocumentsdocumentIdextractionsDeliveryNoteNumber1 getDeliveryNoteNumber() {
    return deliveryNoteNumber;
  }

  public void setDeliveryNoteNumber(DocumentsdocumentIdextractionsDeliveryNoteNumber1 deliveryNoteNumber) {
    this.deliveryNoteNumber = deliveryNoteNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LineItem19 lineItem19 = (LineItem19) o;
    return Objects.equals(this.posId, lineItem19.posId) &&
        Objects.equals(this.articleId, lineItem19.articleId) &&
        Objects.equals(this.ean, lineItem19.ean) &&
        Objects.equals(this.description, lineItem19.description) &&
        Objects.equals(this.quantity, lineItem19.quantity) &&
        Objects.equals(this.unitOfMeasure, lineItem19.unitOfMeasure) &&
        Objects.equals(this.servicePeriod, lineItem19.servicePeriod) &&
        Objects.equals(this.discount, lineItem19.discount) &&
        Objects.equals(this.additionalCost, lineItem19.additionalCost) &&
        Objects.equals(this.taxRate, lineItem19.taxRate) &&
        Objects.equals(this.taxCode, lineItem19.taxCode) &&
        Objects.equals(this.unitPrice, lineItem19.unitPrice) &&
        Objects.equals(this.totalPrice, lineItem19.totalPrice) &&
        Objects.equals(this.orderNumber, lineItem19.orderNumber) &&
        Objects.equals(this.orderConfirmationNumber, lineItem19.orderConfirmationNumber) &&
        Objects.equals(this.deliveryNoteNumber, lineItem19.deliveryNoteNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(posId, articleId, ean, description, quantity, unitOfMeasure, servicePeriod, discount, additionalCost, taxRate, taxCode, unitPrice, totalPrice, orderNumber, orderConfirmationNumber, deliveryNoteNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LineItem19 {\n");
    
    sb.append("    posId: ").append(toIndentedString(posId)).append("\n");
    sb.append("    articleId: ").append(toIndentedString(articleId)).append("\n");
    sb.append("    ean: ").append(toIndentedString(ean)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    unitOfMeasure: ").append(toIndentedString(unitOfMeasure)).append("\n");
    sb.append("    servicePeriod: ").append(toIndentedString(servicePeriod)).append("\n");
    sb.append("    discount: ").append(toIndentedString(discount)).append("\n");
    sb.append("    additionalCost: ").append(toIndentedString(additionalCost)).append("\n");
    sb.append("    taxRate: ").append(toIndentedString(taxRate)).append("\n");
    sb.append("    taxCode: ").append(toIndentedString(taxCode)).append("\n");
    sb.append("    unitPrice: ").append(toIndentedString(unitPrice)).append("\n");
    sb.append("    totalPrice: ").append(toIndentedString(totalPrice)).append("\n");
    sb.append("    orderNumber: ").append(toIndentedString(orderNumber)).append("\n");
    sb.append("    orderConfirmationNumber: ").append(toIndentedString(orderConfirmationNumber)).append("\n");
    sb.append("    deliveryNoteNumber: ").append(toIndentedString(deliveryNoteNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
