/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.InvoiceAdditionalCost;
import com.axonivy.connector.idp.connector.model.InvoiceArticleId;
import com.axonivy.connector.idp.connector.model.InvoiceDeliveryNoteNumber;
import com.axonivy.connector.idp.connector.model.InvoiceDescription;
import com.axonivy.connector.idp.connector.model.InvoiceEan;
import com.axonivy.connector.idp.connector.model.InvoiceGrossAmount;
import com.axonivy.connector.idp.connector.model.InvoiceOrderConfirmationNumber;
import com.axonivy.connector.idp.connector.model.InvoiceOrderNumber;
import com.axonivy.connector.idp.connector.model.InvoicePosId;
import com.axonivy.connector.idp.connector.model.InvoiceQuantity;
import com.axonivy.connector.idp.connector.model.InvoiceTaxCode;
import com.axonivy.connector.idp.connector.model.InvoiceTaxRate;
import com.axonivy.connector.idp.connector.model.InvoiceUnitOfMeasure;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * LineItem23
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class LineItem23 {
  @JsonProperty("pos_id")
  private InvoicePosId posId = null;

  @JsonProperty("article_id")
  private InvoiceArticleId articleId = null;

  @JsonProperty("ean")
  private InvoiceEan ean = null;

  @JsonProperty("description")
  private InvoiceDescription description = null;

  @JsonProperty("quantity")
  private InvoiceQuantity quantity = null;

  @JsonProperty("unit_of_measure")
  private InvoiceUnitOfMeasure unitOfMeasure = null;

  @JsonProperty("service_period")
  private AnyOfLineItem23ServicePeriod servicePeriod = null;

  @JsonProperty("discount")
  private InvoiceAdditionalCost discount = null;

  @JsonProperty("additional_cost")
  private InvoiceAdditionalCost additionalCost = null;

  @JsonProperty("tax_rate")
  private InvoiceTaxRate taxRate = null;

  @JsonProperty("tax_code")
  private InvoiceTaxCode taxCode = null;

  @JsonProperty("unit_price")
  private InvoiceQuantity unitPrice = null;

  @JsonProperty("total_price")
  private InvoiceGrossAmount totalPrice = null;

  @JsonProperty("order_number")
  private InvoiceOrderNumber orderNumber = null;

  @JsonProperty("order_confirmation_number")
  private InvoiceOrderConfirmationNumber orderConfirmationNumber = null;

  @JsonProperty("delivery_note_number")
  private InvoiceDeliveryNoteNumber deliveryNoteNumber = null;

  public LineItem23 posId(InvoicePosId posId) {
    this.posId = posId;
    return this;
  }

   /**
   * Get posId
   * @return posId
  **/
  public InvoicePosId getPosId() {
    return posId;
  }

  public void setPosId(InvoicePosId posId) {
    this.posId = posId;
  }

  public LineItem23 articleId(InvoiceArticleId articleId) {
    this.articleId = articleId;
    return this;
  }

   /**
   * Get articleId
   * @return articleId
  **/
  public InvoiceArticleId getArticleId() {
    return articleId;
  }

  public void setArticleId(InvoiceArticleId articleId) {
    this.articleId = articleId;
  }

  public LineItem23 ean(InvoiceEan ean) {
    this.ean = ean;
    return this;
  }

   /**
   * Get ean
   * @return ean
  **/
  public InvoiceEan getEan() {
    return ean;
  }

  public void setEan(InvoiceEan ean) {
    this.ean = ean;
  }

  public LineItem23 description(InvoiceDescription description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public InvoiceDescription getDescription() {
    return description;
  }

  public void setDescription(InvoiceDescription description) {
    this.description = description;
  }

  public LineItem23 quantity(InvoiceQuantity quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  public InvoiceQuantity getQuantity() {
    return quantity;
  }

  public void setQuantity(InvoiceQuantity quantity) {
    this.quantity = quantity;
  }

  public LineItem23 unitOfMeasure(InvoiceUnitOfMeasure unitOfMeasure) {
    this.unitOfMeasure = unitOfMeasure;
    return this;
  }

   /**
   * Get unitOfMeasure
   * @return unitOfMeasure
  **/
  public InvoiceUnitOfMeasure getUnitOfMeasure() {
    return unitOfMeasure;
  }

  public void setUnitOfMeasure(InvoiceUnitOfMeasure unitOfMeasure) {
    this.unitOfMeasure = unitOfMeasure;
  }

  public LineItem23 servicePeriod(AnyOfLineItem23ServicePeriod servicePeriod) {
    this.servicePeriod = servicePeriod;
    return this;
  }

   /**
   * Get servicePeriod
   * @return servicePeriod
  **/
  public AnyOfLineItem23ServicePeriod getServicePeriod() {
    return servicePeriod;
  }

  public void setServicePeriod(AnyOfLineItem23ServicePeriod servicePeriod) {
    this.servicePeriod = servicePeriod;
  }

  public LineItem23 discount(InvoiceAdditionalCost discount) {
    this.discount = discount;
    return this;
  }

   /**
   * Get discount
   * @return discount
  **/
  public InvoiceAdditionalCost getDiscount() {
    return discount;
  }

  public void setDiscount(InvoiceAdditionalCost discount) {
    this.discount = discount;
  }

  public LineItem23 additionalCost(InvoiceAdditionalCost additionalCost) {
    this.additionalCost = additionalCost;
    return this;
  }

   /**
   * Get additionalCost
   * @return additionalCost
  **/
  public InvoiceAdditionalCost getAdditionalCost() {
    return additionalCost;
  }

  public void setAdditionalCost(InvoiceAdditionalCost additionalCost) {
    this.additionalCost = additionalCost;
  }

  public LineItem23 taxRate(InvoiceTaxRate taxRate) {
    this.taxRate = taxRate;
    return this;
  }

   /**
   * Get taxRate
   * @return taxRate
  **/
  public InvoiceTaxRate getTaxRate() {
    return taxRate;
  }

  public void setTaxRate(InvoiceTaxRate taxRate) {
    this.taxRate = taxRate;
  }

  public LineItem23 taxCode(InvoiceTaxCode taxCode) {
    this.taxCode = taxCode;
    return this;
  }

   /**
   * Get taxCode
   * @return taxCode
  **/
  public InvoiceTaxCode getTaxCode() {
    return taxCode;
  }

  public void setTaxCode(InvoiceTaxCode taxCode) {
    this.taxCode = taxCode;
  }

  public LineItem23 unitPrice(InvoiceQuantity unitPrice) {
    this.unitPrice = unitPrice;
    return this;
  }

   /**
   * Get unitPrice
   * @return unitPrice
  **/
  public InvoiceQuantity getUnitPrice() {
    return unitPrice;
  }

  public void setUnitPrice(InvoiceQuantity unitPrice) {
    this.unitPrice = unitPrice;
  }

  public LineItem23 totalPrice(InvoiceGrossAmount totalPrice) {
    this.totalPrice = totalPrice;
    return this;
  }

   /**
   * Get totalPrice
   * @return totalPrice
  **/
  public InvoiceGrossAmount getTotalPrice() {
    return totalPrice;
  }

  public void setTotalPrice(InvoiceGrossAmount totalPrice) {
    this.totalPrice = totalPrice;
  }

  public LineItem23 orderNumber(InvoiceOrderNumber orderNumber) {
    this.orderNumber = orderNumber;
    return this;
  }

   /**
   * Get orderNumber
   * @return orderNumber
  **/
  public InvoiceOrderNumber getOrderNumber() {
    return orderNumber;
  }

  public void setOrderNumber(InvoiceOrderNumber orderNumber) {
    this.orderNumber = orderNumber;
  }

  public LineItem23 orderConfirmationNumber(InvoiceOrderConfirmationNumber orderConfirmationNumber) {
    this.orderConfirmationNumber = orderConfirmationNumber;
    return this;
  }

   /**
   * Get orderConfirmationNumber
   * @return orderConfirmationNumber
  **/
  public InvoiceOrderConfirmationNumber getOrderConfirmationNumber() {
    return orderConfirmationNumber;
  }

  public void setOrderConfirmationNumber(InvoiceOrderConfirmationNumber orderConfirmationNumber) {
    this.orderConfirmationNumber = orderConfirmationNumber;
  }

  public LineItem23 deliveryNoteNumber(InvoiceDeliveryNoteNumber deliveryNoteNumber) {
    this.deliveryNoteNumber = deliveryNoteNumber;
    return this;
  }

   /**
   * Get deliveryNoteNumber
   * @return deliveryNoteNumber
  **/
  public InvoiceDeliveryNoteNumber getDeliveryNoteNumber() {
    return deliveryNoteNumber;
  }

  public void setDeliveryNoteNumber(InvoiceDeliveryNoteNumber deliveryNoteNumber) {
    this.deliveryNoteNumber = deliveryNoteNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LineItem23 lineItem23 = (LineItem23) o;
    return Objects.equals(this.posId, lineItem23.posId) &&
        Objects.equals(this.articleId, lineItem23.articleId) &&
        Objects.equals(this.ean, lineItem23.ean) &&
        Objects.equals(this.description, lineItem23.description) &&
        Objects.equals(this.quantity, lineItem23.quantity) &&
        Objects.equals(this.unitOfMeasure, lineItem23.unitOfMeasure) &&
        Objects.equals(this.servicePeriod, lineItem23.servicePeriod) &&
        Objects.equals(this.discount, lineItem23.discount) &&
        Objects.equals(this.additionalCost, lineItem23.additionalCost) &&
        Objects.equals(this.taxRate, lineItem23.taxRate) &&
        Objects.equals(this.taxCode, lineItem23.taxCode) &&
        Objects.equals(this.unitPrice, lineItem23.unitPrice) &&
        Objects.equals(this.totalPrice, lineItem23.totalPrice) &&
        Objects.equals(this.orderNumber, lineItem23.orderNumber) &&
        Objects.equals(this.orderConfirmationNumber, lineItem23.orderConfirmationNumber) &&
        Objects.equals(this.deliveryNoteNumber, lineItem23.deliveryNoteNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(posId, articleId, ean, description, quantity, unitOfMeasure, servicePeriod, discount, additionalCost, taxRate, taxCode, unitPrice, totalPrice, orderNumber, orderConfirmationNumber, deliveryNoteNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LineItem23 {\n");
    
    sb.append("    posId: ").append(toIndentedString(posId)).append("\n");
    sb.append("    articleId: ").append(toIndentedString(articleId)).append("\n");
    sb.append("    ean: ").append(toIndentedString(ean)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    unitOfMeasure: ").append(toIndentedString(unitOfMeasure)).append("\n");
    sb.append("    servicePeriod: ").append(toIndentedString(servicePeriod)).append("\n");
    sb.append("    discount: ").append(toIndentedString(discount)).append("\n");
    sb.append("    additionalCost: ").append(toIndentedString(additionalCost)).append("\n");
    sb.append("    taxRate: ").append(toIndentedString(taxRate)).append("\n");
    sb.append("    taxCode: ").append(toIndentedString(taxCode)).append("\n");
    sb.append("    unitPrice: ").append(toIndentedString(unitPrice)).append("\n");
    sb.append("    totalPrice: ").append(toIndentedString(totalPrice)).append("\n");
    sb.append("    orderNumber: ").append(toIndentedString(orderNumber)).append("\n");
    sb.append("    orderConfirmationNumber: ").append(toIndentedString(orderConfirmationNumber)).append("\n");
    sb.append("    deliveryNoteNumber: ").append(toIndentedString(deliveryNoteNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
