/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.Condition1;
import com.axonivy.connector.idp.connector.model.ConditionHeader1;
import com.axonivy.connector.idp.connector.model.Debtor1;
import com.axonivy.connector.idp.connector.model.Loan1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * LoanAgreement
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class LoanAgreement {
  /**
   * Gets or Sets schemaVersion
   */
  public enum SchemaVersionEnum {
    NUMBER_1(1);

    private Integer value;

    SchemaVersionEnum(Integer value) {
      this.value = value;
    }
    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SchemaVersionEnum fromValue(Integer input) {
      for (SchemaVersionEnum b : SchemaVersionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("schema_version")
  private SchemaVersionEnum schemaVersion = SchemaVersionEnum.NUMBER_1;

  /**
   * Gets or Sets documentType
   */
  public enum DocumentTypeEnum {
    LOAN_AGREEMENT("loan_agreement");

    private String value;

    DocumentTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static DocumentTypeEnum fromValue(String input) {
      for (DocumentTypeEnum b : DocumentTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("document_type")
  private DocumentTypeEnum documentType = null;

  @JsonProperty("debtor")
  private Debtor1 debtor = null;

  @JsonProperty("loan")
  private Loan1 loan = null;

  @JsonProperty("condition_header")
  private ConditionHeader1 conditionHeader = null;

  @JsonProperty("condition")
  private Condition1 condition = null;

  public LoanAgreement schemaVersion(SchemaVersionEnum schemaVersion) {
    this.schemaVersion = schemaVersion;
    return this;
  }

   /**
   * Get schemaVersion
   * @return schemaVersion
  **/
  public SchemaVersionEnum getSchemaVersion() {
    return schemaVersion;
  }

  public void setSchemaVersion(SchemaVersionEnum schemaVersion) {
    this.schemaVersion = schemaVersion;
  }

  public LoanAgreement documentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
    return this;
  }

   /**
   * Get documentType
   * @return documentType
  **/
  public DocumentTypeEnum getDocumentType() {
    return documentType;
  }

  public void setDocumentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
  }

  public LoanAgreement debtor(Debtor1 debtor) {
    this.debtor = debtor;
    return this;
  }

   /**
   * Get debtor
   * @return debtor
  **/
  public Debtor1 getDebtor() {
    return debtor;
  }

  public void setDebtor(Debtor1 debtor) {
    this.debtor = debtor;
  }

  public LoanAgreement loan(Loan1 loan) {
    this.loan = loan;
    return this;
  }

   /**
   * Get loan
   * @return loan
  **/
  public Loan1 getLoan() {
    return loan;
  }

  public void setLoan(Loan1 loan) {
    this.loan = loan;
  }

  public LoanAgreement conditionHeader(ConditionHeader1 conditionHeader) {
    this.conditionHeader = conditionHeader;
    return this;
  }

   /**
   * Get conditionHeader
   * @return conditionHeader
  **/
  public ConditionHeader1 getConditionHeader() {
    return conditionHeader;
  }

  public void setConditionHeader(ConditionHeader1 conditionHeader) {
    this.conditionHeader = conditionHeader;
  }

  public LoanAgreement condition(Condition1 condition) {
    this.condition = condition;
    return this;
  }

   /**
   * Get condition
   * @return condition
  **/
  public Condition1 getCondition() {
    return condition;
  }

  public void setCondition(Condition1 condition) {
    this.condition = condition;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoanAgreement loanAgreement = (LoanAgreement) o;
    return Objects.equals(this.schemaVersion, loanAgreement.schemaVersion) &&
        Objects.equals(this.documentType, loanAgreement.documentType) &&
        Objects.equals(this.debtor, loanAgreement.debtor) &&
        Objects.equals(this.loan, loanAgreement.loan) &&
        Objects.equals(this.conditionHeader, loanAgreement.conditionHeader) &&
        Objects.equals(this.condition, loanAgreement.condition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(schemaVersion, documentType, debtor, loan, conditionHeader, condition);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoanAgreement {\n");
    
    sb.append("    schemaVersion: ").append(toIndentedString(schemaVersion)).append("\n");
    sb.append("    documentType: ").append(toIndentedString(documentType)).append("\n");
    sb.append("    debtor: ").append(toIndentedString(debtor)).append("\n");
    sb.append("    loan: ").append(toIndentedString(loan)).append("\n");
    sb.append("    conditionHeader: ").append(toIndentedString(conditionHeader)).append("\n");
    sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
