/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.BBox1;
import com.axonivy.connector.idp.connector.model.PageTransformation1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * PageWithTransformations
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class PageWithTransformations {
  @JsonProperty("line_items")
  private List<List<Integer>> lineItems = new ArrayList<>();

  @JsonProperty("width")
  private Integer width = null;

  @JsonProperty("height")
  private Integer height = null;

  @JsonProperty("bboxes")
  private List<BBox1> bboxes = new ArrayList<>();

  @JsonProperty("transformation")
  private PageTransformation1 transformation = null;

  public PageWithTransformations lineItems(List<List<Integer>> lineItems) {
    this.lineItems = lineItems;
    return this;
  }

  public PageWithTransformations addLineItemsItem(List<Integer> lineItemsItem) {
    this.lineItems.add(lineItemsItem);
    return this;
  }

   /**
   * A list of line items, where each line item is a list of references to bounding boxes.
   * @return lineItems
  **/
  public List<List<Integer>> getLineItems() {
    return lineItems;
  }

  public void setLineItems(List<List<Integer>> lineItems) {
    this.lineItems = lineItems;
  }

  public PageWithTransformations width(Integer width) {
    this.width = width;
    return this;
  }

   /**
   * Page width.
   * @return width
  **/
  public Integer getWidth() {
    return width;
  }

  public void setWidth(Integer width) {
    this.width = width;
  }

  public PageWithTransformations height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * Page height.
   * @return height
  **/
  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }

  public PageWithTransformations bboxes(List<BBox1> bboxes) {
    this.bboxes = bboxes;
    return this;
  }

  public PageWithTransformations addBboxesItem(BBox1 bboxesItem) {
    this.bboxes.add(bboxesItem);
    return this;
  }

   /**
   * A list of boxes that each surrounds one of the detected words.
   * @return bboxes
  **/
  public List<BBox1> getBboxes() {
    return bboxes;
  }

  public void setBboxes(List<BBox1> bboxes) {
    this.bboxes = bboxes;
  }

  public PageWithTransformations transformation(PageTransformation1 transformation) {
    this.transformation = transformation;
    return this;
  }

   /**
   * Get transformation
   * @return transformation
  **/
  public PageTransformation1 getTransformation() {
    return transformation;
  }

  public void setTransformation(PageTransformation1 transformation) {
    this.transformation = transformation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PageWithTransformations pageWithTransformations = (PageWithTransformations) o;
    return Objects.equals(this.lineItems, pageWithTransformations.lineItems) &&
        Objects.equals(this.width, pageWithTransformations.width) &&
        Objects.equals(this.height, pageWithTransformations.height) &&
        Objects.equals(this.bboxes, pageWithTransformations.bboxes) &&
        Objects.equals(this.transformation, pageWithTransformations.transformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lineItems, width, height, bboxes, transformation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PageWithTransformations {\n");
    
    sb.append("    lineItems: ").append(toIndentedString(lineItems)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    bboxes: ").append(toIndentedString(bboxes)).append("\n");
    sb.append("    transformation: ").append(toIndentedString(transformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
