/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.InsuranceHolder1;
import com.axonivy.connector.idp.connector.model.PersonTariffs1;
import com.axonivy.connector.idp.connector.model.StringExtraction1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * PrivateHealthInsurance
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class PrivateHealthInsurance {
  /**
   * Gets or Sets schemaVersion
   */
  public enum SchemaVersionEnum {
    NUMBER_1(1);

    private Integer value;

    SchemaVersionEnum(Integer value) {
      this.value = value;
    }
    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SchemaVersionEnum fromValue(Integer input) {
      for (SchemaVersionEnum b : SchemaVersionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("schema_version")
  private SchemaVersionEnum schemaVersion = SchemaVersionEnum.NUMBER_1;

  /**
   * Gets or Sets documentType
   */
  public enum DocumentTypeEnum {
    PRIVATE_HEALTH_INSURANCE("private_health_insurance");

    private String value;

    DocumentTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static DocumentTypeEnum fromValue(String input) {
      for (DocumentTypeEnum b : DocumentTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("document_type")
  private DocumentTypeEnum documentType = null;

  @JsonProperty("insurance_company")
  private StringExtraction1 insuranceCompany = null;

  @JsonProperty("contract_number")
  private StringExtraction1 contractNumber = null;

  @JsonProperty("insurance_holder")
  private InsuranceHolder1 insuranceHolder = null;

  @JsonProperty("insured_persons")
  private List<StringExtraction1> insuredPersons = new ArrayList<>();

  @JsonProperty("person_tariffs")
  private List<PersonTariffs1> personTariffs = new ArrayList<>();

  public PrivateHealthInsurance schemaVersion(SchemaVersionEnum schemaVersion) {
    this.schemaVersion = schemaVersion;
    return this;
  }

   /**
   * Get schemaVersion
   * @return schemaVersion
  **/
  public SchemaVersionEnum getSchemaVersion() {
    return schemaVersion;
  }

  public void setSchemaVersion(SchemaVersionEnum schemaVersion) {
    this.schemaVersion = schemaVersion;
  }

  public PrivateHealthInsurance documentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
    return this;
  }

   /**
   * Get documentType
   * @return documentType
  **/
  public DocumentTypeEnum getDocumentType() {
    return documentType;
  }

  public void setDocumentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
  }

  public PrivateHealthInsurance insuranceCompany(StringExtraction1 insuranceCompany) {
    this.insuranceCompany = insuranceCompany;
    return this;
  }

   /**
   * Get insuranceCompany
   * @return insuranceCompany
  **/
  public StringExtraction1 getInsuranceCompany() {
    return insuranceCompany;
  }

  public void setInsuranceCompany(StringExtraction1 insuranceCompany) {
    this.insuranceCompany = insuranceCompany;
  }

  public PrivateHealthInsurance contractNumber(StringExtraction1 contractNumber) {
    this.contractNumber = contractNumber;
    return this;
  }

   /**
   * Get contractNumber
   * @return contractNumber
  **/
  public StringExtraction1 getContractNumber() {
    return contractNumber;
  }

  public void setContractNumber(StringExtraction1 contractNumber) {
    this.contractNumber = contractNumber;
  }

  public PrivateHealthInsurance insuranceHolder(InsuranceHolder1 insuranceHolder) {
    this.insuranceHolder = insuranceHolder;
    return this;
  }

   /**
   * Get insuranceHolder
   * @return insuranceHolder
  **/
  public InsuranceHolder1 getInsuranceHolder() {
    return insuranceHolder;
  }

  public void setInsuranceHolder(InsuranceHolder1 insuranceHolder) {
    this.insuranceHolder = insuranceHolder;
  }

  public PrivateHealthInsurance insuredPersons(List<StringExtraction1> insuredPersons) {
    this.insuredPersons = insuredPersons;
    return this;
  }

  public PrivateHealthInsurance addInsuredPersonsItem(StringExtraction1 insuredPersonsItem) {
    this.insuredPersons.add(insuredPersonsItem);
    return this;
  }

   /**
   * Get insuredPersons
   * @return insuredPersons
  **/
  public List<StringExtraction1> getInsuredPersons() {
    return insuredPersons;
  }

  public void setInsuredPersons(List<StringExtraction1> insuredPersons) {
    this.insuredPersons = insuredPersons;
  }

  public PrivateHealthInsurance personTariffs(List<PersonTariffs1> personTariffs) {
    this.personTariffs = personTariffs;
    return this;
  }

  public PrivateHealthInsurance addPersonTariffsItem(PersonTariffs1 personTariffsItem) {
    this.personTariffs.add(personTariffsItem);
    return this;
  }

   /**
   * Get personTariffs
   * @return personTariffs
  **/
  public List<PersonTariffs1> getPersonTariffs() {
    return personTariffs;
  }

  public void setPersonTariffs(List<PersonTariffs1> personTariffs) {
    this.personTariffs = personTariffs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PrivateHealthInsurance privateHealthInsurance = (PrivateHealthInsurance) o;
    return Objects.equals(this.schemaVersion, privateHealthInsurance.schemaVersion) &&
        Objects.equals(this.documentType, privateHealthInsurance.documentType) &&
        Objects.equals(this.insuranceCompany, privateHealthInsurance.insuranceCompany) &&
        Objects.equals(this.contractNumber, privateHealthInsurance.contractNumber) &&
        Objects.equals(this.insuranceHolder, privateHealthInsurance.insuranceHolder) &&
        Objects.equals(this.insuredPersons, privateHealthInsurance.insuredPersons) &&
        Objects.equals(this.personTariffs, privateHealthInsurance.personTariffs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(schemaVersion, documentType, insuranceCompany, contractNumber, insuranceHolder, insuredPersons, personTariffs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrivateHealthInsurance {\n");
    
    sb.append("    schemaVersion: ").append(toIndentedString(schemaVersion)).append("\n");
    sb.append("    documentType: ").append(toIndentedString(documentType)).append("\n");
    sb.append("    insuranceCompany: ").append(toIndentedString(insuranceCompany)).append("\n");
    sb.append("    contractNumber: ").append(toIndentedString(contractNumber)).append("\n");
    sb.append("    insuranceHolder: ").append(toIndentedString(insuranceHolder)).append("\n");
    sb.append("    insuredPersons: ").append(toIndentedString(insuredPersons)).append("\n");
    sb.append("    personTariffs: ").append(toIndentedString(personTariffs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
