/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.BilledParty1;
import com.axonivy.connector.idp.connector.model.Buyer1;
import com.axonivy.connector.idp.connector.model.Carrier1;
import com.axonivy.connector.idp.connector.model.ContactPerson1;
import com.axonivy.connector.idp.connector.model.CurrencyExtractionOptions1;
import com.axonivy.connector.idp.connector.model.DateExtractionOptions1;
import com.axonivy.connector.idp.connector.model.LineItem18;
import com.axonivy.connector.idp.connector.model.PaymentTotalsOptions1;
import com.axonivy.connector.idp.connector.model.RecipientParty1;
import com.axonivy.connector.idp.connector.model.Seller1;
import com.axonivy.connector.idp.connector.model.StringExtractionOptions1;
import com.axonivy.connector.idp.connector.model.TaxCalculation2;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * PurchaseOrder
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class PurchaseOrder {
  /**
   * Gets or Sets schemaVersion
   */
  public enum SchemaVersionEnum {
    NUMBER_1(1);

    private Integer value;

    SchemaVersionEnum(Integer value) {
      this.value = value;
    }
    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SchemaVersionEnum fromValue(Integer input) {
      for (SchemaVersionEnum b : SchemaVersionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("schema_version")
  private SchemaVersionEnum schemaVersion = SchemaVersionEnum.NUMBER_1;

  /**
   * Gets or Sets documentType
   */
  public enum DocumentTypeEnum {
    PURCHASE_ORDER("purchase_order");

    private String value;

    DocumentTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static DocumentTypeEnum fromValue(String input) {
      for (DocumentTypeEnum b : DocumentTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("document_type")
  private DocumentTypeEnum documentType = null;

  @JsonProperty("date")
  private DateExtractionOptions1 date = null;

  @JsonProperty("order_number")
  private StringExtractionOptions1 orderNumber = null;

  @JsonProperty("reference_number")
  private StringExtractionOptions1 referenceNumber = null;

  @JsonProperty("seller")
  private Seller1 seller = null;

  @JsonProperty("buyer")
  private Buyer1 buyer = null;

  @JsonProperty("buyer_contacts")
  private List<ContactPerson1> buyerContacts = new ArrayList<>();

  @JsonProperty("billed_parties")
  private List<BilledParty1> billedParties = new ArrayList<>();

  @JsonProperty("recipient_parties")
  private List<RecipientParty1> recipientParties = new ArrayList<>();

  @JsonProperty("benefit_recipient_parties")
  private List<RecipientParty1> benefitRecipientParties = new ArrayList<>();

  @JsonProperty("carriers")
  private List<Carrier1> carriers = new ArrayList<>();

  @JsonProperty("currency")
  private CurrencyExtractionOptions1 currency = null;

  @JsonProperty("tax_calculations")
  private List<TaxCalculation2> taxCalculations = new ArrayList<>();

  @JsonProperty("payment_totals")
  private PaymentTotalsOptions1 paymentTotals = null;

  @JsonProperty("payment_terms")
  private List<StringExtractionOptions1> paymentTerms = new ArrayList<>();

  @JsonProperty("delivery_terms")
  private List<StringExtractionOptions1> deliveryTerms = new ArrayList<>();

  @JsonProperty("delivery_date")
  private DateExtractionOptions1 deliveryDate = null;

  @JsonProperty("line_items")
  private List<LineItem18> lineItems = new ArrayList<>();

  @JsonProperty("top_notes")
  private StringExtractionOptions1 topNotes = null;

  @JsonProperty("bottom_notes")
  private StringExtractionOptions1 bottomNotes = null;

  public PurchaseOrder schemaVersion(SchemaVersionEnum schemaVersion) {
    this.schemaVersion = schemaVersion;
    return this;
  }

   /**
   * Get schemaVersion
   * @return schemaVersion
  **/
  public SchemaVersionEnum getSchemaVersion() {
    return schemaVersion;
  }

  public void setSchemaVersion(SchemaVersionEnum schemaVersion) {
    this.schemaVersion = schemaVersion;
  }

  public PurchaseOrder documentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
    return this;
  }

   /**
   * Get documentType
   * @return documentType
  **/
  public DocumentTypeEnum getDocumentType() {
    return documentType;
  }

  public void setDocumentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
  }

  public PurchaseOrder date(DateExtractionOptions1 date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  public DateExtractionOptions1 getDate() {
    return date;
  }

  public void setDate(DateExtractionOptions1 date) {
    this.date = date;
  }

  public PurchaseOrder orderNumber(StringExtractionOptions1 orderNumber) {
    this.orderNumber = orderNumber;
    return this;
  }

   /**
   * Get orderNumber
   * @return orderNumber
  **/
  public StringExtractionOptions1 getOrderNumber() {
    return orderNumber;
  }

  public void setOrderNumber(StringExtractionOptions1 orderNumber) {
    this.orderNumber = orderNumber;
  }

  public PurchaseOrder referenceNumber(StringExtractionOptions1 referenceNumber) {
    this.referenceNumber = referenceNumber;
    return this;
  }

   /**
   * Get referenceNumber
   * @return referenceNumber
  **/
  public StringExtractionOptions1 getReferenceNumber() {
    return referenceNumber;
  }

  public void setReferenceNumber(StringExtractionOptions1 referenceNumber) {
    this.referenceNumber = referenceNumber;
  }

  public PurchaseOrder seller(Seller1 seller) {
    this.seller = seller;
    return this;
  }

   /**
   * Get seller
   * @return seller
  **/
  public Seller1 getSeller() {
    return seller;
  }

  public void setSeller(Seller1 seller) {
    this.seller = seller;
  }

  public PurchaseOrder buyer(Buyer1 buyer) {
    this.buyer = buyer;
    return this;
  }

   /**
   * Get buyer
   * @return buyer
  **/
  public Buyer1 getBuyer() {
    return buyer;
  }

  public void setBuyer(Buyer1 buyer) {
    this.buyer = buyer;
  }

  public PurchaseOrder buyerContacts(List<ContactPerson1> buyerContacts) {
    this.buyerContacts = buyerContacts;
    return this;
  }

  public PurchaseOrder addBuyerContactsItem(ContactPerson1 buyerContactsItem) {
    this.buyerContacts.add(buyerContactsItem);
    return this;
  }

   /**
   * Get buyerContacts
   * @return buyerContacts
  **/
  public List<ContactPerson1> getBuyerContacts() {
    return buyerContacts;
  }

  public void setBuyerContacts(List<ContactPerson1> buyerContacts) {
    this.buyerContacts = buyerContacts;
  }

  public PurchaseOrder billedParties(List<BilledParty1> billedParties) {
    this.billedParties = billedParties;
    return this;
  }

  public PurchaseOrder addBilledPartiesItem(BilledParty1 billedPartiesItem) {
    this.billedParties.add(billedPartiesItem);
    return this;
  }

   /**
   * Get billedParties
   * @return billedParties
  **/
  public List<BilledParty1> getBilledParties() {
    return billedParties;
  }

  public void setBilledParties(List<BilledParty1> billedParties) {
    this.billedParties = billedParties;
  }

  public PurchaseOrder recipientParties(List<RecipientParty1> recipientParties) {
    this.recipientParties = recipientParties;
    return this;
  }

  public PurchaseOrder addRecipientPartiesItem(RecipientParty1 recipientPartiesItem) {
    this.recipientParties.add(recipientPartiesItem);
    return this;
  }

   /**
   * Get recipientParties
   * @return recipientParties
  **/
  public List<RecipientParty1> getRecipientParties() {
    return recipientParties;
  }

  public void setRecipientParties(List<RecipientParty1> recipientParties) {
    this.recipientParties = recipientParties;
  }

  public PurchaseOrder benefitRecipientParties(List<RecipientParty1> benefitRecipientParties) {
    this.benefitRecipientParties = benefitRecipientParties;
    return this;
  }

  public PurchaseOrder addBenefitRecipientPartiesItem(RecipientParty1 benefitRecipientPartiesItem) {
    this.benefitRecipientParties.add(benefitRecipientPartiesItem);
    return this;
  }

   /**
   * Get benefitRecipientParties
   * @return benefitRecipientParties
  **/
  public List<RecipientParty1> getBenefitRecipientParties() {
    return benefitRecipientParties;
  }

  public void setBenefitRecipientParties(List<RecipientParty1> benefitRecipientParties) {
    this.benefitRecipientParties = benefitRecipientParties;
  }

  public PurchaseOrder carriers(List<Carrier1> carriers) {
    this.carriers = carriers;
    return this;
  }

  public PurchaseOrder addCarriersItem(Carrier1 carriersItem) {
    this.carriers.add(carriersItem);
    return this;
  }

   /**
   * Get carriers
   * @return carriers
  **/
  public List<Carrier1> getCarriers() {
    return carriers;
  }

  public void setCarriers(List<Carrier1> carriers) {
    this.carriers = carriers;
  }

  public PurchaseOrder currency(CurrencyExtractionOptions1 currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  public CurrencyExtractionOptions1 getCurrency() {
    return currency;
  }

  public void setCurrency(CurrencyExtractionOptions1 currency) {
    this.currency = currency;
  }

  public PurchaseOrder taxCalculations(List<TaxCalculation2> taxCalculations) {
    this.taxCalculations = taxCalculations;
    return this;
  }

  public PurchaseOrder addTaxCalculationsItem(TaxCalculation2 taxCalculationsItem) {
    this.taxCalculations.add(taxCalculationsItem);
    return this;
  }

   /**
   * Get taxCalculations
   * @return taxCalculations
  **/
  public List<TaxCalculation2> getTaxCalculations() {
    return taxCalculations;
  }

  public void setTaxCalculations(List<TaxCalculation2> taxCalculations) {
    this.taxCalculations = taxCalculations;
  }

  public PurchaseOrder paymentTotals(PaymentTotalsOptions1 paymentTotals) {
    this.paymentTotals = paymentTotals;
    return this;
  }

   /**
   * Get paymentTotals
   * @return paymentTotals
  **/
  public PaymentTotalsOptions1 getPaymentTotals() {
    return paymentTotals;
  }

  public void setPaymentTotals(PaymentTotalsOptions1 paymentTotals) {
    this.paymentTotals = paymentTotals;
  }

  public PurchaseOrder paymentTerms(List<StringExtractionOptions1> paymentTerms) {
    this.paymentTerms = paymentTerms;
    return this;
  }

  public PurchaseOrder addPaymentTermsItem(StringExtractionOptions1 paymentTermsItem) {
    this.paymentTerms.add(paymentTermsItem);
    return this;
  }

   /**
   * Get paymentTerms
   * @return paymentTerms
  **/
  public List<StringExtractionOptions1> getPaymentTerms() {
    return paymentTerms;
  }

  public void setPaymentTerms(List<StringExtractionOptions1> paymentTerms) {
    this.paymentTerms = paymentTerms;
  }

  public PurchaseOrder deliveryTerms(List<StringExtractionOptions1> deliveryTerms) {
    this.deliveryTerms = deliveryTerms;
    return this;
  }

  public PurchaseOrder addDeliveryTermsItem(StringExtractionOptions1 deliveryTermsItem) {
    this.deliveryTerms.add(deliveryTermsItem);
    return this;
  }

   /**
   * Get deliveryTerms
   * @return deliveryTerms
  **/
  public List<StringExtractionOptions1> getDeliveryTerms() {
    return deliveryTerms;
  }

  public void setDeliveryTerms(List<StringExtractionOptions1> deliveryTerms) {
    this.deliveryTerms = deliveryTerms;
  }

  public PurchaseOrder deliveryDate(DateExtractionOptions1 deliveryDate) {
    this.deliveryDate = deliveryDate;
    return this;
  }

   /**
   * Get deliveryDate
   * @return deliveryDate
  **/
  public DateExtractionOptions1 getDeliveryDate() {
    return deliveryDate;
  }

  public void setDeliveryDate(DateExtractionOptions1 deliveryDate) {
    this.deliveryDate = deliveryDate;
  }

  public PurchaseOrder lineItems(List<LineItem18> lineItems) {
    this.lineItems = lineItems;
    return this;
  }

  public PurchaseOrder addLineItemsItem(LineItem18 lineItemsItem) {
    this.lineItems.add(lineItemsItem);
    return this;
  }

   /**
   * Get lineItems
   * @return lineItems
  **/
  public List<LineItem18> getLineItems() {
    return lineItems;
  }

  public void setLineItems(List<LineItem18> lineItems) {
    this.lineItems = lineItems;
  }

  public PurchaseOrder topNotes(StringExtractionOptions1 topNotes) {
    this.topNotes = topNotes;
    return this;
  }

   /**
   * Get topNotes
   * @return topNotes
  **/
  public StringExtractionOptions1 getTopNotes() {
    return topNotes;
  }

  public void setTopNotes(StringExtractionOptions1 topNotes) {
    this.topNotes = topNotes;
  }

  public PurchaseOrder bottomNotes(StringExtractionOptions1 bottomNotes) {
    this.bottomNotes = bottomNotes;
    return this;
  }

   /**
   * Get bottomNotes
   * @return bottomNotes
  **/
  public StringExtractionOptions1 getBottomNotes() {
    return bottomNotes;
  }

  public void setBottomNotes(StringExtractionOptions1 bottomNotes) {
    this.bottomNotes = bottomNotes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PurchaseOrder purchaseOrder = (PurchaseOrder) o;
    return Objects.equals(this.schemaVersion, purchaseOrder.schemaVersion) &&
        Objects.equals(this.documentType, purchaseOrder.documentType) &&
        Objects.equals(this.date, purchaseOrder.date) &&
        Objects.equals(this.orderNumber, purchaseOrder.orderNumber) &&
        Objects.equals(this.referenceNumber, purchaseOrder.referenceNumber) &&
        Objects.equals(this.seller, purchaseOrder.seller) &&
        Objects.equals(this.buyer, purchaseOrder.buyer) &&
        Objects.equals(this.buyerContacts, purchaseOrder.buyerContacts) &&
        Objects.equals(this.billedParties, purchaseOrder.billedParties) &&
        Objects.equals(this.recipientParties, purchaseOrder.recipientParties) &&
        Objects.equals(this.benefitRecipientParties, purchaseOrder.benefitRecipientParties) &&
        Objects.equals(this.carriers, purchaseOrder.carriers) &&
        Objects.equals(this.currency, purchaseOrder.currency) &&
        Objects.equals(this.taxCalculations, purchaseOrder.taxCalculations) &&
        Objects.equals(this.paymentTotals, purchaseOrder.paymentTotals) &&
        Objects.equals(this.paymentTerms, purchaseOrder.paymentTerms) &&
        Objects.equals(this.deliveryTerms, purchaseOrder.deliveryTerms) &&
        Objects.equals(this.deliveryDate, purchaseOrder.deliveryDate) &&
        Objects.equals(this.lineItems, purchaseOrder.lineItems) &&
        Objects.equals(this.topNotes, purchaseOrder.topNotes) &&
        Objects.equals(this.bottomNotes, purchaseOrder.bottomNotes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(schemaVersion, documentType, date, orderNumber, referenceNumber, seller, buyer, buyerContacts, billedParties, recipientParties, benefitRecipientParties, carriers, currency, taxCalculations, paymentTotals, paymentTerms, deliveryTerms, deliveryDate, lineItems, topNotes, bottomNotes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PurchaseOrder {\n");
    
    sb.append("    schemaVersion: ").append(toIndentedString(schemaVersion)).append("\n");
    sb.append("    documentType: ").append(toIndentedString(documentType)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    orderNumber: ").append(toIndentedString(orderNumber)).append("\n");
    sb.append("    referenceNumber: ").append(toIndentedString(referenceNumber)).append("\n");
    sb.append("    seller: ").append(toIndentedString(seller)).append("\n");
    sb.append("    buyer: ").append(toIndentedString(buyer)).append("\n");
    sb.append("    buyerContacts: ").append(toIndentedString(buyerContacts)).append("\n");
    sb.append("    billedParties: ").append(toIndentedString(billedParties)).append("\n");
    sb.append("    recipientParties: ").append(toIndentedString(recipientParties)).append("\n");
    sb.append("    benefitRecipientParties: ").append(toIndentedString(benefitRecipientParties)).append("\n");
    sb.append("    carriers: ").append(toIndentedString(carriers)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    taxCalculations: ").append(toIndentedString(taxCalculations)).append("\n");
    sb.append("    paymentTotals: ").append(toIndentedString(paymentTotals)).append("\n");
    sb.append("    paymentTerms: ").append(toIndentedString(paymentTerms)).append("\n");
    sb.append("    deliveryTerms: ").append(toIndentedString(deliveryTerms)).append("\n");
    sb.append("    deliveryDate: ").append(toIndentedString(deliveryDate)).append("\n");
    sb.append("    lineItems: ").append(toIndentedString(lineItems)).append("\n");
    sb.append("    topNotes: ").append(toIndentedString(topNotes)).append("\n");
    sb.append("    bottomNotes: ").append(toIndentedString(bottomNotes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
