/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.CurrencyExtraction1;
import com.axonivy.connector.idp.connector.model.FloatExtraction1;
import com.axonivy.connector.idp.connector.model.StringExtraction1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Repayment1
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class Repayment1 {
  @JsonProperty("free_months")
  private FloatExtraction1 freeMonths = null;

  @JsonProperty("initial_amount")
  private FloatExtraction1 initialAmount = null;

  @JsonProperty("rate")
  private FloatExtraction1 rate = null;

  @JsonProperty("currency")
  private CurrencyExtraction1 currency = null;

  @JsonProperty("payment_method")
  private StringExtraction1 paymentMethod = null;

  public Repayment1 freeMonths(FloatExtraction1 freeMonths) {
    this.freeMonths = freeMonths;
    return this;
  }

   /**
   * Get freeMonths
   * @return freeMonths
  **/
  public FloatExtraction1 getFreeMonths() {
    return freeMonths;
  }

  public void setFreeMonths(FloatExtraction1 freeMonths) {
    this.freeMonths = freeMonths;
  }

  public Repayment1 initialAmount(FloatExtraction1 initialAmount) {
    this.initialAmount = initialAmount;
    return this;
  }

   /**
   * Get initialAmount
   * @return initialAmount
  **/
  public FloatExtraction1 getInitialAmount() {
    return initialAmount;
  }

  public void setInitialAmount(FloatExtraction1 initialAmount) {
    this.initialAmount = initialAmount;
  }

  public Repayment1 rate(FloatExtraction1 rate) {
    this.rate = rate;
    return this;
  }

   /**
   * Get rate
   * @return rate
  **/
  public FloatExtraction1 getRate() {
    return rate;
  }

  public void setRate(FloatExtraction1 rate) {
    this.rate = rate;
  }

  public Repayment1 currency(CurrencyExtraction1 currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  public CurrencyExtraction1 getCurrency() {
    return currency;
  }

  public void setCurrency(CurrencyExtraction1 currency) {
    this.currency = currency;
  }

  public Repayment1 paymentMethod(StringExtraction1 paymentMethod) {
    this.paymentMethod = paymentMethod;
    return this;
  }

   /**
   * Get paymentMethod
   * @return paymentMethod
  **/
  public StringExtraction1 getPaymentMethod() {
    return paymentMethod;
  }

  public void setPaymentMethod(StringExtraction1 paymentMethod) {
    this.paymentMethod = paymentMethod;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Repayment1 repayment1 = (Repayment1) o;
    return Objects.equals(this.freeMonths, repayment1.freeMonths) &&
        Objects.equals(this.initialAmount, repayment1.initialAmount) &&
        Objects.equals(this.rate, repayment1.rate) &&
        Objects.equals(this.currency, repayment1.currency) &&
        Objects.equals(this.paymentMethod, repayment1.paymentMethod);
  }

  @Override
  public int hashCode() {
    return Objects.hash(freeMonths, initialAmount, rate, currency, paymentMethod);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Repayment1 {\n");
    
    sb.append("    freeMonths: ").append(toIndentedString(freeMonths)).append("\n");
    sb.append("    initialAmount: ").append(toIndentedString(initialAmount)).append("\n");
    sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
