/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.AddressOptions1;
import com.axonivy.connector.idp.connector.model.StringExtractionOptions1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Seller1
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class Seller1 {
  @JsonProperty("name")
  private StringExtractionOptions1 name = null;

  @JsonProperty("number")
  private StringExtractionOptions1 number = null;

  @JsonProperty("address")
  private AddressOptions1 address = null;

  @JsonProperty("phone")
  private StringExtractionOptions1 phone = null;

  @JsonProperty("fax")
  private StringExtractionOptions1 fax = null;

  @JsonProperty("e_mail")
  private StringExtractionOptions1 eMail = null;

  public Seller1 name(StringExtractionOptions1 name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public StringExtractionOptions1 getName() {
    return name;
  }

  public void setName(StringExtractionOptions1 name) {
    this.name = name;
  }

  public Seller1 number(StringExtractionOptions1 number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  public StringExtractionOptions1 getNumber() {
    return number;
  }

  public void setNumber(StringExtractionOptions1 number) {
    this.number = number;
  }

  public Seller1 address(AddressOptions1 address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  public AddressOptions1 getAddress() {
    return address;
  }

  public void setAddress(AddressOptions1 address) {
    this.address = address;
  }

  public Seller1 phone(StringExtractionOptions1 phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  public StringExtractionOptions1 getPhone() {
    return phone;
  }

  public void setPhone(StringExtractionOptions1 phone) {
    this.phone = phone;
  }

  public Seller1 fax(StringExtractionOptions1 fax) {
    this.fax = fax;
    return this;
  }

   /**
   * Get fax
   * @return fax
  **/
  public StringExtractionOptions1 getFax() {
    return fax;
  }

  public void setFax(StringExtractionOptions1 fax) {
    this.fax = fax;
  }

  public Seller1 eMail(StringExtractionOptions1 eMail) {
    this.eMail = eMail;
    return this;
  }

   /**
   * Get eMail
   * @return eMail
  **/
  public StringExtractionOptions1 getEMail() {
    return eMail;
  }

  public void setEMail(StringExtractionOptions1 eMail) {
    this.eMail = eMail;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Seller1 seller1 = (Seller1) o;
    return Objects.equals(this.name, seller1.name) &&
        Objects.equals(this.number, seller1.number) &&
        Objects.equals(this.address, seller1.address) &&
        Objects.equals(this.phone, seller1.phone) &&
        Objects.equals(this.fax, seller1.fax) &&
        Objects.equals(this.eMail, seller1.eMail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, number, address, phone, fax, eMail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Seller1 {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    fax: ").append(toIndentedString(fax)).append("\n");
    sb.append("    eMail: ").append(toIndentedString(eMail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
