/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.Address1;
import com.axonivy.connector.idp.connector.model.Customer2Name;
import com.axonivy.connector.idp.connector.model.SenderCategoryExtraction1;
import com.axonivy.connector.idp.connector.model.Vendor2EMail;
import com.axonivy.connector.idp.connector.model.Vendor2Fax;
import com.axonivy.connector.idp.connector.model.Vendor2Phone;
import com.axonivy.connector.idp.connector.model.Vendor2Url;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Sender4
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class Sender4 {
  @JsonProperty("name")
  private Customer2Name name = null;

  @JsonProperty("address")
  private Address1 address = null;

  @JsonProperty("phone")
  private Vendor2Phone phone = null;

  @JsonProperty("fax")
  private Vendor2Fax fax = null;

  @JsonProperty("url")
  private Vendor2Url url = null;

  @JsonProperty("e_mail")
  private Vendor2EMail eMail = null;

  @JsonProperty("category")
  private SenderCategoryExtraction1 category = null;

  public Sender4 name(Customer2Name name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public Customer2Name getName() {
    return name;
  }

  public void setName(Customer2Name name) {
    this.name = name;
  }

  public Sender4 address(Address1 address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  public Address1 getAddress() {
    return address;
  }

  public void setAddress(Address1 address) {
    this.address = address;
  }

  public Sender4 phone(Vendor2Phone phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  public Vendor2Phone getPhone() {
    return phone;
  }

  public void setPhone(Vendor2Phone phone) {
    this.phone = phone;
  }

  public Sender4 fax(Vendor2Fax fax) {
    this.fax = fax;
    return this;
  }

   /**
   * Get fax
   * @return fax
  **/
  public Vendor2Fax getFax() {
    return fax;
  }

  public void setFax(Vendor2Fax fax) {
    this.fax = fax;
  }

  public Sender4 url(Vendor2Url url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public Vendor2Url getUrl() {
    return url;
  }

  public void setUrl(Vendor2Url url) {
    this.url = url;
  }

  public Sender4 eMail(Vendor2EMail eMail) {
    this.eMail = eMail;
    return this;
  }

   /**
   * Get eMail
   * @return eMail
  **/
  public Vendor2EMail getEMail() {
    return eMail;
  }

  public void setEMail(Vendor2EMail eMail) {
    this.eMail = eMail;
  }

  public Sender4 category(SenderCategoryExtraction1 category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  public SenderCategoryExtraction1 getCategory() {
    return category;
  }

  public void setCategory(SenderCategoryExtraction1 category) {
    this.category = category;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sender4 sender4 = (Sender4) o;
    return Objects.equals(this.name, sender4.name) &&
        Objects.equals(this.address, sender4.address) &&
        Objects.equals(this.phone, sender4.phone) &&
        Objects.equals(this.fax, sender4.fax) &&
        Objects.equals(this.url, sender4.url) &&
        Objects.equals(this.eMail, sender4.eMail) &&
        Objects.equals(this.category, sender4.category);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, address, phone, fax, url, eMail, category);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sender4 {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    fax: ").append(toIndentedString(fax)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    eMail: ").append(toIndentedString(eMail)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
