/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.StringExtraction1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * Supplier1
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class Supplier1 {
  @JsonProperty("name")
  private StringExtraction1 name = null;

  @JsonProperty("contact")
  private StringExtraction1 contact = null;

  @JsonProperty("address")
  private StringExtraction1 address = null;

  @JsonProperty("phone")
  private List<StringExtraction1> phone = null;

  @JsonProperty("email")
  private StringExtraction1 email = null;

  public Supplier1 name(StringExtraction1 name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public StringExtraction1 getName() {
    return name;
  }

  public void setName(StringExtraction1 name) {
    this.name = name;
  }

  public Supplier1 contact(StringExtraction1 contact) {
    this.contact = contact;
    return this;
  }

   /**
   * Get contact
   * @return contact
  **/
  public StringExtraction1 getContact() {
    return contact;
  }

  public void setContact(StringExtraction1 contact) {
    this.contact = contact;
  }

  public Supplier1 address(StringExtraction1 address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  public StringExtraction1 getAddress() {
    return address;
  }

  public void setAddress(StringExtraction1 address) {
    this.address = address;
  }

  public Supplier1 phone(List<StringExtraction1> phone) {
    this.phone = phone;
    return this;
  }

  public Supplier1 addPhoneItem(StringExtraction1 phoneItem) {
    if (this.phone == null) {
      this.phone = new ArrayList<>();
    }
    this.phone.add(phoneItem);
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  public List<StringExtraction1> getPhone() {
    return phone;
  }

  public void setPhone(List<StringExtraction1> phone) {
    this.phone = phone;
  }

  public Supplier1 email(StringExtraction1 email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  public StringExtraction1 getEmail() {
    return email;
  }

  public void setEmail(StringExtraction1 email) {
    this.email = email;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Supplier1 supplier1 = (Supplier1) o;
    return Objects.equals(this.name, supplier1.name) &&
        Objects.equals(this.contact, supplier1.contact) &&
        Objects.equals(this.address, supplier1.address) &&
        Objects.equals(this.phone, supplier1.phone) &&
        Objects.equals(this.email, supplier1.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, contact, address, phone, email);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Supplier1 {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    contact: ").append(toIndentedString(contact)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
