/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.StringExtraction1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * TaxType
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class TaxType {
  @JsonProperty("heading")
  private StringExtraction1 heading = null;

  @JsonProperty("sub_heading")
  private StringExtraction1 subHeading = null;

  public TaxType heading(StringExtraction1 heading) {
    this.heading = heading;
    return this;
  }

   /**
   * Get heading
   * @return heading
  **/
  public StringExtraction1 getHeading() {
    return heading;
  }

  public void setHeading(StringExtraction1 heading) {
    this.heading = heading;
  }

  public TaxType subHeading(StringExtraction1 subHeading) {
    this.subHeading = subHeading;
    return this;
  }

   /**
   * Get subHeading
   * @return subHeading
  **/
  public StringExtraction1 getSubHeading() {
    return subHeading;
  }

  public void setSubHeading(StringExtraction1 subHeading) {
    this.subHeading = subHeading;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaxType taxType = (TaxType) o;
    return Objects.equals(this.heading, taxType.heading) &&
        Objects.equals(this.subHeading, taxType.subHeading);
  }

  @Override
  public int hashCode() {
    return Objects.hash(heading, subHeading);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaxType {\n");
    
    sb.append("    heading: ").append(toIndentedString(heading)).append("\n");
    sb.append("    subHeading: ").append(toIndentedString(subHeading)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
