/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.StringExtraction1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Trailer1
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class Trailer1 {
  @JsonProperty("container")
  private StringExtraction1 container = null;

  @JsonProperty("seal")
  private StringExtraction1 seal = null;

  public Trailer1 container(StringExtraction1 container) {
    this.container = container;
    return this;
  }

   /**
   * Get container
   * @return container
  **/
  public StringExtraction1 getContainer() {
    return container;
  }

  public void setContainer(StringExtraction1 container) {
    this.container = container;
  }

  public Trailer1 seal(StringExtraction1 seal) {
    this.seal = seal;
    return this;
  }

   /**
   * Get seal
   * @return seal
  **/
  public StringExtraction1 getSeal() {
    return seal;
  }

  public void setSeal(StringExtraction1 seal) {
    this.seal = seal;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Trailer1 trailer1 = (Trailer1) o;
    return Objects.equals(this.container, trailer1.container) &&
        Objects.equals(this.seal, trailer1.seal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(container, seal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Trailer1 {\n");
    
    sb.append("    container: ").append(toIndentedString(container)).append("\n");
    sb.append("    seal: ").append(toIndentedString(seal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
