/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.DateExtraction1;
import com.axonivy.connector.idp.connector.model.FloatExtraction1;
import com.axonivy.connector.idp.connector.model.StringExtraction1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Transaction
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class Transaction {
  @JsonProperty("date")
  private DateExtraction1 date = null;

  @JsonProperty("transaction_date")
  private DateExtraction1 transactionDate = null;

  @JsonProperty("text")
  private StringExtraction1 text = null;

  @JsonProperty("amount")
  private FloatExtraction1 amount = null;

  public Transaction date(DateExtraction1 date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  public DateExtraction1 getDate() {
    return date;
  }

  public void setDate(DateExtraction1 date) {
    this.date = date;
  }

  public Transaction transactionDate(DateExtraction1 transactionDate) {
    this.transactionDate = transactionDate;
    return this;
  }

   /**
   * Get transactionDate
   * @return transactionDate
  **/
  public DateExtraction1 getTransactionDate() {
    return transactionDate;
  }

  public void setTransactionDate(DateExtraction1 transactionDate) {
    this.transactionDate = transactionDate;
  }

  public Transaction text(StringExtraction1 text) {
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  public StringExtraction1 getText() {
    return text;
  }

  public void setText(StringExtraction1 text) {
    this.text = text;
  }

  public Transaction amount(FloatExtraction1 amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  public FloatExtraction1 getAmount() {
    return amount;
  }

  public void setAmount(FloatExtraction1 amount) {
    this.amount = amount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transaction transaction = (Transaction) o;
    return Objects.equals(this.date, transaction.date) &&
        Objects.equals(this.transactionDate, transaction.transactionDate) &&
        Objects.equals(this.text, transaction.text) &&
        Objects.equals(this.amount, transaction.amount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, transactionDate, text, amount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transaction {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    transactionDate: ").append(toIndentedString(transactionDate)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
