/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.UsageForDocType1;
import com.axonivy.connector.idp.connector.model.UsageForProcessDefinition1;
import com.axonivy.connector.idp.connector.model.UsageForProcessingStep1;
import com.axonivy.connector.idp.connector.model.UsageForTaskDefinition1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * Total usage statistics
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class UsageStatsResponseTotalUsage {
  @JsonProperty("nr_docs")
  private Integer nrDocs = null;

  @JsonProperty("nr_pages")
  private Integer nrPages = null;

  @JsonProperty("by_doc_type")
  private List<UsageForDocType1> byDocType = new ArrayList<>();

  @JsonProperty("by_processing_step")
  private List<UsageForProcessingStep1> byProcessingStep = new ArrayList<>();

  @JsonProperty("by_process_definition")
  private List<UsageForProcessDefinition1> byProcessDefinition = new ArrayList<>();

  @JsonProperty("by_task_definition")
  private List<UsageForTaskDefinition1> byTaskDefinition = new ArrayList<>();

  public UsageStatsResponseTotalUsage nrDocs(Integer nrDocs) {
    this.nrDocs = nrDocs;
    return this;
  }

   /**
   * Total number of documents.
   * @return nrDocs
  **/
  public Integer getNrDocs() {
    return nrDocs;
  }

  public void setNrDocs(Integer nrDocs) {
    this.nrDocs = nrDocs;
  }

  public UsageStatsResponseTotalUsage nrPages(Integer nrPages) {
    this.nrPages = nrPages;
    return this;
  }

   /**
   * Sum of pages in all documents.
   * @return nrPages
  **/
  public Integer getNrPages() {
    return nrPages;
  }

  public void setNrPages(Integer nrPages) {
    this.nrPages = nrPages;
  }

  public UsageStatsResponseTotalUsage byDocType(List<UsageForDocType1> byDocType) {
    this.byDocType = byDocType;
    return this;
  }

  public UsageStatsResponseTotalUsage addByDocTypeItem(UsageForDocType1 byDocTypeItem) {
    this.byDocType.add(byDocTypeItem);
    return this;
  }

   /**
   * Usage aggregated by the type of document.
   * @return byDocType
  **/
  public List<UsageForDocType1> getByDocType() {
    return byDocType;
  }

  public void setByDocType(List<UsageForDocType1> byDocType) {
    this.byDocType = byDocType;
  }

  public UsageStatsResponseTotalUsage byProcessingStep(List<UsageForProcessingStep1> byProcessingStep) {
    this.byProcessingStep = byProcessingStep;
    return this;
  }

  public UsageStatsResponseTotalUsage addByProcessingStepItem(UsageForProcessingStep1 byProcessingStepItem) {
    this.byProcessingStep.add(byProcessingStepItem);
    return this;
  }

   /**
   * Usage aggregated by detailed processing step.
   * @return byProcessingStep
  **/
  public List<UsageForProcessingStep1> getByProcessingStep() {
    return byProcessingStep;
  }

  public void setByProcessingStep(List<UsageForProcessingStep1> byProcessingStep) {
    this.byProcessingStep = byProcessingStep;
  }

  public UsageStatsResponseTotalUsage byProcessDefinition(List<UsageForProcessDefinition1> byProcessDefinition) {
    this.byProcessDefinition = byProcessDefinition;
    return this;
  }

  public UsageStatsResponseTotalUsage addByProcessDefinitionItem(UsageForProcessDefinition1 byProcessDefinitionItem) {
    this.byProcessDefinition.add(byProcessDefinitionItem);
    return this;
  }

   /**
   * Usage aggregated by process definition. Only for documents processed with the workflow system.
   * @return byProcessDefinition
  **/
  public List<UsageForProcessDefinition1> getByProcessDefinition() {
    return byProcessDefinition;
  }

  public void setByProcessDefinition(List<UsageForProcessDefinition1> byProcessDefinition) {
    this.byProcessDefinition = byProcessDefinition;
  }

  public UsageStatsResponseTotalUsage byTaskDefinition(List<UsageForTaskDefinition1> byTaskDefinition) {
    this.byTaskDefinition = byTaskDefinition;
    return this;
  }

  public UsageStatsResponseTotalUsage addByTaskDefinitionItem(UsageForTaskDefinition1 byTaskDefinitionItem) {
    this.byTaskDefinition.add(byTaskDefinitionItem);
    return this;
  }

   /**
   * Usage aggregated by processing task. Only for documents processed with the workflow system.
   * @return byTaskDefinition
  **/
  public List<UsageForTaskDefinition1> getByTaskDefinition() {
    return byTaskDefinition;
  }

  public void setByTaskDefinition(List<UsageForTaskDefinition1> byTaskDefinition) {
    this.byTaskDefinition = byTaskDefinition;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsageStatsResponseTotalUsage usageStatsResponseTotalUsage = (UsageStatsResponseTotalUsage) o;
    return Objects.equals(this.nrDocs, usageStatsResponseTotalUsage.nrDocs) &&
        Objects.equals(this.nrPages, usageStatsResponseTotalUsage.nrPages) &&
        Objects.equals(this.byDocType, usageStatsResponseTotalUsage.byDocType) &&
        Objects.equals(this.byProcessingStep, usageStatsResponseTotalUsage.byProcessingStep) &&
        Objects.equals(this.byProcessDefinition, usageStatsResponseTotalUsage.byProcessDefinition) &&
        Objects.equals(this.byTaskDefinition, usageStatsResponseTotalUsage.byTaskDefinition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nrDocs, nrPages, byDocType, byProcessingStep, byProcessDefinition, byTaskDefinition);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsageStatsResponseTotalUsage {\n");
    
    sb.append("    nrDocs: ").append(toIndentedString(nrDocs)).append("\n");
    sb.append("    nrPages: ").append(toIndentedString(nrPages)).append("\n");
    sb.append("    byDocType: ").append(toIndentedString(byDocType)).append("\n");
    sb.append("    byProcessingStep: ").append(toIndentedString(byProcessingStep)).append("\n");
    sb.append("    byProcessDefinition: ").append(toIndentedString(byProcessDefinition)).append("\n");
    sb.append("    byTaskDefinition: ").append(toIndentedString(byTaskDefinition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
