/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.idp.connector.model.FloatExtraction1;
import com.axonivy.connector.idp.connector.model.StringExtraction1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * VehicleExpertReport
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-12T09:36:24.744976100+07:00[Asia/Bangkok]")
public class VehicleExpertReport {
  /**
   * Gets or Sets schemaVersion
   */
  public enum SchemaVersionEnum {
    NUMBER_1(1);

    private Integer value;

    SchemaVersionEnum(Integer value) {
      this.value = value;
    }
    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SchemaVersionEnum fromValue(Integer input) {
      for (SchemaVersionEnum b : SchemaVersionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("schema_version")
  private SchemaVersionEnum schemaVersion = SchemaVersionEnum.NUMBER_1;

  /**
   * Gets or Sets documentType
   */
  public enum DocumentTypeEnum {
    VEHICLE_EXPERT_REPORT("vehicle_expert_report");

    private String value;

    DocumentTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static DocumentTypeEnum fromValue(String input) {
      for (DocumentTypeEnum b : DocumentTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("document_type")
  private DocumentTypeEnum documentType = null;

  @JsonProperty("number")
  private StringExtraction1 number = null;

  @JsonProperty("estimated_repair_costs_net")
  private FloatExtraction1 estimatedRepairCostsNet = null;

  @JsonProperty("estimated_repair_costs_gross")
  private FloatExtraction1 estimatedRepairCostsGross = null;

  @JsonProperty("residual_value")
  private FloatExtraction1 residualValue = null;

  @JsonProperty("replacement_value_net")
  private FloatExtraction1 replacementValueNet = null;

  @JsonProperty("replacement_value_gross")
  private FloatExtraction1 replacementValueGross = null;

  @JsonProperty("transfer_cost_net")
  private FloatExtraction1 transferCostNet = null;

  @JsonProperty("transfer_cost_gross")
  private FloatExtraction1 transferCostGross = null;

  @JsonProperty("upe_surcharge_net")
  private FloatExtraction1 upeSurchargeNet = null;

  @JsonProperty("upe_surcharge_gross")
  private FloatExtraction1 upeSurchargeGross = null;

  @JsonProperty("value_loss")
  private FloatExtraction1 valueLoss = null;

  @JsonProperty("license_plate_number")
  private StringExtraction1 licensePlateNumber = null;

  @JsonProperty("vehicle_identification_number")
  private StringExtraction1 vehicleIdentificationNumber = null;

  public VehicleExpertReport schemaVersion(SchemaVersionEnum schemaVersion) {
    this.schemaVersion = schemaVersion;
    return this;
  }

   /**
   * Get schemaVersion
   * @return schemaVersion
  **/
  public SchemaVersionEnum getSchemaVersion() {
    return schemaVersion;
  }

  public void setSchemaVersion(SchemaVersionEnum schemaVersion) {
    this.schemaVersion = schemaVersion;
  }

  public VehicleExpertReport documentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
    return this;
  }

   /**
   * Get documentType
   * @return documentType
  **/
  public DocumentTypeEnum getDocumentType() {
    return documentType;
  }

  public void setDocumentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
  }

  public VehicleExpertReport number(StringExtraction1 number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  public StringExtraction1 getNumber() {
    return number;
  }

  public void setNumber(StringExtraction1 number) {
    this.number = number;
  }

  public VehicleExpertReport estimatedRepairCostsNet(FloatExtraction1 estimatedRepairCostsNet) {
    this.estimatedRepairCostsNet = estimatedRepairCostsNet;
    return this;
  }

   /**
   * Get estimatedRepairCostsNet
   * @return estimatedRepairCostsNet
  **/
  public FloatExtraction1 getEstimatedRepairCostsNet() {
    return estimatedRepairCostsNet;
  }

  public void setEstimatedRepairCostsNet(FloatExtraction1 estimatedRepairCostsNet) {
    this.estimatedRepairCostsNet = estimatedRepairCostsNet;
  }

  public VehicleExpertReport estimatedRepairCostsGross(FloatExtraction1 estimatedRepairCostsGross) {
    this.estimatedRepairCostsGross = estimatedRepairCostsGross;
    return this;
  }

   /**
   * Get estimatedRepairCostsGross
   * @return estimatedRepairCostsGross
  **/
  public FloatExtraction1 getEstimatedRepairCostsGross() {
    return estimatedRepairCostsGross;
  }

  public void setEstimatedRepairCostsGross(FloatExtraction1 estimatedRepairCostsGross) {
    this.estimatedRepairCostsGross = estimatedRepairCostsGross;
  }

  public VehicleExpertReport residualValue(FloatExtraction1 residualValue) {
    this.residualValue = residualValue;
    return this;
  }

   /**
   * Get residualValue
   * @return residualValue
  **/
  public FloatExtraction1 getResidualValue() {
    return residualValue;
  }

  public void setResidualValue(FloatExtraction1 residualValue) {
    this.residualValue = residualValue;
  }

  public VehicleExpertReport replacementValueNet(FloatExtraction1 replacementValueNet) {
    this.replacementValueNet = replacementValueNet;
    return this;
  }

   /**
   * Get replacementValueNet
   * @return replacementValueNet
  **/
  public FloatExtraction1 getReplacementValueNet() {
    return replacementValueNet;
  }

  public void setReplacementValueNet(FloatExtraction1 replacementValueNet) {
    this.replacementValueNet = replacementValueNet;
  }

  public VehicleExpertReport replacementValueGross(FloatExtraction1 replacementValueGross) {
    this.replacementValueGross = replacementValueGross;
    return this;
  }

   /**
   * Get replacementValueGross
   * @return replacementValueGross
  **/
  public FloatExtraction1 getReplacementValueGross() {
    return replacementValueGross;
  }

  public void setReplacementValueGross(FloatExtraction1 replacementValueGross) {
    this.replacementValueGross = replacementValueGross;
  }

  public VehicleExpertReport transferCostNet(FloatExtraction1 transferCostNet) {
    this.transferCostNet = transferCostNet;
    return this;
  }

   /**
   * Get transferCostNet
   * @return transferCostNet
  **/
  public FloatExtraction1 getTransferCostNet() {
    return transferCostNet;
  }

  public void setTransferCostNet(FloatExtraction1 transferCostNet) {
    this.transferCostNet = transferCostNet;
  }

  public VehicleExpertReport transferCostGross(FloatExtraction1 transferCostGross) {
    this.transferCostGross = transferCostGross;
    return this;
  }

   /**
   * Get transferCostGross
   * @return transferCostGross
  **/
  public FloatExtraction1 getTransferCostGross() {
    return transferCostGross;
  }

  public void setTransferCostGross(FloatExtraction1 transferCostGross) {
    this.transferCostGross = transferCostGross;
  }

  public VehicleExpertReport upeSurchargeNet(FloatExtraction1 upeSurchargeNet) {
    this.upeSurchargeNet = upeSurchargeNet;
    return this;
  }

   /**
   * Get upeSurchargeNet
   * @return upeSurchargeNet
  **/
  public FloatExtraction1 getUpeSurchargeNet() {
    return upeSurchargeNet;
  }

  public void setUpeSurchargeNet(FloatExtraction1 upeSurchargeNet) {
    this.upeSurchargeNet = upeSurchargeNet;
  }

  public VehicleExpertReport upeSurchargeGross(FloatExtraction1 upeSurchargeGross) {
    this.upeSurchargeGross = upeSurchargeGross;
    return this;
  }

   /**
   * Get upeSurchargeGross
   * @return upeSurchargeGross
  **/
  public FloatExtraction1 getUpeSurchargeGross() {
    return upeSurchargeGross;
  }

  public void setUpeSurchargeGross(FloatExtraction1 upeSurchargeGross) {
    this.upeSurchargeGross = upeSurchargeGross;
  }

  public VehicleExpertReport valueLoss(FloatExtraction1 valueLoss) {
    this.valueLoss = valueLoss;
    return this;
  }

   /**
   * Get valueLoss
   * @return valueLoss
  **/
  public FloatExtraction1 getValueLoss() {
    return valueLoss;
  }

  public void setValueLoss(FloatExtraction1 valueLoss) {
    this.valueLoss = valueLoss;
  }

  public VehicleExpertReport licensePlateNumber(StringExtraction1 licensePlateNumber) {
    this.licensePlateNumber = licensePlateNumber;
    return this;
  }

   /**
   * Get licensePlateNumber
   * @return licensePlateNumber
  **/
  public StringExtraction1 getLicensePlateNumber() {
    return licensePlateNumber;
  }

  public void setLicensePlateNumber(StringExtraction1 licensePlateNumber) {
    this.licensePlateNumber = licensePlateNumber;
  }

  public VehicleExpertReport vehicleIdentificationNumber(StringExtraction1 vehicleIdentificationNumber) {
    this.vehicleIdentificationNumber = vehicleIdentificationNumber;
    return this;
  }

   /**
   * Get vehicleIdentificationNumber
   * @return vehicleIdentificationNumber
  **/
  public StringExtraction1 getVehicleIdentificationNumber() {
    return vehicleIdentificationNumber;
  }

  public void setVehicleIdentificationNumber(StringExtraction1 vehicleIdentificationNumber) {
    this.vehicleIdentificationNumber = vehicleIdentificationNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VehicleExpertReport vehicleExpertReport = (VehicleExpertReport) o;
    return Objects.equals(this.schemaVersion, vehicleExpertReport.schemaVersion) &&
        Objects.equals(this.documentType, vehicleExpertReport.documentType) &&
        Objects.equals(this.number, vehicleExpertReport.number) &&
        Objects.equals(this.estimatedRepairCostsNet, vehicleExpertReport.estimatedRepairCostsNet) &&
        Objects.equals(this.estimatedRepairCostsGross, vehicleExpertReport.estimatedRepairCostsGross) &&
        Objects.equals(this.residualValue, vehicleExpertReport.residualValue) &&
        Objects.equals(this.replacementValueNet, vehicleExpertReport.replacementValueNet) &&
        Objects.equals(this.replacementValueGross, vehicleExpertReport.replacementValueGross) &&
        Objects.equals(this.transferCostNet, vehicleExpertReport.transferCostNet) &&
        Objects.equals(this.transferCostGross, vehicleExpertReport.transferCostGross) &&
        Objects.equals(this.upeSurchargeNet, vehicleExpertReport.upeSurchargeNet) &&
        Objects.equals(this.upeSurchargeGross, vehicleExpertReport.upeSurchargeGross) &&
        Objects.equals(this.valueLoss, vehicleExpertReport.valueLoss) &&
        Objects.equals(this.licensePlateNumber, vehicleExpertReport.licensePlateNumber) &&
        Objects.equals(this.vehicleIdentificationNumber, vehicleExpertReport.vehicleIdentificationNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(schemaVersion, documentType, number, estimatedRepairCostsNet, estimatedRepairCostsGross, residualValue, replacementValueNet, replacementValueGross, transferCostNet, transferCostGross, upeSurchargeNet, upeSurchargeGross, valueLoss, licensePlateNumber, vehicleIdentificationNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VehicleExpertReport {\n");
    
    sb.append("    schemaVersion: ").append(toIndentedString(schemaVersion)).append("\n");
    sb.append("    documentType: ").append(toIndentedString(documentType)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    estimatedRepairCostsNet: ").append(toIndentedString(estimatedRepairCostsNet)).append("\n");
    sb.append("    estimatedRepairCostsGross: ").append(toIndentedString(estimatedRepairCostsGross)).append("\n");
    sb.append("    residualValue: ").append(toIndentedString(residualValue)).append("\n");
    sb.append("    replacementValueNet: ").append(toIndentedString(replacementValueNet)).append("\n");
    sb.append("    replacementValueGross: ").append(toIndentedString(replacementValueGross)).append("\n");
    sb.append("    transferCostNet: ").append(toIndentedString(transferCostNet)).append("\n");
    sb.append("    transferCostGross: ").append(toIndentedString(transferCostGross)).append("\n");
    sb.append("    upeSurchargeNet: ").append(toIndentedString(upeSurchargeNet)).append("\n");
    sb.append("    upeSurchargeGross: ").append(toIndentedString(upeSurchargeGross)).append("\n");
    sb.append("    valueLoss: ").append(toIndentedString(valueLoss)).append("\n");
    sb.append("    licensePlateNumber: ").append(toIndentedString(licensePlateNumber)).append("\n");
    sb.append("    vehicleIdentificationNumber: ").append(toIndentedString(vehicleIdentificationNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
